Library renamed

diff --git a/scilab/modules/parse/Makefile.in b/scilab/modules/parse/Makefile.in
--- a/scilab/modules/parse/Makefile.in
+++ b/scilab/modules/parse/Makefile.in
@@ -79,16 +79,16 @@ am__strip_dir = `echo $$p | sed -e 's|^.*/||'`;
 am__installdirs = "$(DESTDIR)$(pkglibdir)"
 pkglibLTLIBRARIES_INSTALL = $(INSTALL)
 LTLIBRARIES = $(pkglib_LTLIBRARIES)
-libsciParse_la_LIBADD =
-am__objects_1 = libsciParse_la-parsescilab.lo
-am__objects_2 = libsciParse_la-scanscilab.lo
+libsciparse_la_LIBADD =
+am__objects_1 = libsciparse_la-parsescilab.lo
+am__objects_2 = libsciparse_la-scanscilab.lo
 am__objects_3 = $(am__objects_1) $(am__objects_2) \
-	libsciParse_la-parser.lo libsciParse_la-printerror.lo
-am_libsciParse_la_OBJECTS = $(am__objects_3)
-libsciParse_la_OBJECTS = $(am_libsciParse_la_OBJECTS)
-libsciParse_la_LINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) \
+	libsciparse_la-parser.lo libsciparse_la-printerror.lo
+am_libsciparse_la_OBJECTS = $(am__objects_3)
+libsciparse_la_OBJECTS = $(am_libsciparse_la_OBJECTS)
+libsciparse_la_LINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) \
 	$(LIBTOOLFLAGS) --mode=link $(CXXLD) \
-	$(libsciParse_la_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) \
+	$(libsciparse_la_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) \
 	$(LDFLAGS) -o $@
 DEFAULT_INCLUDES = -I.@am__isrc@ -I$(top_builddir)/modules/core/includes
 depcomp = $(SHELL) $(top_srcdir)/config/depcomp
@@ -102,8 +102,8 @@ CXXLD = $(CXX)
 CXXLINK = $(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) \
 	--mode=link $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) \
 	$(LDFLAGS) -o $@
-SOURCES = $(libsciParse_la_SOURCES)
-DIST_SOURCES = $(libsciParse_la_SOURCES)
+SOURCES = $(libsciparse_la_SOURCES)
+DIST_SOURCES = $(libsciparse_la_SOURCES)
 ETAGS = etags
 CTAGS = ctags
 DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
@@ -312,9 +312,9 @@ PARSE_CPP_SOURCES = $(BISON_PARSESCILAB_CPP) \
 			src/cpp/parser.cpp \
 			src/cpp/printerror.cpp
 
-pkglib_LTLIBRARIES = libsciParse.la
-libsciParse_la_SOURCES = $(PARSE_CPP_SOURCES)
-libsciParse_la_CXXFLAGS = -I$(top_builddir)/modules/core/includes \
+pkglib_LTLIBRARIES = libsciparse.la
+libsciparse_la_SOURCES = $(PARSE_CPP_SOURCES)
+libsciparse_la_CXXFLAGS = -I$(top_builddir)/modules/core/includes \
 			-I$(top_builddir)/modules/abstractSyntaxTree/includes \
 			-I$(top_builddir)/modules/symbol/includes \
 			-Iincludes \
@@ -446,8 +446,8 @@ clean-pkglibLTLIBRARIES:
 	  echo "rm -f \"$${dir}/so_locations\""; \
 	  rm -f "$${dir}/so_locations"; \
 	done
-libsciParse.la: $(libsciParse_la_OBJECTS) $(libsciParse_la_DEPENDENCIES) 
-	$(libsciParse_la_LINK) -rpath $(pkglibdir) $(libsciParse_la_OBJECTS) $(libsciParse_la_LIBADD) $(LIBS)
+libsciparse.la: $(libsciparse_la_OBJECTS) $(libsciparse_la_DEPENDENCIES) 
+	$(libsciparse_la_LINK) -rpath $(pkglibdir) $(libsciparse_la_OBJECTS) $(libsciparse_la_LIBADD) $(LIBS)
 
 mostlyclean-compile:
 	-rm -f *.$(OBJEXT)
@@ -455,10 +455,10 @@ mostlyclean-compile:
 distclean-compile:
 	-rm -f *.tab.c
 
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/libsciParse_la-parser.Plo@am__quote@
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/libsciParse_la-parsescilab.Plo@am__quote@
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/libsciParse_la-printerror.Plo@am__quote@
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/libsciParse_la-scanscilab.Plo@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/libsciparse_la-parser.Plo@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/libsciparse_la-parsescilab.Plo@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/libsciparse_la-printerror.Plo@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/libsciparse_la-scanscilab.Plo@am__quote@
 
 .cpp.o:
 @am__fastdepCXX_TRUE@	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
@@ -481,33 +481,33 @@ distclean-compile:
 @AMDEP_TRUE@@am__fastdepCXX_FALSE@	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) @AMDEPBACKSLASH@
 @am__fastdepCXX_FALSE@	$(LTCXXCOMPILE) -c -o $@ $<
 
-libsciParse_la-parsescilab.lo: src/cpp/parsescilab.cpp
-@am__fastdepCXX_TRUE@	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libsciParse_la_CXXFLAGS) $(CXXFLAGS) -MT libsciParse_la-parsescilab.lo -MD -MP -MF $(DEPDIR)/libsciParse_la-parsescilab.Tpo -c -o libsciParse_la-parsescilab.lo `test -f 'src/cpp/parsescilab.cpp' || echo '$(srcdir)/'`src/cpp/parsescilab.cpp
-@am__fastdepCXX_TRUE@	mv -f $(DEPDIR)/libsciParse_la-parsescilab.Tpo $(DEPDIR)/libsciParse_la-parsescilab.Plo
-@AMDEP_TRUE@@am__fastdepCXX_FALSE@	source='src/cpp/parsescilab.cpp' object='libsciParse_la-parsescilab.lo' libtool=yes @AMDEPBACKSLASH@
+libsciparse_la-parsescilab.lo: src/cpp/parsescilab.cpp
+@am__fastdepCXX_TRUE@	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libsciparse_la_CXXFLAGS) $(CXXFLAGS) -MT libsciparse_la-parsescilab.lo -MD -MP -MF $(DEPDIR)/libsciparse_la-parsescilab.Tpo -c -o libsciparse_la-parsescilab.lo `test -f 'src/cpp/parsescilab.cpp' || echo '$(srcdir)/'`src/cpp/parsescilab.cpp
+@am__fastdepCXX_TRUE@	mv -f $(DEPDIR)/libsciparse_la-parsescilab.Tpo $(DEPDIR)/libsciparse_la-parsescilab.Plo
+@AMDEP_TRUE@@am__fastdepCXX_FALSE@	source='src/cpp/parsescilab.cpp' object='libsciparse_la-parsescilab.lo' libtool=yes @AMDEPBACKSLASH@
 @AMDEP_TRUE@@am__fastdepCXX_FALSE@	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) @AMDEPBACKSLASH@
-@am__fastdepCXX_FALSE@	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libsciParse_la_CXXFLAGS) $(CXXFLAGS) -c -o libsciParse_la-parsescilab.lo `test -f 'src/cpp/parsescilab.cpp' || echo '$(srcdir)/'`src/cpp/parsescilab.cpp
+@am__fastdepCXX_FALSE@	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libsciparse_la_CXXFLAGS) $(CXXFLAGS) -c -o libsciparse_la-parsescilab.lo `test -f 'src/cpp/parsescilab.cpp' || echo '$(srcdir)/'`src/cpp/parsescilab.cpp
 
-libsciParse_la-scanscilab.lo: src/cpp/scanscilab.cpp
-@am__fastdepCXX_TRUE@	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libsciParse_la_CXXFLAGS) $(CXXFLAGS) -MT libsciParse_la-scanscilab.lo -MD -MP -MF $(DEPDIR)/libsciParse_la-scanscilab.Tpo -c -o libsciParse_la-scanscilab.lo `test -f 'src/cpp/scanscilab.cpp' || echo '$(srcdir)/'`src/cpp/scanscilab.cpp
-@am__fastdepCXX_TRUE@	mv -f $(DEPDIR)/libsciParse_la-scanscilab.Tpo $(DEPDIR)/libsciParse_la-scanscilab.Plo
-@AMDEP_TRUE@@am__fastdepCXX_FALSE@	source='src/cpp/scanscilab.cpp' object='libsciParse_la-scanscilab.lo' libtool=yes @AMDEPBACKSLASH@
+libsciparse_la-scanscilab.lo: src/cpp/scanscilab.cpp
+@am__fastdepCXX_TRUE@	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libsciparse_la_CXXFLAGS) $(CXXFLAGS) -MT libsciparse_la-scanscilab.lo -MD -MP -MF $(DEPDIR)/libsciparse_la-scanscilab.Tpo -c -o libsciparse_la-scanscilab.lo `test -f 'src/cpp/scanscilab.cpp' || echo '$(srcdir)/'`src/cpp/scanscilab.cpp
+@am__fastdepCXX_TRUE@	mv -f $(DEPDIR)/libsciparse_la-scanscilab.Tpo $(DEPDIR)/libsciparse_la-scanscilab.Plo
+@AMDEP_TRUE@@am__fastdepCXX_FALSE@	source='src/cpp/scanscilab.cpp' object='libsciparse_la-scanscilab.lo' libtool=yes @AMDEPBACKSLASH@
 @AMDEP_TRUE@@am__fastdepCXX_FALSE@	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) @AMDEPBACKSLASH@
-@am__fastdepCXX_FALSE@	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libsciParse_la_CXXFLAGS) $(CXXFLAGS) -c -o libsciParse_la-scanscilab.lo `test -f 'src/cpp/scanscilab.cpp' || echo '$(srcdir)/'`src/cpp/scanscilab.cpp
+@am__fastdepCXX_FALSE@	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libsciparse_la_CXXFLAGS) $(CXXFLAGS) -c -o libsciparse_la-scanscilab.lo `test -f 'src/cpp/scanscilab.cpp' || echo '$(srcdir)/'`src/cpp/scanscilab.cpp
 
-libsciParse_la-parser.lo: src/cpp/parser.cpp
-@am__fastdepCXX_TRUE@	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libsciParse_la_CXXFLAGS) $(CXXFLAGS) -MT libsciParse_la-parser.lo -MD -MP -MF $(DEPDIR)/libsciParse_la-parser.Tpo -c -o libsciParse_la-parser.lo `test -f 'src/cpp/parser.cpp' || echo '$(srcdir)/'`src/cpp/parser.cpp
-@am__fastdepCXX_TRUE@	mv -f $(DEPDIR)/libsciParse_la-parser.Tpo $(DEPDIR)/libsciParse_la-parser.Plo
-@AMDEP_TRUE@@am__fastdepCXX_FALSE@	source='src/cpp/parser.cpp' object='libsciParse_la-parser.lo' libtool=yes @AMDEPBACKSLASH@
+libsciparse_la-parser.lo: src/cpp/parser.cpp
+@am__fastdepCXX_TRUE@	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libsciparse_la_CXXFLAGS) $(CXXFLAGS) -MT libsciparse_la-parser.lo -MD -MP -MF $(DEPDIR)/libsciparse_la-parser.Tpo -c -o libsciparse_la-parser.lo `test -f 'src/cpp/parser.cpp' || echo '$(srcdir)/'`src/cpp/parser.cpp
+@am__fastdepCXX_TRUE@	mv -f $(DEPDIR)/libsciparse_la-parser.Tpo $(DEPDIR)/libsciparse_la-parser.Plo
+@AMDEP_TRUE@@am__fastdepCXX_FALSE@	source='src/cpp/parser.cpp' object='libsciparse_la-parser.lo' libtool=yes @AMDEPBACKSLASH@
 @AMDEP_TRUE@@am__fastdepCXX_FALSE@	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) @AMDEPBACKSLASH@
-@am__fastdepCXX_FALSE@	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libsciParse_la_CXXFLAGS) $(CXXFLAGS) -c -o libsciParse_la-parser.lo `test -f 'src/cpp/parser.cpp' || echo '$(srcdir)/'`src/cpp/parser.cpp
+@am__fastdepCXX_FALSE@	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libsciparse_la_CXXFLAGS) $(CXXFLAGS) -c -o libsciparse_la-parser.lo `test -f 'src/cpp/parser.cpp' || echo '$(srcdir)/'`src/cpp/parser.cpp
 
-libsciParse_la-printerror.lo: src/cpp/printerror.cpp
-@am__fastdepCXX_TRUE@	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libsciParse_la_CXXFLAGS) $(CXXFLAGS) -MT libsciParse_la-printerror.lo -MD -MP -MF $(DEPDIR)/libsciParse_la-printerror.Tpo -c -o libsciParse_la-printerror.lo `test -f 'src/cpp/printerror.cpp' || echo '$(srcdir)/'`src/cpp/printerror.cpp
-@am__fastdepCXX_TRUE@	mv -f $(DEPDIR)/libsciParse_la-printerror.Tpo $(DEPDIR)/libsciParse_la-printerror.Plo
-@AMDEP_TRUE@@am__fastdepCXX_FALSE@	source='src/cpp/printerror.cpp' object='libsciParse_la-printerror.lo' libtool=yes @AMDEPBACKSLASH@
+libsciparse_la-printerror.lo: src/cpp/printerror.cpp
+@am__fastdepCXX_TRUE@	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libsciparse_la_CXXFLAGS) $(CXXFLAGS) -MT libsciparse_la-printerror.lo -MD -MP -MF $(DEPDIR)/libsciparse_la-printerror.Tpo -c -o libsciparse_la-printerror.lo `test -f 'src/cpp/printerror.cpp' || echo '$(srcdir)/'`src/cpp/printerror.cpp
+@am__fastdepCXX_TRUE@	mv -f $(DEPDIR)/libsciparse_la-printerror.Tpo $(DEPDIR)/libsciparse_la-printerror.Plo
+@AMDEP_TRUE@@am__fastdepCXX_FALSE@	source='src/cpp/printerror.cpp' object='libsciparse_la-printerror.lo' libtool=yes @AMDEPBACKSLASH@
 @AMDEP_TRUE@@am__fastdepCXX_FALSE@	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) @AMDEPBACKSLASH@
-@am__fastdepCXX_FALSE@	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libsciParse_la_CXXFLAGS) $(CXXFLAGS) -c -o libsciParse_la-printerror.lo `test -f 'src/cpp/printerror.cpp' || echo '$(srcdir)/'`src/cpp/printerror.cpp
+@am__fastdepCXX_FALSE@	$(LIBTOOL) --tag=CXX $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libsciparse_la_CXXFLAGS) $(CXXFLAGS) -c -o libsciparse_la-printerror.lo `test -f 'src/cpp/printerror.cpp' || echo '$(srcdir)/'`src/cpp/printerror.cpp
 
 mostlyclean-libtool:
 	-rm -f *.lo
