Use functions and some tabulation added

diff --git a/scilab/bin/scilab b/scilab/bin/scilab
--- a/scilab/bin/scilab
+++ b/scilab/bin/scilab
@@ -1,16 +1,19 @@
 #!/bin/sh
-
-# Copyright INRIA
-# Updated : Sylvestre Ledru 2006/2007/2008
-# Updated : Simon Lipp 2008  - clean up (get rid of unnecessary sci_args)
+#
+# Scilab ( http://www.scilab.org/ ) - This file is part of Scilab
+# Copyright (C) INRIA - 2006-2008 - Sylvestre Ledru
+# Copyright (C) INRIA - 2008 - Simon Lipp
+# Copyright (C) DIGITEO - 2009 - Sylvestre Ledru
+# This file must be used under the terms of the CeCILL.
+# This source file is licensed as described in the file COPYING, which
+# you should have received as part of this distribution.  The terms
+# are also available at    
+# http://www.cecill.info/licences/Licence_CeCILL_V2-en.txt
+#
+# Simon Lipp 2008:
+# - clean up (get rid of unnecessary sci_args)
 #                            - accept arguments with spaces, e.g.
 #                               -e "disp(1); disp(2)" (fix bug #2606)
-
-#############################################################################
-#                                                                           #
-#                       DO NOT MODIFY BELOW THIS LINE                       #
-#                                                                           #
-#############################################################################
 
 ####
 #
@@ -56,6 +59,7 @@ if test -n "$SCI"; then
 fi
 
 
+# Electric fence is a tool to check problem of memory
 start_electric_fence() {
 	echo "Running Scilab with Electric Fence : "  LD_PRELOAD=libefence.so.0.0 "$SCILABBIN" "$@"
 	LD_PRELOAD=libefence.so.0.0 "$SCILABBIN" "$@"
@@ -122,90 +126,93 @@ find_docbook_path() {
 }
 
 
-SCILABBIN="scilab-bin"
+detect_scilab_path() {
+	SCILABBIN="scilab-bin"
 
-OLDPWD=`pwd`
+	OLDPWD=`pwd`
 
 # Use scilab-bin in the current dir if it exists
 # If not, then start resolving symlinks until we find scilab-bin
-found=0
-progname="$0"
-curdir=`dirname "$progname"`
-PATH="$curdir:$PATH"
+	found=0
+	progname="$0"
+	curdir=`dirname "$progname"`
+	PATH="$curdir:$PATH"
 
-progbase=`basename "$progname"`
-run_sci="$curdir/$SCILABBIN"
-if test -x "$run_sci"; then # scilab-bin is in the /bin/ directory
-	cd "$curdir/../"
-	SCI=`pwd`
-	SCIBIN=$run_sci
-	found=1
-else
-	run_sci="$curdir/../$SCILABBIN"
-	if test -x "$run_sci"; then # scilab-bin is in the / directory
-		# which is the case in a dev env
+	progbase=`basename "$progname"`
+	run_sci="$curdir/$SCILABBIN"
+	if test -x "$run_sci"; then # scilab-bin is in the /bin/ directory
 		cd "$curdir/../"
 		SCI=`pwd`
 		SCIBIN=$run_sci
 		found=1
 	else
-		here=`/bin/pwd`
-		while test -h "$progname"; do
-			bn=`basename "$progname"`
-			cd `dirname "$progname"`
+		run_sci="$curdir/../$SCILABBIN"
+		if test -x "$run_sci"; then # scilab-bin is in the / directory
+		# which is the case in a dev env
+			cd "$curdir/../"
+			SCI=`pwd`
+			SCIBIN=$run_sci
+			found=1
+		else
+			here=`/bin/pwd`
+			while test -h "$progname"; do
+				bn=`basename "$progname"`
+				cd `dirname "$progname"`
 			# Browse the symlink to the real one
-			progname=`/bin/ls -l "$bn" | sed -e 's/^.* -> //' `
-			if test ! -x "$progname"; then
-				break
-			fi
-			curdir=`dirname "$progname"`
-			if test -x "$curdir"; then
-				cd "$curdir/../"
-				SCI=`pwd`
-				SCIBIN="$curdir/$SCILABBIN"
-				found=1
-				break
-			fi
-			# The current file ($0), probably scilab is a symlink to the real one and here, it is the dev env
-			run_sci="$curdir/../$SCILABBIN"
-			if test -x "$run_sci"; then
-				cd "$curdir/../"
-				SCI=`pwd`
-				SCIBIN=$run_sci
-				found=1
-				break
-			fi
-		done
-		cd "$here"
+				progname=`/bin/ls -l "$bn" | sed -e 's/^.* -> //' `
+				if test ! -x "$progname"; then
+					break
+				fi
+				curdir=`dirname "$progname"`
+				if test -x "$curdir"; then
+					cd "$curdir/../"
+					SCI=`pwd`
+					SCIBIN="$curdir/$SCILABBIN"
+					found=1
+					break
+				fi
+			# The current file ($0), probably scilab is a symlink to the 
+			# real one and here, it is the dev env
+				run_sci="$curdir/../$SCILABBIN"
+				if test -x "$run_sci"; then
+					cd "$curdir/../"
+					SCI=`pwd`
+					SCIBIN=$run_sci
+					found=1
+					break
+				fi
+			done
+			cd "$here"
+		fi
+		if test $SCIVERBOSE -ne 0; then
+			echo "I think I found Scilab here : $SCI"
+		fi
 	fi
-	if test $SCIVERBOSE -ne 0; then
-		echo "I think I found Scilab here : $SCI"
-	fi
-fi
 
 
-if test -x "$SCI/bin/$SCILABBIN"; then
+	if test -x "$SCI/bin/$SCILABBIN"; then
 # real env
-	SCILABBIN=$SCI/bin/$SCILABBIN
-	SCI=$SCI/share/scilab/
-else
-	if test -x "$SCI/$SCILABBIN"; then
-		# dev env
-		SCILABBIN=$SCI/$SCILABBIN
-		DEVENV=1
-		# add modelica in the path
-		PATH="$PATH:$SCI/modules/scicos/"
+		SCILABBIN=$SCI/bin/$SCILABBIN
+		SCI=$SCI/share/scilab/
 	else
-		echo "Cannot find $SCILABBIN ..."
-		exit 1
+		if test -x "$SCI/$SCILABBIN"; then
+		# dev env
+			SCILABBIN=$SCI/$SCILABBIN
+			DEVENV=1
+		# add modelica in the path
+			PATH="$PATH:$SCI/modules/scicos/"
+		else
+			echo "Cannot find $SCILABBIN ..."
+			exit 1
+		fi
 	fi
-fi
 
-export SCI
-PATH="$SCI:$SCI/bin:$PATH"
+	export SCI
+}
 
+detect_java_vm() {
 ############# JAVA DETECTION ##############
-#�Basic inspiration from Eclipse
+# Basic inspiration from Eclipse
 #
 # Scilab is looking for Java in various places with different ways :
 # * if JAVA_HOME is specificed, use it
@@ -218,12 +225,12 @@ PATH="$SCI:$SCI/bin:$PATH"
 # 2 others) are available
 ###
 
-if test "${OS}" = ""; then
+	if test "${OS}" = ""; then
         OS=`uname -s` # Retrieve the Operating System                                                                                                         
-fi
-if test "${MODEL}" = ""; then
+	fi
+	if test "${MODEL}" = ""; then
         MODEL=`uname -m` # Retrieve the model                                                                                                                 
-fi
+	fi
 
 # Get the proc name matching to the one of the JVM
 # Inspiration and data are from http://www.google.com/codesearch?hl=en&q=+java+ppc+libjava.so+show:a78sz0SP41k:zxNozD-vc0A:FWiIy7Hinmg&sa=N&cd=2&ct=rc&cs_p=http://fresh.t-systems-sfr.com/unix/src/misc/tclBlendSrc1.2.5.tar.gz&cs_f=tclBlend1.2.5/configure.in#a0
@@ -232,177 +239,184 @@ fi
 # uname -m Darwin
 
 # If the user has the variable JAVA_HOME in the ENV
-if test -n "$JAVA_HOME" ; then
-	if test $SCIVERBOSE -ne 0; then
-		echo "Using specified vm: $JAVA_HOME"
+	if test -n "$JAVA_HOME" ; then
+		if test $SCIVERBOSE -ne 0; then
+			echo "Using specified vm: $JAVA_HOME"
+		fi
+		if test ! -x "$JAVA_HOME/bin/java" ; then
+			echo "Cannot find $JAVA_HOME/bin/java"
+			exit 1
+		fi
 	fi
-    if test ! -x "$JAVA_HOME/bin/java" ; then
-		echo "Cannot find $JAVA_HOME/bin/java"
-        exit 1
-    fi
-fi
 
-if test -z "$JAVA_HOME"; then
-            case $OS in
-                *darwin* | *Darwin*)
+	if test -z "$JAVA_HOME"; then
+        case $OS in
+            *darwin* | *Darwin*)
                     # Seems to be always that under Mac OS X. Don't hesitate to submit a bug report if it is not the case.
-					JAVA_HOME="/System/Library/Frameworks/JavaVM.framework/Home/"
-                    LD_LIBRARY_PATH="/System/Library/Frameworks/JavaVM.framework/Libraries:$LD_LIBRARY_PATH"
-					if test $SCIVERBOSE -ne 0; then
-						echo "Using default Mac OS X vm: $JAVA_HOME"
-						echo "And LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
-					fi
-					;;
-                *)
-					;;
-			esac
-fi
+				JAVA_HOME="/System/Library/Frameworks/JavaVM.framework/Home/"
+                LD_LIBRARY_PATH="/System/Library/Frameworks/JavaVM.framework/Libraries:$LD_LIBRARY_PATH"
+				if test $SCIVERBOSE -ne 0; then
+					echo "Using default Mac OS X vm: $JAVA_HOME"
+					echo "And LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
+				fi
+				;;
+            *)
+				;;
+		esac
+	fi
 
 # Browse "default directory" (if it means anything under Unix/Linux) of Java
 # to find where it could be !
-if test -z "$JAVA_HOME"; then
-	JAVA_DEFAULT_DIR="/usr/lib/jvm/java-6-openjdk/ /usr/lib/jvm/java/ /usr/lib/jvm/java-6-sun/ /usr/lib/j2se/1.6 /usr/java/jdk1.6.0*/ /usr/java/jdk1.5.0*/ /usr/lib/j2sdk1.6-ibm /usr/lib/jvm/java-1.5.0-sun /usr/java/ /usr/lib/j2se/1.5 /usr/lib/j2se/1.4 /usr/java/jre1.6.0*/ /usr/java/jre1.5.0*/ /usr/lib/j2sdk1.5-ibm /usr/lib/j2sdk1.4-ibm /usr/lib/j2sdk1.5-sun /usr/lib/j2sdk1.4-sun /usr/lib/jvm/java-gcj /usr/lib/jvm/java-1.5.0-gcj/ /usr/lib/kaffe/pthreads /usr/lib/jvm/java-1.7.0-icedtea-*/ /usr/lib/jvm/jre/"
-    for JAVA_HOME in $JAVA_DEFAULT_DIR ; do
-		if test $SCIVERBOSE -ne 0; then
-			echo "Trying to find Java in $JAVA_HOME "
-		fi
-		if test -x "${JAVA_HOME}/bin/java" ; then
-            export JAVA_HOME
+	if test -z "$JAVA_HOME"; then
+		JAVA_DEFAULT_DIR="/usr/lib/jvm/java-6-openjdk/ /usr/lib/jvm/java/ /usr/lib/jvm/java-6-sun/ /usr/lib/j2se/1.6 /usr/java/jdk1.6.0*/ /usr/java/jdk1.5.0*/ /usr/lib/j2sdk1.6-ibm /usr/lib/jvm/java-1.5.0-sun /usr/java/ /usr/lib/j2se/1.5 /usr/lib/j2se/1.4 /usr/java/jre1.6.0*/ /usr/java/jre1.5.0*/ /usr/lib/j2sdk1.5-ibm /usr/lib/j2sdk1.4-ibm /usr/lib/j2sdk1.5-sun /usr/lib/j2sdk1.4-sun /usr/lib/jvm/java-gcj /usr/lib/jvm/java-1.5.0-gcj/ /usr/lib/kaffe/pthreads /usr/lib/jvm/java-1.7.0-icedtea-*/ /usr/lib/jvm/jre/"
+		for JAVA_HOME in $JAVA_DEFAULT_DIR ; do
 			if test $SCIVERBOSE -ne 0; then
-				echo "found"
+				echo "Trying to find Java in $JAVA_HOME "
 			fi
-            break
-        fi
-	done
-fi
+			if test -x "${JAVA_HOME}/bin/java" ; then
+				export JAVA_HOME
+				if test $SCIVERBOSE -ne 0; then
+					echo "found"
+				fi
+				break
+			fi
+		done
+	fi
 
 # JAVA_HOME still haven't been found. Well, we can now try to find it in the path
 
-if test -z "$JAVA_HOME"; then
-    PATH_SEPARATOR=:
-	as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-	if test $SCIVERBOSE -ne 0; then
-		echo "Look the binary java in the PATH. If it is a symlink, try to resolve it"
-	fi
-	for DIR in $PATH; do
-		if test -f $DIR/java; then
+	if test -z "$JAVA_HOME"; then
+		PATH_SEPARATOR=:
+		as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+		if test $SCIVERBOSE -ne 0; then
+			echo "Look the binary java in the PATH. If it is a symlink, try to resolve it"
+		fi
+		for DIR in $PATH; do
+			if test -f $DIR/java; then
 
-			_cur=$DIR/java
+				_cur=$DIR/java
 			# resolve symlink
 			# Will probably bug if a file contains -> in the name
-			while ls -ld "$_cur" 2>/dev/null | grep " -> " >/dev/null; do
-				_cur=`ls -ld "$_cur" | sed 's/.* -> //'`
-			done
+				while ls -ld "$_cur" 2>/dev/null | grep " -> " >/dev/null; do
+					_cur=`ls -ld "$_cur" | sed 's/.* -> //'`
+				done
 			# symlink resolved to the real file
 
 			# Now, create JAVA_HOME
-			TMP=`dirname $_cur`
-			JAVA_HOME=`dirname $TMP`
-			if test ! -z "$JAVA_HOME"; then
-				break;
+				TMP=`dirname $_cur`
+				JAVA_HOME=`dirname $TMP`
+				if test ! -z "$JAVA_HOME"; then
+					break;
+				fi
 			fi
-		fi
-	done
-	IFS=$as_save_IFS
-fi
-if test ! -z "$JAVA_HOME"; then
-	if test $SCIVERBOSE -ne 0; then
-		echo "JAVA_HOME : $JAVA_HOME"
+		done
+		IFS=$as_save_IFS
 	fi
+	if test ! -z "$JAVA_HOME"; then
+		if test $SCIVERBOSE -ne 0; then
+			echo "JAVA_HOME : $JAVA_HOME"
+		fi
 
 # Manage JRE & JDK because libjava.so and others are stored in the JRE
-	if test -d $JAVA_HOME/jre; then
-		JRE_HOME=$JAVA_HOME/jre
-	else
-		JRE_HOME=$JAVA_HOME
-	fi
+		if test -d $JAVA_HOME/jre; then
+			JRE_HOME=$JAVA_HOME/jre
+		else
+			JRE_HOME=$JAVA_HOME
+		fi
 
 # Configuring LD_LIBRARY_PATH for libjava.so libhpi.so and libxxxx.so
 
-JAVA_SHLIB="libjava.so"
+		JAVA_SHLIB="libjava.so"
 
-case $OS in
-	"Linux")
-		case $MODEL in
-			"x86_64")
-				proc="amd64"
-				;;
-			i?86)
+		case $OS in
+			"Linux")
+				case $MODEL in
+					"x86_64")
+						proc="amd64"
+						;;
+					i?86)
 
-				if test -d ${JRE_HOME}/lib/`uname -m` ; then
-					proc=`uname -m`
-				else
-					proc="i386"
-				fi
+						if test -d ${JRE_HOME}/lib/`uname -m` ; then
+							proc=`uname -m`
+						else
+							proc="i386"
+						fi
+						;;
+					"ia64")
+						proc="i64"
+						;;
+					"ppc")
+						proc="ppc"
+						;;
+					"alpha")  
+						proc="alpha"
+						;;
+					*)
+						echo "Could not find the Java configuration for the model <${MODEL}>. Please contact us."
+						;;
+				esac
 				;;
-			"ia64")
-				proc="i64"
+			"HP-UX")
+				JAVA_SHLIB="libjava.sl"
+				proc="lib" # TODO : check if it is right or not ... seems not !
 				;;
-		    "ppc")
-				proc="ppc"
+			"IRIX")
+				proc="lib32"
 				;;
-			"alpha")  
-				proc="alpha"
-				;;
-			*)
-				echo "Could not find the Java configuration for the model <${MODEL}>. Please contact us."
-				;;
-			esac
-		;;
-	"HP-UX")
-		JAVA_SHLIB="libjava.sl"
-		proc="lib" # TODO : check if it is right or not ... seems not !
-		;;
-	"IRIX")
-		proc="lib32"
-		;;
-    "SunOS")
-    		case $MODEL in
-			"i86pc") # solaris x86
-				proc="i386"
-				;;
+			"SunOS")
+    			case $MODEL in
+					"i86pc") # solaris x86
+						proc="i386"
+						;;
 				# check for the 64 bits syntax
-			"sparc")
-				proc="sparc"
+					"sparc")
+						proc="sparc"
+						;;
+					*)
+						echo "Could not find the Java configuration for the model <${MODEL}>. Please contact us."
+						;;
+				esac
 				;;
-			*)
-				echo "Could not find the Java configuration for the model <${MODEL}>. Please contact us."
+			*win32* | *WIN32* | *CYGWIN_NT*)
+				proc="win32"
+				JAVA_SHLIB="jvm.dll"
 				;;
-			esac
-		;;
-	*win32* | *WIN32* | *CYGWIN_NT*)
-		proc="win32"
-		JAVA_SHLIB="jvm.dll"
-		;;
-    *darwin* | *Darwin*) # MacOS X
+			*darwin* | *Darwin*) # MacOS X
 	# For Mac OS X, Since path are different from the JVM normal tree, don't need to detect 
 	# the CPU
-	;;
-	*)
-		echo "Could not find the Java configuration for the OS <${OS}>. Please contact us."
-		;;
-esac
+				;;
+			*)
+				echo "Could not find the Java configuration for the OS <${OS}>. Please contact us."
+				;;
+		esac
 
 # Check if the lib exists or not (we should manage system where .so is not the
 # ext for library
-	LIBJAVA="$JRE_HOME/lib/$proc/$JAVA_SHLIB"
-	if test ! -f $LIBJAVA; then
-		if test $SCIVERBOSE -ne 0; then
-			echo "Cannot find $LIBJAVA"
-		fi
-	else
+		LIBJAVA="$JRE_HOME/lib/$proc/$JAVA_SHLIB"
+		if test ! -f $LIBJAVA; then
+			if test $SCIVERBOSE -ne 0; then
+				echo "Cannot find $LIBJAVA"
+			fi
+		else
             CLASSPATH="$CLASSPATH:$SCI/modules/jvm/jar/org.scilab.modules.jvm.jar"
 		# @TODO This is the default path of the official sun JVM. 
 		# It is different for other implementation of the JVM....
 		    LD_LIBRARY_PATH="$JRE_HOME/lib/$proc/:$JRE_HOME/lib/$proc/server/:$JRE_HOME/lib/$proc/native_threads/:$LD_LIBRARY_PATH"
+		fi
+	else
+		if test $SCIVERBOSE -ne 0; then
+			echo "Have not been able to find any Java VM on this computer. Some features may be broken."
+		fi
 	fi
-else
-	if test $SCIVERBOSE -ne 0; then
-		echo "Have not been able to find any Java VM on this computer. Some features may be broken."
-	fi
-fi
 
 ####### END OF JAVA ENV DETECTION/SETTING ######
+}
+
+detect_scilab_path
+
+PATH="$SCI:$SCI/bin:$PATH"
+
+detect_java_vm
 
 # See http://bugzilla.scilab.org/show_bug.cgi?id=3486
 # Some Java stuff raises spurious SIGSEGV. The problem is that when bug-buddy
