Fix indentation in scilab shell script.
Change-Id: I23347fa13e7f77d04ea6abae5672729df54c00ae

diff --git a/scilab/bin/scilab b/scilab/bin/scilab
--- a/scilab/bin/scilab
+++ b/scilab/bin/scilab
@@ -393,81 +393,81 @@ detect_java_vm() {
 # uname -m Darwin
 
 # If the user has the variable JAVA_HOME in the ENV
-    if test -n "$JAVA_HOME" ; then
-            if test $SCIVERBOSE -ne 0; then
-                echo "Using specified vm: $JAVA_HOME"
-            fi
-            if test ! -x "$JAVA_HOME/bin/java" ; then
-                echo "Cannot find $JAVA_HOME/bin/java"
-                exit 1
-            fi
+        if test -n "$JAVA_HOME" ; then
+                if test $SCIVERBOSE -ne 0; then
+                    echo "Using specified vm: $JAVA_HOME"
+                fi
+                if test ! -x "$JAVA_HOME/bin/java" ; then
+                    echo "Cannot find $JAVA_HOME/bin/java"
+                    exit 1
+                fi
         else
 
-        case $OS in
-            *darwin* | *Darwin*)
-                set_macosx_java_vm
-                if test $SCIVERBOSE -ne 0; then
-                    echo "Using default Mac OS X vm: $JAVA_HOME"
-                    echo "And LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
-                    echo "And DYLD_LIBRARY_PATH: $DYLD_LIBRARY_PATH"
-                fi
-                ;;
-            *)
-                ;;
-        esac
+            case $OS in
+                *darwin* | *Darwin*)
+                    set_macosx_java_vm
+                    if test $SCIVERBOSE -ne 0; then
+                        echo "Using default Mac OS X vm: $JAVA_HOME"
+                        echo "And LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
+                        echo "And DYLD_LIBRARY_PATH: $DYLD_LIBRARY_PATH"
+                    fi
+                    ;;
+                *)
+                    ;;
+            esac
 
 # Browse "default directory" (if it means anything under Unix/Linux) of Java
 # to find where it could be !
-        if test -z "$JAVA_HOME"; then
-            JAVA_DEFAULT_DIR="/usr/lib/jvm/default-java /usr/lib/jvm/java-6-openjdk/ /usr/lib/jvm/java-7-openjdk/ /usr/lib/jvm/java/ /usr/lib/jvm/java-6-sun/ /usr/lib/j2se/1.6 /usr/java/jdk1.6.0*/ /usr/java/jdk1.5.0*/ /usr/lib/j2sdk1.6-ibm /usr/lib/jvm/java-1.5.0-sun /usr/java/ /usr/lib/j2se/1.5 /usr/lib/j2se/1.4 /usr/java/jre1.6.0*/ /usr/java/jre1.5.0*/ /usr/lib/j2sdk1.5-ibm /usr/lib/j2sdk1.4-ibm /usr/lib/j2sdk1.5-sun /usr/lib/j2sdk1.4-sun /usr/lib/jvm/java-gcj /usr/lib/jvm/java-1.5.0-gcj/ /usr/lib/kaffe/pthreads /usr/lib/jvm/java-1.7.0-icedtea-*/ /usr/lib/jvm/jre/ /usr/local/diablo-jdk1.6.0/"
-            for JAVA_HOME in $JAVA_DEFAULT_DIR ; do
-                if test $SCIVERBOSE -ne 0; then
-                    echo "Trying to find Java in $JAVA_HOME "
-                fi
-                if test -x "${JAVA_HOME}/bin/java" ; then
-                    export JAVA_HOME
+            if test -z "$JAVA_HOME"; then
+                JAVA_DEFAULT_DIR="/usr/lib/jvm/default-java /usr/lib/jvm/java-6-openjdk/ /usr/lib/jvm/java-7-openjdk/ /usr/lib/jvm/java/ /usr/lib/jvm/java-6-sun/ /usr/lib/j2se/1.6 /usr/java/jdk1.6.0*/ /usr/java/jdk1.5.0*/ /usr/lib/j2sdk1.6-ibm /usr/lib/jvm/java-1.5.0-sun /usr/java/ /usr/lib/j2se/1.5 /usr/lib/j2se/1.4 /usr/java/jre1.6.0*/ /usr/java/jre1.5.0*/ /usr/lib/j2sdk1.5-ibm /usr/lib/j2sdk1.4-ibm /usr/lib/j2sdk1.5-sun /usr/lib/j2sdk1.4-sun /usr/lib/jvm/java-gcj /usr/lib/jvm/java-1.5.0-gcj/ /usr/lib/kaffe/pthreads /usr/lib/jvm/java-1.7.0-icedtea-*/ /usr/lib/jvm/jre/ /usr/local/diablo-jdk1.6.0/"
+                for JAVA_HOME in $JAVA_DEFAULT_DIR ; do
                     if test $SCIVERBOSE -ne 0; then
-                        echo "found"
+                        echo "Trying to find Java in $JAVA_HOME "
                     fi
-                    break
-                fi
-            done
-        fi
+                    if test -x "${JAVA_HOME}/bin/java" ; then
+                        export JAVA_HOME
+                        if test $SCIVERBOSE -ne 0; then
+                            echo "found"
+                        fi
+                        break
+                    fi
+                done
+            fi
 
 # JAVA_HOME still haven't been found. Well, we can now try to find it in the path
-        if test ! -d "$JAVA_HOME" -o ! -h "$JAVA_HOME"; then
-            if test $SCIVERBOSE -ne 0; then
-                echo "Have not been able to find any Java VM on this computer. Some features may be broken."
-            fi
-        else
-
-            PATH_SEPARATOR=:
-            as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-            if test $SCIVERBOSE -ne 0; then
-                echo "Look the binary java in the PATH. If it is a symlink, try to resolve it"
-            fi
-            for DIR in $PATH; do
-                if test -f $DIR/java; then
-
-                    _cur=$DIR/java
-            # resolve symlink
-            # Will probably bug if a file contains -> in the name
-                    while ls -ld "$_cur" 2>/dev/null | grep " -> " >/dev/null; do
-                        _cur=$(ls -ld "$_cur" | sed 's/.* -> //')
-                    done
-            # symlink resolved to the real file
-
-            # Now, create JAVA_HOME
-                    TMP=$(dirname $_cur)
-                    JAVA_HOME=$(dirname $TMP)
-                    if test ! -z "$JAVA_HOME"; then
-                        break;
-                    fi
+            if test ! -d "$JAVA_HOME" -o ! -h "$JAVA_HOME"; then
+                if test $SCIVERBOSE -ne 0; then
+                    echo "Have not been able to find any Java VM on this computer. Some features may be broken."
                 fi
-            done
-            IFS=$as_save_IFS
+            else
+
+                PATH_SEPARATOR=:
+                as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+                if test $SCIVERBOSE -ne 0; then
+                    echo "Look the binary java in the PATH. If it is a symlink, try to resolve it"
+                fi
+                for DIR in $PATH; do
+                    if test -f $DIR/java; then
+
+                        _cur=$DIR/java
+                # resolve symlink
+                # Will probably bug if a file contains -> in the name
+                        while ls -ld "$_cur" 2>/dev/null | grep " -> " >/dev/null; do
+                            _cur=$(ls -ld "$_cur" | sed 's/.* -> //')
+                        done
+                # symlink resolved to the real file
+
+                # Now, create JAVA_HOME
+                        TMP=$(dirname $_cur)
+                        JAVA_HOME=$(dirname $TMP)
+                        if test ! -z "$JAVA_HOME"; then
+                            break;
+                        fi
+                    fi
+                done
+                IFS=$as_save_IFS
+            fi
         fi
-    fi
         if test ! -z "$JAVA_HOME"; then
             if test $SCIVERBOSE -ne 0; then
                 echo "JAVA_HOME : $JAVA_HOME"
