* bug 6945 fixed - Conflicting options were confusing Scilab argument processing                    (example: scilab-cli with the -nw option)
Change-Id: I74a552373f76716d1b8e650ebe9d963c001d1d0f

diff --git a/scilab/bin/scilab b/scilab/bin/scilab
--- a/scilab/bin/scilab
+++ b/scilab/bin/scilab
@@ -805,7 +805,19 @@ if test "$rest" = "yes"; then
         fi
 
         case $sciarg in
-            -nogui|-version|-ns|-nb|-nw|-nouserstartup|--texmacs|-nwni)
+            -nogui|-version|-ns|-nb|-nouserstartup|--texmacs)
+                ;;
+            -nw)
+                if test "$SCILAB_MODE" = "nwni"; then
+                    echo "Cannot use scilab-cli with option -nw"
+                    exit 5
+                fi
+                ;;
+            -nwni)
+                if test "$SCILAB_MODE" = "nw"; then
+                    echo "Cannot use scilab-adv-cli with option -nwni"
+                    exit 5
+                fi
                 ;;
             -psn_*)
         # Under Mac OS X, .app is adding the arg -psn_0_xxxx
