Try to fix the 10.7 issue + uncomment the 10.5 section
Change-Id: I29c6fb59780663dda4d2a07b27b4dddd1f0d8238

diff --git a/scilab/bin/scilab b/scilab/bin/scilab
--- a/scilab/bin/scilab
+++ b/scilab/bin/scilab
@@ -649,23 +649,24 @@ check_macosx_version()
                    # We force to install JRE on Lion
                    /usr/libexec/java_home --request
 
-                   # We remove if it exists with 10.7
-                   rm -rf $BINPATH/../lib/thirdparty/libiconv.2.4.0.dylib
                    ;;
 
                 6)
+		    # the iconv lib fails under 10.7, just declare it for 10.5 & 10.6
+		    LD_LIBRARY_PATH=$BINPATH/../lib/thirdparty/10.6/${LD_LIBRARY_PATH+:$LD_LIBRARY_PATH}
                     if test $macosxBuildVersion -le 4; then
                         # Version <= 10.6.4
                         osascript $BINPATH/checkmacosx.applescript $macosxVersion "10.6.5 (Snow Leopard) or newer system" || exit 128
                     fi
                     ;;
-# Does not work under 10.5 binary for now. Fail by default
-#                 5)
-#                     if test $macosxBuildVersion -ge 8; then
-#                         # Version <= 10.5.8
-#                         osascript $BINPATH/checkmacosx.applescript $macosxVersion "10.5.8 (Leopard) or newer system" || exit 128
-#                         fi
-#                    ;;
+                 5)
+                    # the iconv lib fails under 10.7, just declare it for 10.5 & 10.6
+		     LD_LIBRARY_PATH=$BINPATH/../lib/thirdparty/10.6/${LD_LIBRARY_PATH+:$LD_LIBRARY_PATH}
+                     if test $macosxBuildVersion -ge 8; then
+                         # Version <= 10.5.8
+                         osascript $BINPATH/checkmacosx.applescript $macosxVersion "10.5.8 (Leopard) or newer system" || exit 128
+                         fi
+                    ;;
                 *)
                     osascript $BINPATH/checkmacosx.applescript $macosxVersion "10.6.5 (Snow Leopard) or newer system" || exit 128
                     ;;
@@ -881,8 +882,8 @@ if test "$rest" = "yes"; then
                 fi
                 ;;
             -psn_*)
-        # Under Mac OS X, .app is adding the arg -psn_0_xxxx
-        # (psn = ProcessSerialNumber). It is not used (but could be in the future)
+	        # Under Mac OS X, .app is adding the arg -psn_0_xxxx
+        	# (psn = ProcessSerialNumber). It is not used (but could be in the future)
                 ;;
             -display|-f|-l|-e|-d|-mem)
                 prevarg=1
