Check for a more recent version of jeuclid

diff --git a/scilab/configure b/scilab/configure
--- a/scilab/configure
+++ b/scilab/configure
@@ -26032,13 +26032,13 @@ echo "$as_me: error: Could not find the Docbook root directory. If you have inst
 	fi
 	# xml.apache.org SVG Library
 
-	{ echo "$as_me:$LINENO: checking batik" >&5
-echo $ECHO_N "checking batik... $ECHO_C" >&6; }
+	{ echo "$as_me:$LINENO: checking batik-all" >&5
+echo $ECHO_N "checking batik-all... $ECHO_C" >&6; }
 	found_jar=no
 	saved_ac_java_classpath=$ac_java_classpath
 	DEFAULT_JAR_DIR="/usr/share/java/ /usr/lib/java/ /usr/share/java /usr/share/java/jar /opt/java/lib /usr/local/java /usr/local/java/jar /usr/local/share/java /usr/local/share/java/jar /usr/local/lib/java"
     for jardir in "`pwd`/thirdparty" "`pwd`/jar" $DEFAULT_JAR_DIR "$_user_libdir"; do
-      for jar in "$jardir/batik.jar" "$jardir/libbatik.jar" "$jardir/libbatik-java.jar" "$jardir/batik*.jar"; do
+      for jar in "$jardir/batik-all.jar" "$jardir/libbatik-all.jar" "$jardir/libbatik-all-java.jar" "$jardir/batik-all*.jar"; do
 #	jar=`echo $jar|sed -e 's/ /\\ /'`
 #	echo "protected $jar"
 #	jar_resolved=`ls $jar 2>/dev/null`
@@ -26090,8 +26090,8 @@ echo "${ECHO_T}$jar_resolved" >&6; }
     if test "$found_jar" = "no"; then
       { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
-	{ { echo "$as_me:$LINENO: error: Could not find or use the Java package/jar batik used by Apache SVG Library (looking for package org.apache.batik.parser.Parser)" >&5
-echo "$as_me: error: Could not find or use the Java package/jar batik used by Apache SVG Library (looking for package org.apache.batik.parser.Parser)" >&2;}
+	{ { echo "$as_me:$LINENO: error: Could not find or use the Java package/jar batik-all used by Apache SVG Library (looking for package org.apache.batik.parser.Parser)" >&5
+echo "$as_me: error: Could not find or use the Java package/jar batik-all used by Apache SVG Library (looking for package org.apache.batik.parser.Parser)" >&2;}
    { (exit 1); exit 1; }; }
     fi
 
@@ -26254,7 +26254,7 @@ echo $ECHO_N "checking jeuclid-core... $ECHO_C" >&6; }
 
     cat << \EOF > conftest.java
 // #line 26256 "configure"
-import net.sourceforge.jeuclid.DOMBuilder;
+import net.sourceforge.jeuclid.ant.MathMLConverter;
 
 public class conftest {
     public static void main(String[] argv) {
@@ -26294,8 +26294,8 @@ echo "${ECHO_T}$jar_resolved" >&6; }
     if test "$found_jar" = "no"; then
       { echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
-	{ { echo "$as_me:$LINENO: error: Could not find or use the Java package/jar jeuclid-core used by MathML rendering solution (looking for package net.sourceforge.jeuclid.DOMBuilder)" >&5
-echo "$as_me: error: Could not find or use the Java package/jar jeuclid-core used by MathML rendering solution (looking for package net.sourceforge.jeuclid.DOMBuilder)" >&2;}
+	{ { echo "$as_me:$LINENO: error: Could not find or use the Java package/jar jeuclid-core used by MathML rendering solution (at least version 3.1.X) (looking for package net.sourceforge.jeuclid.ant.MathMLConverter)" >&5
+echo "$as_me: error: Could not find or use the Java package/jar jeuclid-core used by MathML rendering solution (at least version 3.1.X) (looking for package net.sourceforge.jeuclid.ant.MathMLConverter)" >&2;}
    { (exit 1); exit 1; }; }
     fi
 
