wrong symbol check

diff --git a/scilab/configure b/scilab/configure
--- a/scilab/configure
+++ b/scilab/configure
@@ -7719,25 +7719,11 @@ fi
 
 
 
-#
-# Evaluate shell variable equivalents to Makefile directory variables
-#
-#if test "x$prefix" = xNONE
-#then
-#  prefix=$ac_default_prefix
-#fi
-# Let make expand exec_prefix.
-#if test "x$exec_prefix" = xNONE
-#then
-#  exec_prefix='${prefix}'
-#fi
 
-#
-#eval "eval PREFIX_DIR=${prefix}"
-#eval "eval EXEC_PREFIX_DIR=${exec_prefix}"
 
-# default prefix
-ac_default_prefix=/usr/local/
+if test "x${prefix}" = "xNONE"; then
+  prefix="${ac_default_prefix}"
+fi
 
 ###############################
 ## creating Path.incl if needed
@@ -10104,7 +10090,7 @@ echo "${ECHO_T}$ac_java_classpath" >&6; }
 echo $ECHO_N "checking to see if the java compiler works... $ECHO_C" >&6; }
 
     cat << \EOF > conftest.java
-// #line 10107 "configure"
+// #line 10093 "configure"
 
 
 public class conftest {
@@ -10154,7 +10140,7 @@ echo $ECHO_N "checking type of jvm... $ECHO_C" >&6; }
     if test "x$ac_java_jvm_name" = "x" ; then
 
     cat << \EOF > conftest.java
-// #line 10157 "configure"
+// #line 10143 "configure"
 import gnu.java.io.EncodingManager;
 
 public class conftest {
@@ -10202,7 +10188,7 @@ echo $ECHO_N "checking java API version... $ECHO_C" >&6; }
 
 
     cat << \EOF > conftest.java
-// #line 10205 "configure"
+// #line 10191 "configure"
 import java.nio.charset.Charset;
 
 public class conftest {
@@ -10229,7 +10215,7 @@ EOF
 
 
     cat << \EOF > conftest.java
-// #line 10232 "configure"
+// #line 10218 "configure"
 import java.lang.StringBuilder;
 
 public class conftest {
@@ -15592,9 +15578,9 @@ fi
 
 
 
-{ echo "$as_me:$LINENO: checking for pcreposix_regexec in -lpcreposix" >&5
-echo $ECHO_N "checking for pcreposix_regexec in -lpcreposix... $ECHO_C" >&6; }
-if test "${ac_cv_lib_pcreposix_pcreposix_regexec+set}" = set; then
+{ echo "$as_me:$LINENO: checking for regexec in -lpcreposix" >&5
+echo $ECHO_N "checking for regexec in -lpcreposix... $ECHO_C" >&6; }
+if test "${ac_cv_lib_pcreposix_regexec+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
@@ -15612,11 +15598,11 @@ cat >>conftest.$ac_ext <<_ACEOF
 #ifdef __cplusplus
 extern "C"
 #endif
-char pcreposix_regexec ();
+char regexec ();
 int
 main ()
 {
-return pcreposix_regexec ();
+return regexec ();
   ;
   return 0;
 }
@@ -15639,21 +15625,21 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_pcreposix_pcreposix_regexec=yes
+  ac_cv_lib_pcreposix_regexec=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-	ac_cv_lib_pcreposix_pcreposix_regexec=no
+	ac_cv_lib_pcreposix_regexec=no
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_pcreposix_pcreposix_regexec" >&5
-echo "${ECHO_T}$ac_cv_lib_pcreposix_pcreposix_regexec" >&6; }
-if test $ac_cv_lib_pcreposix_pcreposix_regexec = yes; then
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_pcreposix_regexec" >&5
+echo "${ECHO_T}$ac_cv_lib_pcreposix_regexec" >&6; }
+if test $ac_cv_lib_pcreposix_regexec = yes; then
   cat >>confdefs.h <<_ACEOF
 #define HAVE_LIBPCREPOSIX 1
 _ACEOF
@@ -15661,8 +15647,8 @@ _ACEOF
   LIBS="-lpcreposix $LIBS"
 
 else
-  { { echo "$as_me:$LINENO: error: pcre : library missing. (Cannot find symbol pcre_compile). Check if pcre is installed and if the version is correct" >&5
-echo "$as_me: error: pcre : library missing. (Cannot find symbol pcre_compile). Check if pcre is installed and if the version is correct" >&2;}
+  { { echo "$as_me:$LINENO: error: pcreposix : library missing. (Cannot find symbol regexec). Check if pcre is installed and if the version is correct" >&5
+echo "$as_me: error: pcreposix : library missing. (Cannot find symbol regexec). Check if pcre is installed and if the version is correct" >&2;}
    { (exit 1); exit 1; }; }
 
 fi
@@ -15978,7 +15964,7 @@ CPPFLAGS="$CPPFLAGS -I$CHK_TCL_INCLUDE_PATH"
 { echo "$as_me:$LINENO: checking if tcl is version $CHK_TCL_MAJOR.$CHK_TCL_MINOR or later" >&5
 echo $ECHO_N "checking if tcl is version $CHK_TCL_MAJOR.$CHK_TCL_MINOR or later... $ECHO_C" >&6; }
 cat > conftest.$ac_ext <<EOF
-#line 15981 "configure"
+#line 15967 "configure"
 #include "confdefs.h"
 
 #include "$CHK_TCL_INCLUDE_PATH/$CHK_TCL_INC_NAME"
@@ -16339,7 +16325,7 @@ CPPFLAGS="$CPPFLAGS $TCL_INC_PATH -I$CHK_TK_INCLUDE_PATH $X_CFLAGS"
 echo $ECHO_N "checking if tk is version $CHK_TK_MAJOR.$CHK_TK_MINOR or later... $ECHO_C" >&6; }
 
 cat > conftest.$ac_ext <<EOF
-#line 16342 "configure"
+#line 16328 "configure"
 #include "confdefs.h"
 
 #include "$CHK_TK_INCLUDE_PATH/$CHK_TK_INC_NAME"
@@ -17881,13 +17867,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:17884: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:17870: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:17887: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:17873: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:17890: output\"" >&5)
+  (eval echo "\"\$as_me:17876: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -18973,7 +18959,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 18976 "configure"' > conftest.$ac_ext
+  echo '#line 18962 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -20567,11 +20553,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:20570: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20556: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:20574: \$? = $ac_status" >&5
+   echo "$as_me:20560: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -20889,11 +20875,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:20892: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20878: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:20896: \$? = $ac_status" >&5
+   echo "$as_me:20882: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -20994,11 +20980,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:20997: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20983: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:21001: \$? = $ac_status" >&5
+   echo "$as_me:20987: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -21049,11 +21035,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:21052: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:21038: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:21056: \$? = $ac_status" >&5
+   echo "$as_me:21042: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -23798,7 +23784,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 23801 "configure"
+#line 23787 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -23898,7 +23884,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 23901 "configure"
+#line 23887 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -25920,11 +25906,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:25923: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:25909: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:25927: \$? = $ac_status" >&5
+   echo "$as_me:25913: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -26019,11 +26005,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:26022: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:26008: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:26026: \$? = $ac_status" >&5
+   echo "$as_me:26012: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -26071,11 +26057,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:26074: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:26060: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:26078: \$? = $ac_status" >&5
+   echo "$as_me:26064: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -27446,11 +27432,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:27449: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:27435: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:27453: \$? = $ac_status" >&5
+   echo "$as_me:27439: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -27545,11 +27531,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:27548: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:27534: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:27552: \$? = $ac_status" >&5
+   echo "$as_me:27538: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -27597,11 +27583,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:27600: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:27586: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:27604: \$? = $ac_status" >&5
+   echo "$as_me:27590: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -32787,8 +32773,8 @@ echo ""
 
 echo ""
 echo "Options used to compile and link:"
-echo "  PREFIX           = $PREFIX_DIR"
-echo "  EXEC-PREFIX      = $EXEC_PREFIX_DIR"
+echo "  PREFIX           = $prefix"
+echo "  DESTDIR          = $DESTDIR"
 echo "  VERSION          = $PACKAGE_VERSION"
 echo "  CC               = $CC"
 echo "  CFLAGS           = $CFLAGS"
