configure, configure.ac (64 bits):  * SSE/SSE2 can be dangerous  * add -fPIC  * tell the user to try --with-gfortran when autoconf choose g77

diff --git a/scilab/configure b/scilab/configure
--- a/scilab/configure
+++ b/scilab/configure
@@ -10291,7 +10291,7 @@ if test -n "$F77"; then
    fi
 	  case "$host" in
 		 x86_64-*-linux*)
-			FFLAGS="$FFLAGS -mfpmath=sse -msse2 -m64 -fPIC"
+			FFLAGS="$FFLAGS -m64 -fPIC"
 					;;
 		# Dec Alpha OSF 4
 		alpha*-dec-osf4.*)
@@ -10437,7 +10437,7 @@ if test "$CC" = "gcc" -o "$CC" = "ccache gcc"; then
 	    CFLAGS="$CFLAGS -Dlinux -fwritable-strings"
 	;;
 	 x86_64-*-linux-gnu)
-		CFLAGS="$CFLAGS -Dlinux -DNARROWPROTO -mfpmath=sse -msse2 -m64"
+		CFLAGS="$CFLAGS -Dlinux -DNARROWPROTO -fPIC -m64"
 		IS_64_BITS_CPU=true
     ;;
 	 i*86-*-linux-gnu | *-pc-linux-gnu | i*86-*-linux )
@@ -10534,8 +10534,8 @@ FFLAGS="$FFLAGS "'-I$(top_srcdir)/modules/core/includes/'
 
 if test $IS_64_BITS_CPU = true; then
    if test $f90compatible = false; then
-      { { echo "$as_me:$LINENO: error: 64 bits support needs a fortran 90 compiler." >&5
-echo "$as_me: error: 64 bits support needs a fortran 90 compiler." >&2;}
+      { { echo "$as_me:$LINENO: error: 64 bits support needs a fortran 90 compiler (try --with-gfortran)." >&5
+echo "$as_me: error: 64 bits support needs a fortran 90 compiler (try --with-gfortran)." >&2;}
    { (exit 1); exit 1; }; }
    fi
 
