update gtk

diff --git a/scilab/configure b/scilab/configure
--- a/scilab/configure
+++ b/scilab/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.25 .
+# From configure.in Revision: 1.26 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52.
 #
@@ -11361,7 +11361,11 @@ echo "$as_me: error: you need at least version 1.2 of gtk" >&2;}
    { (exit 1); exit 1; }; }
      ;;
     * )
-     echo "$as_me:11364: result: $GTK_VER" >&5
+     # we have cheched above that gtk-config is in the
+     # path, then we don't want to generate a full path
+     # for gtk-config or to directly generate the
+     # result of `gtk-config --cflags`. Idem for gnome
+     echo "$as_me:11368: result: $GTK_VER" >&5
 echo "${ECHO_T}$GTK_VER" >&6
      GTKCFLAGS='`gtk-config --cflags`'
      GTKLIBS='`gtk-config --libs`'
@@ -11430,7 +11434,7 @@ saved_cflags="$CFLAGS"
 saved_ldflags="$LDFLAGS"
 saved_cppflags="$CPPFLAGS"
 
-echo "$as_me:11433: checking for main in -ldl" >&5
+echo "$as_me:11437: checking for main in -ldl" >&5
 echo $ECHO_N "checking for main in -ldl... $ECHO_C" >&6
 if test "${ac_cv_lib_dl_main+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -11438,7 +11442,7 @@ else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-ldl  $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
-#line 11441 "configure"
+#line 11445 "configure"
 #include "confdefs.h"
 
 int
@@ -11450,16 +11454,16 @@ main ();
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:11453: \"$ac_link\"") >&5
+if { (eval echo "$as_me:11457: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:11456: \$? = $ac_status" >&5
+  echo "$as_me:11460: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:11459: \"$ac_try\"") >&5
+  { (eval echo "$as_me:11463: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:11462: \$? = $ac_status" >&5
+  echo "$as_me:11466: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   ac_cv_lib_dl_main=yes
 else
@@ -11470,7 +11474,7 @@ fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:11473: result: $ac_cv_lib_dl_main" >&5
+echo "$as_me:11477: result: $ac_cv_lib_dl_main" >&5
 echo "${ECHO_T}$ac_cv_lib_dl_main" >&6
 if test $ac_cv_lib_dl_main = yes; then
   TCLTK_LIBS=" -ldl"
@@ -11493,7 +11497,7 @@ CHK_TCL_INC_NAME=tcl.h
 
 echo $ac_n "  testing version (need $CHK_TCL_MAJOR.$CHK_TCL_MINOR or later)... " $ac_c
 cat > conftest.$ac_ext <<EOF
-#line 11496 "configure"
+#line 11500 "configure"
 #include "confdefs.h"
 
 #include "$CHK_TCL_INCLUDE_PATH/$CHK_TCL_INC_NAME"
@@ -11579,7 +11583,7 @@ LDFLAGS=$LDFLAGS
 # Check for Tcl lib
 echo $ac_n "  ""$ac_c"
 if test "$USER_TCL_LIB_PATH" = ""
-then echo "$as_me:11582: checking for Tcl_DoOneEvent in -lm" >&5
+then echo "$as_me:11586: checking for Tcl_DoOneEvent in -lm" >&5
 echo $ECHO_N "checking for Tcl_DoOneEvent in -lm... $ECHO_C" >&6
 if test "${ac_cv_lib_m_Tcl_DoOneEvent+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -11587,7 +11591,7 @@ else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-lm  -l$NAME_LIB_TCL $X_LIBS $X_EXTRA_LIBS $TCLTK_LIBS $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
-#line 11590 "configure"
+#line 11594 "configure"
 #include "confdefs.h"
 
 /* Override any gcc2 internal prototype to avoid an error.  */
@@ -11606,16 +11610,16 @@ Tcl_DoOneEvent ();
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:11609: \"$ac_link\"") >&5
+if { (eval echo "$as_me:11613: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:11612: \$? = $ac_status" >&5
+  echo "$as_me:11616: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:11615: \"$ac_try\"") >&5
+  { (eval echo "$as_me:11619: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:11618: \$? = $ac_status" >&5
+  echo "$as_me:11622: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   ac_cv_lib_m_Tcl_DoOneEvent=yes
 else
@@ -11626,7 +11630,7 @@ fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:11629: result: $ac_cv_lib_m_Tcl_DoOneEvent" >&5
+echo "$as_me:11633: result: $ac_cv_lib_m_Tcl_DoOneEvent" >&5
 echo "${ECHO_T}$ac_cv_lib_m_Tcl_DoOneEvent" >&6
 if test $ac_cv_lib_m_Tcl_DoOneEvent = yes; then
   TCL_LIB_OK=1
@@ -11634,7 +11638,7 @@ else
   TCL_LIB_OK=0
 fi
 
-else echo "$as_me:11637: checking for Tcl_DoOneEvent in -lm" >&5
+else echo "$as_me:11641: checking for Tcl_DoOneEvent in -lm" >&5
 echo $ECHO_N "checking for Tcl_DoOneEvent in -lm... $ECHO_C" >&6
 if test "${ac_cv_lib_m_Tcl_DoOneEvent+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -11642,7 +11646,7 @@ else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-lm  -L$USER_TCL_LIB_PATH -l$NAME_LIB_TCL $X_LIBS $X_EXTRA_LIBS $TCLTK_LIBS $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
-#line 11645 "configure"
+#line 11649 "configure"
 #include "confdefs.h"
 
 /* Override any gcc2 internal prototype to avoid an error.  */
@@ -11661,16 +11665,16 @@ Tcl_DoOneEvent ();
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:11664: \"$ac_link\"") >&5
+if { (eval echo "$as_me:11668: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:11667: \$? = $ac_status" >&5
+  echo "$as_me:11671: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:11670: \"$ac_try\"") >&5
+  { (eval echo "$as_me:11674: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:11673: \$? = $ac_status" >&5
+  echo "$as_me:11677: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   ac_cv_lib_m_Tcl_DoOneEvent=yes
 else
@@ -11681,7 +11685,7 @@ fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:11684: result: $ac_cv_lib_m_Tcl_DoOneEvent" >&5
+echo "$as_me:11688: result: $ac_cv_lib_m_Tcl_DoOneEvent" >&5
 echo "${ECHO_T}$ac_cv_lib_m_Tcl_DoOneEvent" >&6
 if test $ac_cv_lib_m_Tcl_DoOneEvent = yes; then
   TCL_LIB_OK=1
@@ -11735,7 +11739,7 @@ saved_cppflags="$CPPFLAGS"
 CPPFLAGS="$CPPFLAGS $TCL_INC_PATH $X_CFLAGS"
 echo $ac_n "  testing version (need $CHK_TK_MAJOR.$CHK_TK_MINOR or later)... " $ac_c
 cat > conftest.$ac_ext <<EOF
-#line 11738 "configure"
+#line 11742 "configure"
 #include "confdefs.h"
 
 #include "$CHK_TK_INCLUDE_PATH/$CHK_TK_INC_NAME"
@@ -11818,7 +11822,7 @@ LDFLAGS=$LDFLAGS" $X_LDFLAGS $X_LIBS"
 # Check for Tk lib
 echo $ac_n "  ""$ac_c"
 if test "$USER_TK_LIB_PATH" = ""
-then echo "$as_me:11821: checking for Tk_BindEvent in -lm" >&5
+then echo "$as_me:11825: checking for Tk_BindEvent in -lm" >&5
 echo $ECHO_N "checking for Tk_BindEvent in -lm... $ECHO_C" >&6
 if test "${ac_cv_lib_m_Tk_BindEvent+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -11826,7 +11830,7 @@ else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-lm  -l$NAME_LIB_TK  -lX11 $X_LIBS $X_EXTRA_LIBS $TCLTK_LIBS $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
-#line 11829 "configure"
+#line 11833 "configure"
 #include "confdefs.h"
 
 /* Override any gcc2 internal prototype to avoid an error.  */
@@ -11845,16 +11849,16 @@ Tk_BindEvent ();
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:11848: \"$ac_link\"") >&5
+if { (eval echo "$as_me:11852: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:11851: \$? = $ac_status" >&5
+  echo "$as_me:11855: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:11854: \"$ac_try\"") >&5
+  { (eval echo "$as_me:11858: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:11857: \$? = $ac_status" >&5
+  echo "$as_me:11861: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   ac_cv_lib_m_Tk_BindEvent=yes
 else
@@ -11865,7 +11869,7 @@ fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:11868: result: $ac_cv_lib_m_Tk_BindEvent" >&5
+echo "$as_me:11872: result: $ac_cv_lib_m_Tk_BindEvent" >&5
 echo "${ECHO_T}$ac_cv_lib_m_Tk_BindEvent" >&6
 if test $ac_cv_lib_m_Tk_BindEvent = yes; then
   TK_LIB_OK=1
@@ -11873,7 +11877,7 @@ else
   TK_LIB_OK=0
 fi
 
-else echo "$as_me:11876: checking for Tk_BindEvent in -lm" >&5
+else echo "$as_me:11880: checking for Tk_BindEvent in -lm" >&5
 echo $ECHO_N "checking for Tk_BindEvent in -lm... $ECHO_C" >&6
 if test "${ac_cv_lib_m_Tk_BindEvent+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -11881,7 +11885,7 @@ else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-lm  -L$USER_TK_LIB_PATH -l$NAME_LIB_TK  -lX11 $X_LIBS $X_EXTRA_LIBS $TCLTK_LIBS $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
-#line 11884 "configure"
+#line 11888 "configure"
 #include "confdefs.h"
 
 /* Override any gcc2 internal prototype to avoid an error.  */
@@ -11900,16 +11904,16 @@ Tk_BindEvent ();
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:11903: \"$ac_link\"") >&5
+if { (eval echo "$as_me:11907: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:11906: \$? = $ac_status" >&5
+  echo "$as_me:11910: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:11909: \"$ac_try\"") >&5
+  { (eval echo "$as_me:11913: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:11912: \$? = $ac_status" >&5
+  echo "$as_me:11916: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   ac_cv_lib_m_Tk_BindEvent=yes
 else
@@ -11920,7 +11924,7 @@ fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:11923: result: $ac_cv_lib_m_Tk_BindEvent" >&5
+echo "$as_me:11927: result: $ac_cv_lib_m_Tk_BindEvent" >&5
 echo "${ECHO_T}$ac_cv_lib_m_Tk_BindEvent" >&6
 if test $ac_cv_lib_m_Tk_BindEvent = yes; then
   TK_LIB_OK=1
@@ -11967,7 +11971,7 @@ EOF
   TKSCILIB="\$(SCIDIR)/libs/tksci.a"
   TKSCIDIR=tksci
 else
-  { { echo "$as_me:11970: error: \"TCL/TK not found. Do not use --with-tk\"" >&5
+  { { echo "$as_me:11974: error: \"TCL/TK not found. Do not use --with-tk\"" >&5
 echo "$as_me: error: \"TCL/TK not found. Do not use --with-tk\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -12090,7 +12094,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:12093: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:12097: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -12262,7 +12266,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:12265: error: ambiguous option: $1
+    { { echo "$as_me:12269: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -12281,7 +12285,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:12284: error: unrecognized option: $1
+  -*) { { echo "$as_me:12288: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -12341,7 +12345,7 @@ do
   "scripts/scilab-gtk.g" ) CONFIG_FILES="$CONFIG_FILES scripts/scilab-gtk.g" ;;
   "examples/Makefile" ) CONFIG_FILES="$CONFIG_FILES examples/Makefile" ;;
   "routines/machine.h" ) CONFIG_HEADERS="$CONFIG_HEADERS routines/machine.h" ;;
-  *) { { echo "$as_me:12344: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:12348: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -12486,7 +12490,7 @@ s,@XAW_LOCAL_SUBDIR@,$XAW_LOCAL_SUBDIR,;t t
 s,@XAW_LOCAL_INCLUDES@,$XAW_LOCAL_INCLUDES,;t t
 s,@XAW_LOCAL_LIB@,$XAW_LOCAL_LIB,;t t
 s,@GTKCFLAGS@,$GTKCFLAGS,;t t
-s,@GTKLIB@,$GTKLIB,;t t
+s,@GTKLIBS@,$GTKLIBS,;t t
 s,@GNOMECFLAGS@,$GNOMECFLAGS,;t t
 s,@TERMCAPLIB@,$TERMCAPLIB,;t t
 s,@MAIN@,$MAIN,;t t
@@ -12644,7 +12648,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:12647: creating $ac_file" >&5
+    { echo "$as_me:12651: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -12662,7 +12666,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:12665: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:12669: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -12675,7 +12679,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:12678: error: cannot find input file: $f" >&5
+           { { echo "$as_me:12682: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -12735,7 +12739,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:12738: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:12742: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -12746,7 +12750,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:12749: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:12753: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -12759,7 +12763,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:12762: error: cannot find input file: $f" >&5
+           { { echo "$as_me:12766: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -12876,7 +12880,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:12879: $ac_file is unchanged" >&5
+      { echo "$as_me:12883: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
