Change in the call process of GIWS and SWIG ... We are not using built_sources anymore but their own target ... GIWS_WRAPPERS & SWIG_WRAPPERS ...\n * Option --with-giws-generation=/home/sylvestre/dev/giws/trunk/ also added

diff --git a/scilab/configure b/scilab/configure
--- a/scilab/configure
+++ b/scilab/configure
@@ -885,12 +885,16 @@ JAVA_HOME
 SWIG_BIN
 SWIG_RUNTIME_LIBS_DIR
 SWIG_JAVA
+PYTHON
+GIWS_BIN
 GUI_TRUE
 GUI_FALSE
 JAVASCI_TRUE
 JAVASCI_FALSE
 SWIG_TRUE
 SWIG_FALSE
+GIWS_TRUE
+GIWS_FALSE
 GREP
 EGREP
 LIBOBJS
@@ -1577,6 +1581,7 @@ Optional Packages:
   --without-javasci       do not compile the Java/Scilab module
   --without-gui           do not compile the Graphical User Interface (GUI). Intended for embedded/clustering/grid Scilab
   --with-swig-generation  Regenerate Java => C wrappers produces by Swig (A Java Development Kit (JDK) is mandatory for this option)
+  --with-giws-generation  Regenerate C/C++ => Java wrappers produces by Giws (A Java Development Kit (JDK) is mandatory for this option)
   --with-x                use the X Window System
   --with-jdk=DIR          use JDK from DIR
   --with-ant=DIR          use ant from DIR
@@ -4299,6 +4304,13 @@ fi
 # Check whether --with-swig-generation was given.
 if test "${with_swig_generation+set}" = set; then
   withval=$with_swig_generation;
+fi
+
+
+
+# Check whether --with-giws-generation was given.
+if test "${with_giws_generation+set}" = set; then
+  withval=$with_giws_generation;
 fi
 
 
@@ -10106,7 +10118,7 @@ echo "${ECHO_T}$ac_java_classpath" >&6; }
 echo $ECHO_N "checking to see if the java compiler works... $ECHO_C" >&6; }
 
     cat << \EOF > conftest.java
-// #line 10109 "configure"
+// #line 10121 "configure"
 
 
 public class conftest {
@@ -10156,7 +10168,7 @@ echo $ECHO_N "checking type of jvm... $ECHO_C" >&6; }
     if test "x$ac_java_jvm_name" = "x" ; then
 
     cat << \EOF > conftest.java
-// #line 10159 "configure"
+// #line 10171 "configure"
 import gnu.java.io.EncodingManager;
 
 public class conftest {
@@ -10204,7 +10216,7 @@ echo $ECHO_N "checking java API version... $ECHO_C" >&6; }
 
 
     cat << \EOF > conftest.java
-// #line 10207 "configure"
+// #line 10219 "configure"
 import java.nio.charset.Charset;
 
 public class conftest {
@@ -10231,7 +10243,7 @@ EOF
 
 
     cat << \EOF > conftest.java
-// #line 10234 "configure"
+// #line 10246 "configure"
 import java.lang.StringBuilder;
 
 public class conftest {
@@ -11419,7 +11431,7 @@ echo $ECHO_N "checking flexdock... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11422 "configure"
+// #line 11434 "configure"
 import org.flexdock.docking.DockingManager;
 
 public class conftest {
@@ -11482,7 +11494,7 @@ echo $ECHO_N "checking jogl... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11485 "configure"
+// #line 11497 "configure"
 import javax.media.opengl.GL;
 
 public class conftest {
@@ -11545,7 +11557,7 @@ echo $ECHO_N "checking gluegen-rt... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11548 "configure"
+// #line 11560 "configure"
 import com.sun.gluegen.runtime.CPU;
 
 public class conftest {
@@ -11608,7 +11620,7 @@ echo $ECHO_N "checking JRosetta-API... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11611 "configure"
+// #line 11623 "configure"
 import com.artenum.rosetta.interfaces.core.ConsoleConfiguration;
 
 public class conftest {
@@ -11671,7 +11683,7 @@ echo $ECHO_N "checking JRosetta-1.0... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11674 "configure"
+// #line 11686 "configure"
 import com.artenum.rosetta.core.action.AbstractConsoleAction;
 
 public class conftest {
@@ -11734,7 +11746,7 @@ echo $ECHO_N "checking commons-logging... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11737 "configure"
+// #line 11749 "configure"
 import org.apache.commons.logging.LogFactory;
 
 public class conftest {
@@ -11797,7 +11809,7 @@ echo "$as_me: WARNING: We do not support $ac_java_jvm_name yet" >&2;}
 
 
 
-	if test "$with_swig_generation" = yes; then
+	if test "$with_swig_generation" != no; then
 
 	# Extract the first word of "swig", so it can be a program name with args.
 set dummy swig; ac_word=$2
@@ -11878,7 +11890,136 @@ echo "$as_me: SWIG runtime library directory is '$SWIG_RUNTIME_LIBS_DIR'" >&6;}
 
 
 
+
 	fi
+
+	# Giws is the equivalent of Swig developped by the Scilab team
+	# in order to provide a wrapper to Java from C/C++
+	if test "$with_giws_generation" != no; then
+
+# Checking Python in the current path... As Giws is not at all mandatory
+# Python is not mandatory and we don't want to provide an additionnal option
+# to the ./configure
+   for ac_prog in python
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_PYTHON+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$PYTHON"; then
+  ac_cv_prog_PYTHON="$PYTHON" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_PYTHON="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+fi
+fi
+PYTHON=$ac_cv_prog_PYTHON
+if test -n "$PYTHON"; then
+  { echo "$as_me:$LINENO: result: $PYTHON" >&5
+echo "${ECHO_T}$PYTHON" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+  test -n "$PYTHON" && break
+done
+test -n "$PYTHON" || PYTHON="no"
+
+   if test "x$PYTHON" = "xno"; then
+		{ { echo "$as_me:$LINENO: error: Giws needs Python" >&5
+echo "$as_me: error: Giws needs Python" >&2;}
+   { (exit 1); exit 1; }; }
+   fi
+
+## If the user is providing a path to the option
+if test "$with_giws_generation" != 'yes' -a "$with_giws_generation" != 'no'; then
+
+   { echo "$as_me:$LINENO: checking giws" >&5
+echo $ECHO_N "checking giws... $ECHO_C" >&6; }
+   GIWS_BIN="$with_giws_generation/giws.py"
+   if test -f "$GIWS_BIN"; then
+                { echo "$as_me:$LINENO: result: $GIWS_BIN" >&5
+echo "${ECHO_T}$GIWS_BIN" >&6; }
+        else
+                { { echo "$as_me:$LINENO: error: Unable to find $GIWS_BIN. Please check the path you provided" >&5
+echo "$as_me: error: Unable to find $GIWS_BIN. Please check the path you provided" >&2;}
+   { (exit 1); exit 1; }; }
+		fi
+else
+# Looks for it in the path
+   for ac_prog in giws.py
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_GIWS_BIN+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$GIWS_BIN"; then
+  ac_cv_prog_GIWS_BIN="$GIWS_BIN" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_GIWS_BIN="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+fi
+fi
+GIWS_BIN=$ac_cv_prog_GIWS_BIN
+if test -n "$GIWS_BIN"; then
+  { echo "$as_me:$LINENO: result: $GIWS_BIN" >&5
+echo "${ECHO_T}$GIWS_BIN" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+  test -n "$GIWS_BIN" && break
+done
+test -n "$GIWS_BIN" || GIWS_BIN="no"
+
+   if test "x$GIWS_BIN" = "xno"; then
+		{ { echo "$as_me:$LINENO: error: Could find giws.py in the PATH" >&5
+echo "$as_me: error: Could find giws.py in the PATH" >&2;}
+   { (exit 1); exit 1; }; }
+   fi
+fi
+chmod +x $GIWS_BIN
+
+
+
+	fi
+
 fi
 
  if test "$with_gui" != no; then
@@ -11897,12 +12038,20 @@ else
   JAVASCI_FALSE=
 fi
 
- if test "$with_swig_generation" = yes; then
+ if test "$with_swig_generation" != no; then
   SWIG_TRUE=
   SWIG_FALSE='#'
 else
   SWIG_TRUE='#'
   SWIG_FALSE=
+fi
+
+ if test "$with_giws_generation" != no; then
+  GIWS_TRUE=
+  GIWS_FALSE='#'
+else
+  GIWS_TRUE='#'
+  GIWS_FALSE=
 fi
 
 
@@ -18524,7 +18673,7 @@ CPPFLAGS="$CPPFLAGS -I$CHK_TCL_INCLUDE_PATH"
 { echo "$as_me:$LINENO: checking if tcl is version $CHK_TCL_MAJOR.$CHK_TCL_MINOR or later" >&5
 echo $ECHO_N "checking if tcl is version $CHK_TCL_MAJOR.$CHK_TCL_MINOR or later... $ECHO_C" >&6; }
 cat > conftest.$ac_ext <<EOF
-#line 18527 "configure"
+#line 18676 "configure"
 #include "confdefs.h"
 
 #include "$CHK_TCL_INCLUDE_PATH/$CHK_TCL_INC_NAME"
@@ -18885,7 +19034,7 @@ CPPFLAGS="$CPPFLAGS $TCL_INC_PATH -I$CHK_TK_INCLUDE_PATH $X_CFLAGS"
 echo $ECHO_N "checking if tk is version $CHK_TK_MAJOR.$CHK_TK_MINOR or later... $ECHO_C" >&6; }
 
 cat > conftest.$ac_ext <<EOF
-#line 18888 "configure"
+#line 19037 "configure"
 #include "confdefs.h"
 
 #include "$CHK_TK_INCLUDE_PATH/$CHK_TK_INC_NAME"
@@ -20473,13 +20622,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:20476: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:20625: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:20479: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:20628: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:20482: output\"" >&5)
+  (eval echo "\"\$as_me:20631: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -21565,7 +21714,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 21568 "configure"' > conftest.$ac_ext
+  echo '#line 21717 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -23159,11 +23308,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:23162: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:23311: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:23166: \$? = $ac_status" >&5
+   echo "$as_me:23315: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -23481,11 +23630,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:23484: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:23633: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:23488: \$? = $ac_status" >&5
+   echo "$as_me:23637: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -23586,11 +23735,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:23589: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:23738: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:23593: \$? = $ac_status" >&5
+   echo "$as_me:23742: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -23641,11 +23790,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:23644: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:23793: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:23648: \$? = $ac_status" >&5
+   echo "$as_me:23797: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -26390,7 +26539,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 26393 "configure"
+#line 26542 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -26490,7 +26639,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 26493 "configure"
+#line 26642 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -28512,11 +28661,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:28515: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:28664: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:28519: \$? = $ac_status" >&5
+   echo "$as_me:28668: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -28611,11 +28760,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:28614: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:28763: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:28618: \$? = $ac_status" >&5
+   echo "$as_me:28767: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -28663,11 +28812,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:28666: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:28815: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:28670: \$? = $ac_status" >&5
+   echo "$as_me:28819: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -30038,11 +30187,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:30041: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:30190: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:30045: \$? = $ac_status" >&5
+   echo "$as_me:30194: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -30137,11 +30286,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:30140: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:30289: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:30144: \$? = $ac_status" >&5
+   echo "$as_me:30293: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -30189,11 +30338,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:30192: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:30341: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:30196: \$? = $ac_status" >&5
+   echo "$as_me:30345: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -32604,6 +32753,13 @@ echo "$as_me: error: conditional \"SWIG\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${GIWS_TRUE}" && test -z "${GIWS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"GIWS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"GIWS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${SCICOS_TRUE}" && test -z "${SCICOS_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"SCICOS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -33845,12 +34001,16 @@ JAVA_HOME!$JAVA_HOME$ac_delim
 SWIG_BIN!$SWIG_BIN$ac_delim
 SWIG_RUNTIME_LIBS_DIR!$SWIG_RUNTIME_LIBS_DIR$ac_delim
 SWIG_JAVA!$SWIG_JAVA$ac_delim
+PYTHON!$PYTHON$ac_delim
+GIWS_BIN!$GIWS_BIN$ac_delim
 GUI_TRUE!$GUI_TRUE$ac_delim
 GUI_FALSE!$GUI_FALSE$ac_delim
 JAVASCI_TRUE!$JAVASCI_TRUE$ac_delim
 JAVASCI_FALSE!$JAVASCI_FALSE$ac_delim
 SWIG_TRUE!$SWIG_TRUE$ac_delim
 SWIG_FALSE!$SWIG_FALSE$ac_delim
+GIWS_TRUE!$GIWS_TRUE$ac_delim
+GIWS_FALSE!$GIWS_FALSE$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
@@ -33912,7 +34072,7 @@ tcldir!$tcldir$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 89; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 93; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -35445,11 +35605,19 @@ fi
 
 echo ""
 echo "SWIG Configuration:"
-if test ! -z "$SWIGBIN"; then
+if test ! -z "$SWIG_BIN"; then
 echo "  SWIG_BIN ............ = $SWIG_BIN"
 echo "  SWIG_JAVA ........... = $SWIG_JAVA"
 else
 echo "  SWIG generation disabled"
+fi
+
+echo ""
+echo "GIWS Configuration:"
+if test ! -z "$GIWS_BIN"; then
+echo "  GIWS_BIN ............ = $GIWS_BIN"
+else
+echo "  GIWS generation disabled"
 fi
 
 echo ""
