fix a bug introduced in r27597 & use pkgconfig 0.21 in order to use the same version that sly

diff --git a/scilab/configure b/scilab/configure
--- a/scilab/configure
+++ b/scilab/configure
@@ -25428,10 +25428,11 @@ pkg_failed=no
 { echo "$as_me:$LINENO: checking for MATIO" >&5
 echo $ECHO_N "checking for MATIO... $ECHO_C" >&6; }
 
-if test -n "$MATIO_CFLAGS"; then
-    pkg_cv_MATIO_CFLAGS="$MATIO_CFLAGS"
- elif test -n "$PKG_CONFIG"; then
-    if test -n "$PKG_CONFIG" && \
+if test -n "$PKG_CONFIG"; then
+    if test -n "$MATIO_CFLAGS"; then
+        pkg_cv_MATIO_CFLAGS="$MATIO_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"matio >= 1.3.3\"") >&5
   ($PKG_CONFIG --exists --print-errors "matio >= 1.3.3") 2>&5
   ac_status=$?
@@ -25441,13 +25442,15 @@ if test -n "$MATIO_CFLAGS"; then
 else
   pkg_failed=yes
 fi
- else
-    pkg_failed=untried
+    fi
+else
+	pkg_failed=untried
 fi
-if test -n "$MATIO_LIBS"; then
-    pkg_cv_MATIO_LIBS="$MATIO_LIBS"
- elif test -n "$PKG_CONFIG"; then
-    if test -n "$PKG_CONFIG" && \
+if test -n "$PKG_CONFIG"; then
+    if test -n "$MATIO_LIBS"; then
+        pkg_cv_MATIO_LIBS="$MATIO_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
     { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"matio >= 1.3.3\"") >&5
   ($PKG_CONFIG --exists --print-errors "matio >= 1.3.3") 2>&5
   ac_status=$?
@@ -25457,8 +25460,9 @@ if test -n "$MATIO_LIBS"; then
 else
   pkg_failed=yes
 fi
- else
-    pkg_failed=untried
+    fi
+else
+	pkg_failed=untried
 fi
 
 
@@ -25471,9 +25475,9 @@ else
         _pkg_short_errors_supported=no
 fi
         if test $_pkg_short_errors_supported = yes; then
-	        MATIO_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "matio >= 1.3.3" 2>&1`
+	        MATIO_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "matio >= 1.3.3"`
         else
-	        MATIO_PKG_ERRORS=`$PKG_CONFIG --print-errors "matio >= 1.3.3" 2>&1`
+	        MATIO_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "matio >= 1.3.3"`
         fi
 	# Put the nasty error message in config.log where it belongs
 	echo "$MATIO_PKG_ERRORS" >&5
@@ -25510,7 +25514,7 @@ Alternatively, you may set the environment variables MATIO_CFLAGS
 and MATIO_LIBS to avoid the need to call pkg-config.
 See the pkg-config man page for more details.
 
-To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&5
 echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
 is in your PATH or set the PKG_CONFIG environment variable to the full
@@ -25520,7 +25524,7 @@ Alternatively, you may set the environment variables MATIO_CFLAGS
 and MATIO_LIBS to avoid the need to call pkg-config.
 See the pkg-config man page for more details.
 
-To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+To get pkg-config, see <http://www.freedesktop.org/software/pkgconfig>.
 See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }
 else
@@ -25533,6 +25537,9 @@ fi
 
    save_CFLAGS="$CFLAGS"
    save_LIBS="$LIBS"
+
+   CFLAGS="$CFLAGS $MATIO_CFLAGS"
+   LIBS="$LIBS $MATIO_LIBS"
 
 
 
@@ -25684,7 +25691,8 @@ fi
 
 done
 
-   { echo "$as_me:$LINENO: checking for Mat_Open in -lmatio" >&5
+
+{ echo "$as_me:$LINENO: checking for Mat_Open in -lmatio" >&5
 echo $ECHO_N "checking for Mat_Open in -lmatio... $ECHO_C" >&6; }
 if test "${ac_cv_lib_matio_Mat_Open+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -25754,8 +25762,14 @@ fi
 { echo "$as_me:$LINENO: result: $ac_cv_lib_matio_Mat_Open" >&5
 echo "${ECHO_T}$ac_cv_lib_matio_Mat_Open" >&6; }
 if test $ac_cv_lib_matio_Mat_Open = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBMATIO 1
+_ACEOF
 
-     { { echo "$as_me:$LINENO: error: Invalid MATIO_LIBS returned by pkg-config. Try to define MATIO_LIBS." >&5
+  LIBS="-lmatio $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: Invalid MATIO_LIBS returned by pkg-config. Try to define MATIO_LIBS." >&5
 echo "$as_me: error: Invalid MATIO_LIBS returned by pkg-config. Try to define MATIO_LIBS." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -25838,7 +25852,7 @@ echo $ECHO_N "checking batik... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 25841 "configure"
+// #line 25855 "configure"
 import org.apache.batik.parser.Parser;
 
 public class conftest {
@@ -25906,7 +25920,7 @@ echo $ECHO_N "checking saxon... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 25909 "configure"
+// #line 25923 "configure"
 import com.icl.saxon.Loader;
 
 public class conftest {
@@ -25974,7 +25988,7 @@ echo $ECHO_N "checking fop... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 25977 "configure"
+// #line 25991 "configure"
 import org.apache.fop.pdf.PDFInfo;
 
 public class conftest {
@@ -26042,7 +26056,7 @@ echo $ECHO_N "checking jeuclid-core... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 26045 "configure"
+// #line 26059 "configure"
 import net.sourceforge.jeuclid.MathBase;
 
 public class conftest {
@@ -26110,7 +26124,7 @@ echo $ECHO_N "checking commons-io... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 26113 "configure"
+// #line 26127 "configure"
 import org.apache.commons.io.output.CountingOutputStream;
 
 public class conftest {
@@ -26178,7 +26192,7 @@ echo $ECHO_N "checking xmlgraphics-commons... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 26181 "configure"
+// #line 26195 "configure"
 import org.apache.xmlgraphics.util.Service;
 
 public class conftest {
@@ -26247,7 +26261,7 @@ echo $ECHO_N "checking avalon-framework... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 26250 "configure"
+// #line 26264 "configure"
 import org.apache.avalon.framework.configuration.ConfigurationException;
 
 public class conftest {
@@ -26887,7 +26901,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 26890 "configure"' > conftest.$ac_ext
+  echo '#line 26904 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -28757,11 +28771,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:28760: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:28774: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:28764: \$? = $ac_status" >&5
+   echo "$as_me:28778: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -29047,11 +29061,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:29050: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:29064: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:29054: \$? = $ac_status" >&5
+   echo "$as_me:29068: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -29151,11 +29165,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:29154: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:29168: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:29158: \$? = $ac_status" >&5
+   echo "$as_me:29172: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -31600,7 +31614,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 31603 "configure"
+#line 31617 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -31700,7 +31714,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 31703 "configure"
+#line 31717 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -34121,11 +34135,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:34124: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:34138: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:34128: \$? = $ac_status" >&5
+   echo "$as_me:34142: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -34225,11 +34239,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:34228: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:34242: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:34232: \$? = $ac_status" >&5
+   echo "$as_me:34246: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -35823,11 +35837,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:35826: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:35840: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:35830: \$? = $ac_status" >&5
+   echo "$as_me:35844: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -35927,11 +35941,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:35930: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:35944: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:35934: \$? = $ac_status" >&5
+   echo "$as_me:35948: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -38151,11 +38165,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:38154: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:38168: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:38158: \$? = $ac_status" >&5
+   echo "$as_me:38172: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -38441,11 +38455,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:38444: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:38458: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:38448: \$? = $ac_status" >&5
+   echo "$as_me:38462: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -38545,11 +38559,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:38548: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:38562: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:38552: \$? = $ac_status" >&5
+   echo "$as_me:38566: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
