better feedback

diff --git a/scilab/configure b/scilab/configure
--- a/scilab/configure
+++ b/scilab/configure
@@ -21298,7 +21298,7 @@ fi
   # Check for tcl header file
   { echo "$as_me:$LINENO: checking for header file tcl.h" >&5
 echo $ECHO_N "checking for header file tcl.h... $ECHO_C" >&6; }
-  dirs="$USER_TCL_INC_PATH /include /usr/include /usr/include/tcl /usr/include/tcl8.* /usr/local/include /usr/local/include/tcl /usr/local/include/tcl8.*  /usr/X11/include/tcl /usr/X11/include/tcl8.* /usr/include/X11 /usr/include/X11/tcl /usr/include/X11/tcl8.* ../include ../../include /usr/tcl /usr/local/tcl /usr/local/tcl/include /usr/tcl/include /sw/include"
+  dirs="$USER_TCL_INC_PATH /include /usr/include /usr/include/tcl /usr/include/tcl8.5 /usr/include/tcl8.* /usr/local/include /usr/local/include/tcl /usr/local/include/tcl8.*  /usr/X11/include/tcl /usr/X11/include/tcl8.* /usr/include/X11 /usr/include/X11/tcl /usr/include/X11/tcl8.* ../include ../../include /usr/tcl /usr/local/tcl /usr/local/tcl/include /usr/tcl/include /sw/include"
   for i in $dirs ; do
 	if test -r $i/tcl.h; then
 		{ echo "$as_me:$LINENO: result: found in $i " >&5
@@ -21660,12 +21660,12 @@ done
   #perform tk tests if tcl test passed
   if test $TCL_LIB_OK = 0; then
 	if test $TCL_INCLUDE_OK = 0; then
-        	{ { echo "$as_me:$LINENO: error: no header file tcl.h found for 8.4*. Please install the dev library of tcl 8.4" >&5
-echo "$as_me: error: no header file tcl.h found for 8.4*. Please install the dev library of tcl 8.4" >&2;}
+        	{ { echo "$as_me:$LINENO: error: no header file tcl.h found for 8.4* or 8.5*. Please install the dev library of tcl 8.4 or 8.5" >&5
+echo "$as_me: error: no header file tcl.h found for 8.4* or 8.5*. Please install the dev library of tcl 8.4 or 8.5" >&2;}
    { (exit 1); exit 1; }; }
         else
-			{ { echo "$as_me:$LINENO: error: header file tcl.h has been found for 8.4*  but no corresponding tcl library (ie libtcl8.4.so)" >&5
-echo "$as_me: error: header file tcl.h has been found for 8.4*  but no corresponding tcl library (ie libtcl8.4.so)" >&2;}
+			{ { echo "$as_me:$LINENO: error: header file tcl.h has been found for 8.4* or 8.5* but no corresponding tcl library (ie libtcl8.4.so or libtcl8.5.so)" >&5
+echo "$as_me: error: header file tcl.h has been found for 8.4* or 8.5* but no corresponding tcl library (ie libtcl8.4.so or libtcl8.5.so)" >&2;}
    { (exit 1); exit 1; }; }
         fi
   fi
@@ -21675,7 +21675,9 @@ echo "$as_me: error: header file tcl.h has been found for 8.4*  but no correspon
 echo $ECHO_N "checking for header file tk.h... $ECHO_C" >&6; }
   TK_LIB_OK=0
   TK_INCLUDE_OK=0
-  dirs="$USER_TK_INC_PATH  /include /usr/include /usr/include/tk /usr/include/tk8.* /usr/local/include /usr/local/include/tk /usr/local/include/tk8.* /usr/X11/include/tk /usr/X11/include/tk8.* /usr/include/X11 /usr/include/X11/tk /usr/include/X11/tk8.* ../include ../../include /usr/tk /usr/local/tk /usr/local/tk/include /usr/tk/include  /usr/local/tcl /usr/tcl /usr/tcl/include /usr/local/tcl/include /sw/include /usr/include/tcl8.*"
+  dirs="$USER_TK_INC_PATH  /include /usr/include /usr/include/tk /usr/include/tk8.5 /usr/include/tk8.* /usr/local/include /usr/local/include/tk /usr/local/include/tk8.* /usr/X11/include/tk /usr/X11/include/tk8.* /usr/include/X11 /usr/include/X11/tk /usr/include/X11/tk8.* ../include ../../include /usr/tk /usr/local/tk /usr/local/tk/include /usr/tk/include  /usr/local/tcl /usr/tcl /usr/tcl/include /usr/local/tcl/include /sw/include /usr/include/tcl8.5 /usr/include/tcl8.*"
+# /usr/include/tcl8.5 is checked because some distribs store tk headers
+# in /usr/include/tcl8.*
   for i in $dirs ; do
 	if test -r $i/tk.h; then
 		{ echo "$as_me:$LINENO: result: found in $i " >&5
@@ -21694,7 +21696,7 @@ CPPFLAGS="$CPPFLAGS $TCL_INC_PATH -I$CHK_TK_INCLUDE_PATH $X_CFLAGS"
 echo $ECHO_N "checking if tk is version $CHK_TK_MAJOR.$CHK_TK_MINOR or later... $ECHO_C" >&6; }
 
 cat > conftest.$ac_ext <<EOF
-#line 21697 "configure"
+#line 21699 "configure"
 #include "confdefs.h"
 
 #include "$CHK_TK_INCLUDE_PATH/$CHK_TK_INC_NAME"
@@ -22009,12 +22011,12 @@ done
 
   if test $TK_LIB_OK = 0; then
 	if test $TK_INCLUDE_OK = 0; then
-        	{ { echo "$as_me:$LINENO: error: no header file tk.h found for 8.4*. Please install the dev library of tk 8.4" >&5
-echo "$as_me: error: no header file tk.h found for 8.4*. Please install the dev library of tk 8.4" >&2;}
+        	{ { echo "$as_me:$LINENO: error: no header file tk.h found for 8.4* or 8.5*. Please install the dev library of tk 8.4 or 8.5" >&5
+echo "$as_me: error: no header file tk.h found for 8.4* or 8.5*. Please install the dev library of tk 8.4 or 8.5" >&2;}
    { (exit 1); exit 1; }; }
         else
-		{ { echo "$as_me:$LINENO: error: header file tk.h has been found for 8.4* but no corresponding tk library (libtk8.4.so)" >&5
-echo "$as_me: error: header file tk.h has been found for 8.4* but no corresponding tk library (libtk8.4.so)" >&2;}
+		{ { echo "$as_me:$LINENO: error: header file tk.h has been found for 8.4* or 8.5* but no corresponding tk library (libtk8.4.so or libtk8.5.so)" >&5
+echo "$as_me: error: header file tk.h has been found for 8.4* or 8.5* but no corresponding tk library (libtk8.4.so or libtk8.5.so)" >&2;}
    { (exit 1); exit 1; }; }
         fi
 
@@ -23038,13 +23040,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:23041: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:23043: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:23044: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:23046: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:23047: output\"" >&5)
+  (eval echo "\"\$as_me:23049: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -24130,7 +24132,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 24133 "configure"' > conftest.$ac_ext
+  echo '#line 24135 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -25763,11 +25765,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:25766: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:25768: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:25770: \$? = $ac_status" >&5
+   echo "$as_me:25772: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -26085,11 +26087,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:26088: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:26090: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:26092: \$? = $ac_status" >&5
+   echo "$as_me:26094: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -26190,11 +26192,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:26193: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:26195: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:26197: \$? = $ac_status" >&5
+   echo "$as_me:26199: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -26245,11 +26247,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:26248: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:26250: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:26252: \$? = $ac_status" >&5
+   echo "$as_me:26254: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -29074,7 +29076,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 29077 "configure"
+#line 29079 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -29174,7 +29176,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 29177 "configure"
+#line 29179 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -31212,11 +31214,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:31215: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:31217: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:31219: \$? = $ac_status" >&5
+   echo "$as_me:31221: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -31311,11 +31313,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:31314: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:31316: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:31318: \$? = $ac_status" >&5
+   echo "$as_me:31320: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -31363,11 +31365,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:31366: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:31368: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:31370: \$? = $ac_status" >&5
+   echo "$as_me:31372: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -32746,11 +32748,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:32749: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:32751: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:32753: \$? = $ac_status" >&5
+   echo "$as_me:32755: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -32845,11 +32847,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:32848: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:32850: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:32852: \$? = $ac_status" >&5
+   echo "$as_me:32854: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -32897,11 +32899,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:32900: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:32902: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:32904: \$? = $ac_status" >&5
+   echo "$as_me:32906: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -38300,6 +38302,22 @@ else
 echo "  JAVA disabled"
 fi
 
+echo ""
+echo "TCL/TK configuration:"
+echo "  TK_INC_PATH .... = $TK_INC_PATH"
+echo "  TCL_INC_PATH ... = $TCL_INC_PATH"
+echo "  TCLTK_LIBS ..... = $TCLTK_LIBS"
+
+echo ""
+echo "XML configuration:"
+echo "  XML_FLAGS ...... = $XML_FLAGS"
+echo "  XML_LIBS ....... = $XML_LIBS"
+
+echo ""
+echo "PCRE configuration:"
+echo "  PCRE_CFLAGS .... = $PCRE_CFLAGS"
+echo "  PCRE_LIBS ...... = $PCRE_LIBS"
+
 
 echo ""
 echo "SWIG Configuration:"
@@ -38361,12 +38379,5 @@ echo "  CXXFLAGS ....... = $CXXFLAGS"
 echo "  F77 ............ = $F77"
 echo "  FFLAGS ......... = $FFLAGS"
 echo "  F77_LDFLAGS .... = $F77_LDFLAGS"
-echo "  XML_FLAGS ...... = $XML_FLAGS"
-echo "  XML_LIBS ....... = $XML_LIBS"
-echo "  PCRE_CFLAGS .... = $PCRE_CFLAGS"
-echo "  PCRE_LIBS ...... = $PCRE_LIBS"
 echo "  TERMCAP_LIB .... = $TERMCAP_LIB"
-echo "  TK_INC_PATH .... = $TK_INC_PATH"
-echo "  TCL_INC_PATH ... = $TCL_INC_PATH"
-echo "  TCLTK_LIBS ..... = $TCLTK_LIBS"
 echo ""
