*Regenerated files and linker less permissive

diff --git a/scilab/configure b/scilab/configure
--- a/scilab/configure
+++ b/scilab/configure
@@ -920,6 +920,7 @@ OCAMLC
 OCAMLOPT
 OCAMLDEP
 OCAMLYACC
+OCAMLLEX
 WITH_OCAML
 SCICOS_ENABLE
 OCAML_TRUE
@@ -984,8 +985,6 @@ DSYMUTIL
 NMEDIT
 CXXCPP
 LIBTOOL
-YASP_TRUE
-YASP_FALSE
 LTLIBOBJS'
 ac_subst_files=''
       ac_precious_vars='build_alias
@@ -1608,7 +1607,6 @@ Optional Features:
   --enable-fast-install[=PKGS]
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
-  --enable-yasp           Enable the compilation of the Yasp modules
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -9824,7 +9822,7 @@ echo "${ECHO_T}$ac_java_classpath" >&6; }
 echo $ECHO_N "checking to see if the java compiler works... $ECHO_C" >&6; }
 
     cat << \EOF > conftest.java
-// #line 9827 "configure"
+// #line 9825 "configure"
 
 
 public class conftest {
@@ -9874,7 +9872,7 @@ echo $ECHO_N "checking type of jvm... $ECHO_C" >&6; }
     if test "x$ac_java_jvm_name" = "x" ; then
 
     cat << \EOF > conftest.java
-// #line 9877 "configure"
+// #line 9875 "configure"
 import gnu.java.io.EncodingManager;
 
 public class conftest {
@@ -9922,7 +9920,7 @@ echo $ECHO_N "checking java API version... $ECHO_C" >&6; }
 
 
     cat << \EOF > conftest.java
-// #line 9925 "configure"
+// #line 9923 "configure"
 import java.nio.charset.Charset;
 
 public class conftest {
@@ -9949,7 +9947,7 @@ EOF
 
 
     cat << \EOF > conftest.java
-// #line 9952 "configure"
+// #line 9950 "configure"
 import java.lang.StringBuilder;
 
 public class conftest {
@@ -11201,7 +11199,7 @@ echo $ECHO_N "checking flexdock... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11204 "configure"
+// #line 11202 "configure"
 import org.flexdock.docking.DockingManager;
 
 public class conftest {
@@ -11267,7 +11265,7 @@ echo $ECHO_N "checking jogl... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11270 "configure"
+// #line 11268 "configure"
 import javax.media.opengl.glu.GLUnurbs;
 
 public class conftest {
@@ -11333,7 +11331,7 @@ echo $ECHO_N "checking jhall... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11336 "configure"
+// #line 11334 "configure"
 import javax.help.JHelp;
 
 public class conftest {
@@ -11399,7 +11397,7 @@ echo $ECHO_N "checking gluegen-rt... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11402 "configure"
+// #line 11400 "configure"
 import com.sun.gluegen.runtime.CPU;
 
 public class conftest {
@@ -11465,7 +11463,7 @@ echo $ECHO_N "checking jrosetta-API... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11468 "configure"
+// #line 11466 "configure"
 import com.artenum.rosetta.interfaces.core.ConsoleConfiguration;
 
 public class conftest {
@@ -11531,7 +11529,7 @@ echo $ECHO_N "checking jrosetta-engine... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11534 "configure"
+// #line 11532 "configure"
 import com.artenum.rosetta.core.action.AbstractConsoleAction;
 
 public class conftest {
@@ -11597,7 +11595,7 @@ echo $ECHO_N "checking commons-logging... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11600 "configure"
+// #line 11598 "configure"
 import org.apache.commons.logging.LogFactory;
 
 public class conftest {
@@ -15795,12 +15793,11 @@ fi
 
 
 	if test "$OCAMLC" = no; then
-		{ { echo "$as_me:$LINENO: error: ocamlc not found" >&5
-echo "$as_me: error: ocamlc not found" >&2;}
+		{ { echo "$as_me:$LINENO: error: ocamlc not found. Mandatory to build Scicos." >&5
+echo "$as_me: error: ocamlc not found. Mandatory to build Scicos." >&2;}
    { (exit 1); exit 1; }; }
-	else
-
-		# Extract the first word of "ocamlopt", so it can be a program name with args.
+	fi
+	# Extract the first word of "ocamlopt", so it can be a program name with args.
 set dummy ocamlopt; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
@@ -15838,12 +15835,12 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
-		if test "$OCAMLOPT" = no; then
-			{ { echo "$as_me:$LINENO: error: ocamlopt not found" >&5
-echo "$as_me: error: ocamlopt not found" >&2;}
+	if test "$OCAMLOPT" = no; then
+		{ { echo "$as_me:$LINENO: error: ocamlopt not found. Mandatory to build Scicos." >&5
+echo "$as_me: error: ocamlopt not found. Mandatory to build Scicos." >&2;}
    { (exit 1); exit 1; }; }
-		else
-			# Extract the first word of "ocamldep", so it can be a program name with args.
+	fi
+	# Extract the first word of "ocamldep", so it can be a program name with args.
 set dummy ocamldep; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
@@ -15881,12 +15878,12 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
-			if test "$OCAMLDEP" = no; then
-				{ { echo "$as_me:$LINENO: error: ocamldep not found" >&5
-echo "$as_me: error: ocamldep not found" >&2;}
+	if test "$OCAMLDEP" = no; then
+		{ { echo "$as_me:$LINENO: error: ocamldep not found. Mandatory to build Scicos." >&5
+echo "$as_me: error: ocamldep not found. Mandatory to build Scicos." >&2;}
    { (exit 1); exit 1; }; }
-			else
-				# Extract the first word of "ocamlyacc", so it can be a program name with args.
+	fi
+	# Extract the first word of "ocamlyacc", so it can be a program name with args.
 set dummy ocamlyacc; ac_word=$2
 { echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
@@ -15924,24 +15921,66 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
-				if test "$OCAMLYACC" = no; then
-					{ { echo "$as_me:$LINENO: error: ocamlyacc not found" >&5
-echo "$as_me: error: ocamlyacc not found" >&2;}
+	if test "$OCAMLYACC" = no; then
+		{ { echo "$as_me:$LINENO: error: ocamlyacc not found. Mandatory to build Scicos." >&5
+echo "$as_me: error: ocamlyacc not found. Mandatory to build Scicos." >&2;}
    { (exit 1); exit 1; }; }
-				else
+	fi
+	# Extract the first word of "ocamllex", so it can be a program name with args.
+set dummy ocamllex; ac_word=$2
+{ echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6; }
+if test "${ac_cv_prog_OCAMLLEX+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$OCAMLLEX"; then
+  ac_cv_prog_OCAMLLEX="$OCAMLLEX" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if { test -f "$as_dir/$ac_word$ac_exec_ext" && $as_test_x "$as_dir/$ac_word$ac_exec_ext"; }; then
+    ac_cv_prog_OCAMLLEX="ocamllex"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+IFS=$as_save_IFS
+
+  test -z "$ac_cv_prog_OCAMLLEX" && ac_cv_prog_OCAMLLEX="no"
+fi
+fi
+OCAMLLEX=$ac_cv_prog_OCAMLLEX
+if test -n "$OCAMLLEX"; then
+  { echo "$as_me:$LINENO: result: $OCAMLLEX" >&5
+echo "${ECHO_T}$OCAMLLEX" >&6; }
+else
+  { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+
+	if test "$OCAMLLEX" = no; then
+		{ { echo "$as_me:$LINENO: error: ocamllex not found. Mandatory to build Scicos." >&5
+echo "$as_me: error: ocamllex not found. Mandatory to build Scicos." >&2;}
+   { (exit 1); exit 1; }; }
+	fi
 
 cat >>confdefs.h <<\_ACEOF
 #define WITH_OCAML
 _ACEOF
 
-					OCAMLC=ocamlc
-					OCAMLOPT=ocamlopt
-					OCAMLDEP=ocamldep
-					OCAMLDEP=ocamlyacc
-				fi
-			fi
-		fi
-	fi
+	OCAMLC=ocamlc
+	OCAMLOPT=ocamlopt
+	OCAMLDEP=ocamldep
+	OCAMLYACC=ocamlyacc
+	OCAMLLEX=ocamllex
+
+
 
 
 
@@ -24004,7 +24043,7 @@ CPPFLAGS="$CPPFLAGS -I$CHK_TCL_INCLUDE_PATH"
 { echo "$as_me:$LINENO: checking if tcl is version $CHK_TCL_MAJOR.$CHK_TCL_MINOR or later" >&5
 echo $ECHO_N "checking if tcl is version $CHK_TCL_MAJOR.$CHK_TCL_MINOR or later... $ECHO_C" >&6; }
 cat > conftest.$ac_ext <<EOF
-#line 24007 "configure"
+#line 24046 "configure"
 #include "confdefs.h"
 
 #include "$CHK_TCL_INCLUDE_PATH/$CHK_TCL_INC_NAME"
@@ -24388,7 +24427,7 @@ CPPFLAGS="$CPPFLAGS $TCL_INC_PATH -I$CHK_TK_INCLUDE_PATH $X_CFLAGS"
 echo $ECHO_N "checking if tk is version $CHK_TK_MAJOR.$CHK_TK_MINOR or later... $ECHO_C" >&6; }
 
 cat > conftest.$ac_ext <<EOF
-#line 24391 "configure"
+#line 24430 "configure"
 #include "confdefs.h"
 
 #include "$CHK_TK_INCLUDE_PATH/$CHK_TK_INC_NAME"
@@ -25504,7 +25543,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 25507 "configure"' > conftest.$ac_ext
+  echo '#line 25546 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -27374,11 +27413,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:27377: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:27416: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:27381: \$? = $ac_status" >&5
+   echo "$as_me:27420: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -27664,11 +27703,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:27667: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:27706: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:27671: \$? = $ac_status" >&5
+   echo "$as_me:27710: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -27768,11 +27807,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:27771: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:27810: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:27775: \$? = $ac_status" >&5
+   echo "$as_me:27814: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -30217,7 +30256,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 30220 "configure"
+#line 30259 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -30317,7 +30356,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 30320 "configure"
+#line 30359 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -32738,11 +32777,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:32741: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:32780: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:32745: \$? = $ac_status" >&5
+   echo "$as_me:32784: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -32842,11 +32881,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:32845: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:32884: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:32849: \$? = $ac_status" >&5
+   echo "$as_me:32888: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -34440,11 +34479,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:34443: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:34482: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:34447: \$? = $ac_status" >&5
+   echo "$as_me:34486: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -34544,11 +34583,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:34547: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:34586: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:34551: \$? = $ac_status" >&5
+   echo "$as_me:34590: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -36768,11 +36807,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:36771: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:36810: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:36775: \$? = $ac_status" >&5
+   echo "$as_me:36814: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -37058,11 +37097,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:37061: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:37100: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:37065: \$? = $ac_status" >&5
+   echo "$as_me:37104: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -37162,11 +37201,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:37165: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:37204: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:37169: \$? = $ac_status" >&5
+   echo "$as_me:37208: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -40093,39 +40132,6 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 
-
-
-#################
-## NEXT GEN SCILAB (Yasp = Yet Another Scilab Puffin)
-#################
-
-# Check whether --enable-yasp was given.
-if test "${enable_yasp+set}" = set; then
-  enableval=$enable_yasp;
-fi
-
-
-if test "$enable_yasp" = yes; then
-   { echo "$as_me:$LINENO: WARNING: =====================================" >&5
-echo "$as_me: WARNING: =====================================" >&2;}
-   { echo "$as_me:$LINENO: WARNING: YASP (Yet Another Scilab Puffin) is the future engine of Scilab 6. This option is only for crazy stuntman." >&5
-echo "$as_me: WARNING: YASP (Yet Another Scilab Puffin) is the future engine of Scilab 6. This option is only for crazy stuntman." >&2;}
-   { echo "$as_me:$LINENO: WARNING: =====================================" >&5
-echo "$as_me: WARNING: =====================================" >&2;}
-   sleep 2
-   YASP_ENABLE=yes
-fi
-
- if test "$enable_yasp" = yes; then
-  YASP_TRUE=
-  YASP_FALSE='#'
-else
-  YASP_TRUE='#'
-  YASP_FALSE=
-fi
-
-
-
 #################
 ## stop on warning
 #################
@@ -40426,13 +40432,6 @@ if test -z "${INSTALL_HELP_XML_TRUE}" && test -z "${INSTALL_HELP_XML_FALSE}"; th
   { { echo "$as_me:$LINENO: error: conditional \"INSTALL_HELP_XML\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"INSTALL_HELP_XML\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-if test -z "${YASP_TRUE}" && test -z "${YASP_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"YASP\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"YASP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -41234,6 +41233,7 @@ OCAMLC!$OCAMLC$ac_delim
 OCAMLOPT!$OCAMLOPT$ac_delim
 OCAMLDEP!$OCAMLDEP$ac_delim
 OCAMLYACC!$OCAMLYACC$ac_delim
+OCAMLLEX!$OCAMLLEX$ac_delim
 WITH_OCAML!$WITH_OCAML$ac_delim
 SCICOS_ENABLE!$SCICOS_ENABLE$ac_delim
 OCAML_TRUE!$OCAML_TRUE$ac_delim
@@ -41276,7 +41276,6 @@ PCRE_CONFIG!$PCRE_CONFIG$ac_delim
 PCRE_CFLAGS!$PCRE_CFLAGS$ac_delim
 PCRE_LIBS!$PCRE_LIBS$ac_delim
 PCRE_VERSION!$PCRE_VERSION$ac_delim
-XMKMF!$XMKMF$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -41318,6 +41317,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+XMKMF!$XMKMF$ac_delim
 X_CFLAGS!$X_CFLAGS$ac_delim
 X_PRE_LIBS!$X_PRE_LIBS$ac_delim
 X_LIBS!$X_LIBS$ac_delim
@@ -41339,12 +41339,10 @@ DSYMUTIL!$DSYMUTIL$ac_delim
 NMEDIT!$NMEDIT$ac_delim
 CXXCPP!$CXXCPP$ac_delim
 LIBTOOL!$LIBTOOL$ac_delim
-YASP_TRUE!$YASP_TRUE$ac_delim
-YASP_FALSE!$YASP_FALSE$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 24; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 23; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
