Better make install-html / option added to the configure : --with-install-help-xml or --without-install-help-xml / some makefile updated (a few files have been removed)

diff --git a/scilab/configure b/scilab/configure
--- a/scilab/configure
+++ b/scilab/configure
@@ -897,6 +897,8 @@ OCAMLOPT
 OCAMLDEP
 WITH_OCAML
 WITH
+INSTALL_HELP_XML_TRUE
+INSTALL_HELP_XML_FALSE
 XML_CONFIG
 XML_FLAGS
 XML_LIBS
@@ -1558,6 +1560,7 @@ Optional Packages:
   --with-atlas-library=DIR  Atlas library files are in DIR and we use Atlas
   --with-sablotron compile man pages with sablotron
   --with-xsltproc  compile man pages with xsltproc
+  --with-install-help-xml  make install will install XML files
   --with-libxml2=PREFIX    set the path to your libxml2 installation
   --with-pic              try to use only PIC/non-PIC objects [default=use
                           both]
@@ -9896,7 +9899,7 @@ echo "${ECHO_T}$ac_java_classpath" >&6; }
 echo $ECHO_N "checking to see if the java compiler works... $ECHO_C" >&6; }
 
     cat << \EOF > conftest.java
-// #line 9899 "configure"
+// #line 9902 "configure"
 
 
 public class conftest {
@@ -9946,7 +9949,7 @@ echo $ECHO_N "checking type of jvm... $ECHO_C" >&6; }
     if test "x$ac_java_jvm_name" = "x" ; then
 
     cat << \EOF > conftest.java
-// #line 9949 "configure"
+// #line 9952 "configure"
 import gnu.java.io.EncodingManager;
 
 public class conftest {
@@ -9994,7 +9997,7 @@ echo $ECHO_N "checking java API version... $ECHO_C" >&6; }
 
 
     cat << \EOF > conftest.java
-// #line 9997 "configure"
+// #line 10000 "configure"
 import java.nio.charset.Charset;
 
 public class conftest {
@@ -10021,7 +10024,7 @@ EOF
 
 
     cat << \EOF > conftest.java
-// #line 10024 "configure"
+// #line 10027 "configure"
 import java.lang.StringBuilder;
 
 public class conftest {
@@ -14409,7 +14412,7 @@ CPPFLAGS="$CPPFLAGS -I$CHK_TCL_INCLUDE_PATH"
 { echo "$as_me:$LINENO: checking if tcl is version $CHK_TCL_MAJOR.$CHK_TCL_MINOR or later" >&5
 echo $ECHO_N "checking if tcl is version $CHK_TCL_MAJOR.$CHK_TCL_MINOR or later... $ECHO_C" >&6; }
 cat > conftest.$ac_ext <<EOF
-#line 14412 "configure"
+#line 14415 "configure"
 #include "confdefs.h"
 
 #include "$CHK_TCL_INCLUDE_PATH/$CHK_TCL_INC_NAME"
@@ -14770,7 +14773,7 @@ CPPFLAGS="$CPPFLAGS $TCL_INC_PATH -I$CHK_TK_INCLUDE_PATH $X_CFLAGS"
 echo $ECHO_N "checking if tk is version $CHK_TK_MAJOR.$CHK_TK_MINOR or later... $ECHO_C" >&6; }
 
 cat > conftest.$ac_ext <<EOF
-#line 14773 "configure"
+#line 14776 "configure"
 #include "confdefs.h"
 
 #include "$CHK_TK_INCLUDE_PATH/$CHK_TK_INC_NAME"
@@ -15490,6 +15493,26 @@ unset WITH
 
 
 fi
+
+
+
+# Check whether --with-install-help-xml was given.
+if test "${with_install_help_xml+set}" = set; then
+  withval=$with_install_help_xml; with_install_help_xml=$withval
+else
+  with_install_help_xml=''
+
+fi
+
+
+ if test "$with_install_help_xml" = "yes"; then
+  INSTALL_HELP_XML_TRUE=
+  INSTALL_HELP_XML_FALSE='#'
+else
+  INSTALL_HELP_XML_TRUE='#'
+  INSTALL_HELP_XML_FALSE=
+fi
+
 
 #######################
 ## test for underscores (name mangling issues between C and fortran)
@@ -16465,13 +16488,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:16468: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:16491: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:16471: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:16494: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:16474: output\"" >&5)
+  (eval echo "\"\$as_me:16497: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -17557,7 +17580,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 17560 "configure"' > conftest.$ac_ext
+  echo '#line 17583 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -19151,11 +19174,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19154: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19177: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19158: \$? = $ac_status" >&5
+   echo "$as_me:19181: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -19473,11 +19496,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19476: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19499: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:19480: \$? = $ac_status" >&5
+   echo "$as_me:19503: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -19578,11 +19601,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19581: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19604: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:19585: \$? = $ac_status" >&5
+   echo "$as_me:19608: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -19633,11 +19656,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:19636: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:19659: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:19640: \$? = $ac_status" >&5
+   echo "$as_me:19663: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22382,7 +22405,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 22385 "configure"
+#line 22408 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -22482,7 +22505,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 22485 "configure"
+#line 22508 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -24504,11 +24527,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:24507: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:24530: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:24511: \$? = $ac_status" >&5
+   echo "$as_me:24534: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -24603,11 +24626,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:24606: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:24629: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:24610: \$? = $ac_status" >&5
+   echo "$as_me:24633: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -24655,11 +24678,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:24658: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:24681: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:24662: \$? = $ac_status" >&5
+   echo "$as_me:24685: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -26030,11 +26053,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:26033: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:26056: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:26037: \$? = $ac_status" >&5
+   echo "$as_me:26060: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -26129,11 +26152,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:26132: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:26155: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:26136: \$? = $ac_status" >&5
+   echo "$as_me:26159: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -26181,11 +26204,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:26184: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:26207: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:26188: \$? = $ac_status" >&5
+   echo "$as_me:26211: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -28592,6 +28615,13 @@ echo "$as_me: error: conditional \"PVM\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${INSTALL_HELP_XML_TRUE}" && test -z "${INSTALL_HELP_XML_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"INSTALL_HELP_XML\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"INSTALL_HELP_XML\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${am__fastdepCXX_TRUE}" && test -z "${am__fastdepCXX_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"am__fastdepCXX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -29799,6 +29829,8 @@ OCAMLOPT!$OCAMLOPT$ac_delim
 OCAMLDEP!$OCAMLDEP$ac_delim
 WITH_OCAML!$WITH_OCAML$ac_delim
 WITH!$WITH$ac_delim
+INSTALL_HELP_XML_TRUE!$INSTALL_HELP_XML_TRUE$ac_delim
+INSTALL_HELP_XML_FALSE!$INSTALL_HELP_XML_FALSE$ac_delim
 XML_CONFIG!$XML_CONFIG$ac_delim
 XML_FLAGS!$XML_FLAGS$ac_delim
 XML_LIBS!$XML_LIBS$ac_delim
@@ -29826,7 +29858,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 61; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 63; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -31270,8 +31302,8 @@ echo "Uses local xaw (--with-local-xaw) ............... : $with_local_xaw"
 echo "Use PVM (--with-pvm) ............................ : $with_pvm"
 echo "PVM include (--with-pvm-include) ................ : $PVMINCLUDE"
 echo "PVM library (--with-pvm-library) ................ : $PVMLIBDIR"
-echo "Do not use TCL/TK (--without-tk) ................. : $with_tk"
-echo "Do not compile with Ocaml (--without-ocaml) ...... : $with_ocaml"
+echo "Do not use TCL/TK (--without-tk) ................ : $with_tk"
+echo "Do not compile with Ocaml (--without-ocaml) ..... : $with_ocaml"
 echo "TCL include (--with-tcl-include) ................ : $USER_TCL_INC_PATH"
 echo "TCL library (--with-tcl-library) ................ : $USER_TCL_LIB_PATH"
 echo "TK include (--with-tk-include) .................. : $USER_TK_INC_PATH"
@@ -31279,6 +31311,7 @@ echo "TK library (--with-tk-library) .................. : $USER_TK_LIB_PATH"
 echo "Atlas library (--with-atlas-library) ............ : $USER_ATLAS_LIB_PATH"
 echo "Sablotron processor (--with-sablotron) .......... : $with_sablotron"
 echo "Xsltproc processor (--with-xsltproc) ............ : $with_xsltproc"
+echo "Install XML Help (--with-install-help-xml) ...... : $with_install_help_xml"
 echo "Do not compile Scicos (--without-scicos) ........ : $without_scicos"
 echo ""
 echo "GUI : $GUI"
