update Makefile.in (gui)

diff --git a/scilab/configure b/scilab/configure
--- a/scilab/configure
+++ b/scilab/configure
@@ -10748,8 +10748,8 @@ fi
 
 
     if test "x$JAVA" = "x" ; then
-        { { echo "$as_me:$LINENO: error: Cannot find java on $ac_java_jvm_dir/bin" >&5
-echo "$as_me: error: Cannot find java on $ac_java_jvm_dir/bin" >&2;}
+        { { echo "$as_me:$LINENO: error: Cannot find java" >&5
+echo "$as_me: error: Cannot find java" >&2;}
    { (exit 1); exit 1; }; }
     fi
 
@@ -10940,8 +10940,8 @@ fi
 
 
     if test "x$JAVAH" = "x" ; then
-        { { echo "$as_me:$LINENO: error: Cannot find $TOOL on $ac_java_jvm_dir/bin" >&5
-echo "$as_me: error: Cannot find $TOOL on $ac_java_jvm_dir/bin" >&2;}
+        { { echo "$as_me:$LINENO: error: Cannot find $TOOL" >&5
+echo "$as_me: error: Cannot find $TOOL" >&2;}
    { (exit 1); exit 1; }; }
     fi
 
@@ -11036,8 +11036,8 @@ fi
 
 
     if test "x$JAR" = "x" ; then
-        { { echo "$as_me:$LINENO: error: Cannot find jar on $ac_java_jvm_dir/bin" >&5
-echo "$as_me: error: Cannot find jar on $ac_java_jvm_dir/bin" >&2;}
+        { { echo "$as_me:$LINENO: error: Cannot find jar" >&5
+echo "$as_me: error: Cannot find jar" >&2;}
    { (exit 1); exit 1; }; }
     fi
 
@@ -11247,8 +11247,8 @@ fi
 
 
     if test "x$ANT" = "x" ; then
-        { { echo "$as_me:$LINENO: error: Cannot find ant on " >&5
-echo "$as_me: error: Cannot find ant on " >&2;}
+        { { echo "$as_me:$LINENO: error: Cannot find ant" >&5
+echo "$as_me: error: Cannot find ant" >&2;}
    { (exit 1); exit 1; }; }
     fi
 
@@ -11347,8 +11347,8 @@ fi
 
 
     if test "x$ANT" = "x" ; then
-        { { echo "$as_me:$LINENO: error: Cannot find ant on $ANTPATH/bin $ANTPATH" >&5
-echo "$as_me: error: Cannot find ant on $ANTPATH/bin $ANTPATH" >&2;}
+        { { echo "$as_me:$LINENO: error: Cannot find ant" >&5
+echo "$as_me: error: Cannot find ant" >&2;}
    { (exit 1); exit 1; }; }
     fi
 
