* change of error message * some dead code removed * with the options --without-gui and --with-javasci, we were still checking thirdparty java packages

diff --git a/scilab/configure b/scilab/configure
--- a/scilab/configure
+++ b/scilab/configure
@@ -5393,8 +5393,8 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 fi
 
 if test -z "$F77"; then
-  { { echo "$as_me:$LINENO: error: No fortran compiler. cannot compile scilab without a fortran compiler" >&5
-echo "$as_me: error: No fortran compiler. cannot compile scilab without a fortran compiler" >&2;}
+  { { echo "$as_me:$LINENO: error: No fortran compiler found. Cannot compile scilab without a fortran compiler" >&5
+echo "$as_me: error: No fortran compiler found. Cannot compile scilab without a fortran compiler" >&2;}
    { (exit 1); exit 1; }; }
 else
 	case "$F77" in
@@ -7547,7 +7547,7 @@ else
 fi
 
 
-
+echo "CXX " $CXX
 if test -z "$CXX"; then
   { { echo "$as_me:$LINENO: error: No C++ Compiler found. Cannot compile Scilab without a C++ compiler" >&5
 echo "$as_me: error: No C++ Compiler found. Cannot compile Scilab without a C++ compiler" >&2;}
@@ -7793,7 +7793,8 @@ FILES_TO_CLEAN='*.CKP *.ln *.BAK *.bak core errs ,* *~ *.a .emacs_* tags TAGS ma
 ## Find the X11 include and library directories.
 #############################################
 
-
+##
+## @TODO : should be removed
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -9460,10 +9461,6 @@ if test -n "$F77"; then
 	 ;;
 	  esac
 #	   FFLAGS_O0=`echo $FFLAGS | sed 's/-O[0-9]*//g'`
-else
-	{ { echo "$as_me:$LINENO: error: No fortran compiler found" >&5
-echo "$as_me: error: No fortran compiler found" >&2;}
-   { (exit 1); exit 1; }; }
 fi
 
 #########################
@@ -9512,6 +9509,13 @@ fi
 ############
 ## C++
 ############
+
+
+if test -z "$CXX"; then
+  { { echo "$as_me:$LINENO: error: No C++ compiler found. Cannot compile scilab without a C++ compiler" >&5
+echo "$as_me: error: No C++ compiler found. Cannot compile scilab without a C++ compiler" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 if test "$CXX" = "g++"; then
    ## With GNU C++ Compiler
@@ -10102,7 +10106,7 @@ echo "${ECHO_T}$ac_java_classpath" >&6; }
 echo $ECHO_N "checking to see if the java compiler works... $ECHO_C" >&6; }
 
     cat << \EOF > conftest.java
-// #line 10105 "configure"
+// #line 10109 "configure"
 
 
 public class conftest {
@@ -10152,7 +10156,7 @@ echo $ECHO_N "checking type of jvm... $ECHO_C" >&6; }
     if test "x$ac_java_jvm_name" = "x" ; then
 
     cat << \EOF > conftest.java
-// #line 10155 "configure"
+// #line 10159 "configure"
 import gnu.java.io.EncodingManager;
 
 public class conftest {
@@ -10200,7 +10204,7 @@ echo $ECHO_N "checking java API version... $ECHO_C" >&6; }
 
 
     cat << \EOF > conftest.java
-// #line 10203 "configure"
+// #line 10207 "configure"
 import java.nio.charset.Charset;
 
 public class conftest {
@@ -10227,7 +10231,7 @@ EOF
 
 
     cat << \EOF > conftest.java
-// #line 10230 "configure"
+// #line 10234 "configure"
 import java.lang.StringBuilder;
 
 public class conftest {
@@ -11396,6 +11400,7 @@ echo "$as_me: error: Cannot find ant" >&2;}
 
 	fi
 
+		if test "$with_gui" != no; then
 
 	{ echo "$as_me:$LINENO: checking flexdock" >&5
 echo $ECHO_N "checking flexdock... $ECHO_C" >&6; }
@@ -11414,7 +11419,7 @@ echo $ECHO_N "checking flexdock... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11417 "configure"
+// #line 11422 "configure"
 import org.flexdock.docking.DockingManager;
 
 public class conftest {
@@ -11477,7 +11482,7 @@ echo $ECHO_N "checking jogl... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11480 "configure"
+// #line 11485 "configure"
 import javax.media.opengl.GL;
 
 public class conftest {
@@ -11540,7 +11545,7 @@ echo $ECHO_N "checking gluegen-rt... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11543 "configure"
+// #line 11548 "configure"
 import com.sun.gluegen.runtime.CPU;
 
 public class conftest {
@@ -11603,7 +11608,7 @@ echo $ECHO_N "checking JRosetta-API... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11606 "configure"
+// #line 11611 "configure"
 import com.artenum.rosetta.interfaces.core.ConsoleConfiguration;
 
 public class conftest {
@@ -11666,7 +11671,7 @@ echo $ECHO_N "checking JRosetta-1.0... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11669 "configure"
+// #line 11674 "configure"
 import com.artenum.rosetta.core.action.AbstractConsoleAction;
 
 public class conftest {
@@ -11729,7 +11734,7 @@ echo $ECHO_N "checking commons-logging... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11732 "configure"
+// #line 11737 "configure"
 import org.apache.commons.logging.LogFactory;
 
 public class conftest {
@@ -11779,6 +11784,7 @@ cat >>confdefs.h <<\_ACEOF
 #define WITH_GUI
 _ACEOF
 
+		fi
 	else
 		{ echo "$as_me:$LINENO: WARNING: Sun javac not found: I will not build the java interface" >&5
 echo "$as_me: WARNING: Sun javac not found: I will not build the java interface" >&2;}
@@ -18518,7 +18524,7 @@ CPPFLAGS="$CPPFLAGS -I$CHK_TCL_INCLUDE_PATH"
 { echo "$as_me:$LINENO: checking if tcl is version $CHK_TCL_MAJOR.$CHK_TCL_MINOR or later" >&5
 echo $ECHO_N "checking if tcl is version $CHK_TCL_MAJOR.$CHK_TCL_MINOR or later... $ECHO_C" >&6; }
 cat > conftest.$ac_ext <<EOF
-#line 18521 "configure"
+#line 18527 "configure"
 #include "confdefs.h"
 
 #include "$CHK_TCL_INCLUDE_PATH/$CHK_TCL_INC_NAME"
@@ -18879,7 +18885,7 @@ CPPFLAGS="$CPPFLAGS $TCL_INC_PATH -I$CHK_TK_INCLUDE_PATH $X_CFLAGS"
 echo $ECHO_N "checking if tk is version $CHK_TK_MAJOR.$CHK_TK_MINOR or later... $ECHO_C" >&6; }
 
 cat > conftest.$ac_ext <<EOF
-#line 18882 "configure"
+#line 18888 "configure"
 #include "confdefs.h"
 
 #include "$CHK_TK_INCLUDE_PATH/$CHK_TK_INC_NAME"
@@ -20467,13 +20473,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:20470: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:20476: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:20473: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:20479: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:20476: output\"" >&5)
+  (eval echo "\"\$as_me:20482: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -21559,7 +21565,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 21562 "configure"' > conftest.$ac_ext
+  echo '#line 21568 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -23153,11 +23159,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:23156: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:23162: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:23160: \$? = $ac_status" >&5
+   echo "$as_me:23166: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -23475,11 +23481,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:23478: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:23484: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:23482: \$? = $ac_status" >&5
+   echo "$as_me:23488: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -23580,11 +23586,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:23583: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:23589: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:23587: \$? = $ac_status" >&5
+   echo "$as_me:23593: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -23635,11 +23641,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:23638: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:23644: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:23642: \$? = $ac_status" >&5
+   echo "$as_me:23648: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -26384,7 +26390,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 26387 "configure"
+#line 26393 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -26484,7 +26490,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 26487 "configure"
+#line 26493 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -28506,11 +28512,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:28509: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:28515: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:28513: \$? = $ac_status" >&5
+   echo "$as_me:28519: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -28605,11 +28611,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:28608: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:28614: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:28612: \$? = $ac_status" >&5
+   echo "$as_me:28618: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -28657,11 +28663,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:28660: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:28666: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:28664: \$? = $ac_status" >&5
+   echo "$as_me:28670: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -30032,11 +30038,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:30035: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:30041: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:30039: \$? = $ac_status" >&5
+   echo "$as_me:30045: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -30131,11 +30137,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:30134: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:30140: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:30138: \$? = $ac_status" >&5
+   echo "$as_me:30144: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -30183,11 +30189,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:30186: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:30192: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:30190: \$? = $ac_status" >&5
+   echo "$as_me:30196: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
