tcl/tk

diff --git a/scilab/configure b/scilab/configure
--- a/scilab/configure
+++ b/scilab/configure
@@ -11509,10 +11509,12 @@ CHK_TCL_INCLUDE_PATH=$i
 CHK_TCL_MAJOR=8
 CHK_TCL_MINOR=0
 CHK_TCL_INC_NAME=tcl.h
-echo "$as_me:11512: checking if tcl is version $CHK_TCL_MAJOR.$CHK_TCL_MINOR or later" >&5
+saved_cflags="$CFLAGS"
+CFLAGS="$CFLAGS -I$CHK_TCL_INCLUDE_PATH"
+echo "$as_me:11514: checking if tcl is version $CHK_TCL_MAJOR.$CHK_TCL_MINOR or later" >&5
 echo $ECHO_N "checking if tcl is version $CHK_TCL_MAJOR.$CHK_TCL_MINOR or later... $ECHO_C" >&6
 cat > conftest.$ac_ext <<EOF
-#line 11515 "configure"
+#line 11517 "configure"
 #include "confdefs.h"
 
 #include "$CHK_TCL_INCLUDE_PATH/$CHK_TCL_INC_NAME"
@@ -11540,7 +11542,7 @@ rm -f conftest*
 cat > conftest.$ac_ext <<EOF
 #include "confdefs.h"
 #include <stdio.h>
-#include "$CHK_TCL_INCLUDE_PATH/$CHK_TCL_INC_NAME"
+#include <$CHK_TCL_INC_NAME>
 int main(int argc,char **argv) {
         FILE *maj = fopen("tclmajor","w");
         FILE *min = fopen("tclminor","w");
@@ -11563,28 +11565,29 @@ fi
 TCL_INC_PATH=-I$i
 TCL_LIB=tcl$TCL_VERSION
 if test $TCL_VERSION_OK = 1; then
-	echo "$as_me:11566: result: ($TCL_VERSION) yes" >&5
+	echo "$as_me:11568: result: ($TCL_VERSION) yes" >&5
 echo "${ECHO_T}($TCL_VERSION) yes" >&6
 else
-	echo "$as_me:11569: result: ($TCL_VERSION) no" >&5
+	echo "$as_me:11571: result: ($TCL_VERSION) no" >&5
 echo "${ECHO_T}($TCL_VERSION) no" >&6
 	if $TCL_VERSION = "can't happen"; then
-		{ { echo "$as_me:11572: error: can(t happen" >&5
+		{ { echo "$as_me:11574: error: can(t happen" >&5
 echo "$as_me: error: can(t happen" >&2;}
    { (exit 1); exit 1; }; }
         else
-	   { { echo "$as_me:11576: error: you need at least version 8.0 of tcl" >&5
+	   { { echo "$as_me:11578: error: you need at least version 8.0 of tcl" >&5
 echo "$as_me: error: you need at least version 8.0 of tcl" >&2;}
    { (exit 1); exit 1; }; }
 	fi
 fi
+CFLAGS=$saved_cflags
 
 		if test $TCL_VERSION_OK = 1; then
 
 CHK_TCL_MAJ=$TCL_MAJOR_VERSION
 CHK_TCL_MIN=$TCL_MINOR_VERSION
 TCL_LIB_OK=0
-  echo "$as_me:11587: checking for tcl library tcl$TCL_MAJOR_VERSION.$TCL_MINOR_VERSION" >&5
+  echo "$as_me:11590: checking for tcl library tcl$TCL_MAJOR_VERSION.$TCL_MINOR_VERSION" >&5
 echo $ECHO_N "checking for tcl library tcl$TCL_MAJOR_VERSION.$TCL_MINOR_VERSION... $ECHO_C" >&6
 dirs="$USER_TCL_LIB_PATH /lib /usr/lib /usr/lib/tcl /usr/lib/tcl8.* /shlib /shlib/tcl /shlib/tcl8.* /usr/shlib /shlib/tcl /usr//shlib/tcl8.* /usr/local/lib /usr/local/lib/tcl /usr/local/lib/tcl8.* /usr/local/shlib /usr/X11/lib/tcl /usr/X11/lib/tcl8.* /usr/lib/X11 /usr/lib/X11/tcl /usr/lib/X11/tcl8.* ../lib ../../lib  /usr/local/tcl /usr/tcl /usr/tcl/lib /usr/local/tcl/lib ."
 libexts="so so.1.0 sl a"
@@ -11597,7 +11600,7 @@ for e in $libexts; do
 				PATH_LIB_TCL=$j
 				EXT_LIB_TCL=$e
 				NAME_LIB_TCL=$n
-				echo "$as_me:11600: result: found $m using -L$PATH_LIB_TCL -l$NAME_LIB_TCL" >&5
+				echo "$as_me:11603: result: found $m using -L$PATH_LIB_TCL -l$NAME_LIB_TCL" >&5
 echo "${ECHO_T}found $m using -L$PATH_LIB_TCL -l$NAME_LIB_TCL" >&6
 				saved_cflags="$CFLAGS"
 				saved_ldflags="$LDFLAGS"
@@ -11609,7 +11612,7 @@ echo "${ECHO_T}found $m using -L$PATH_LIB_TCL -l$NAME_LIB_TCL" >&6
 				# Check for Tcl lib
 				if test "$USER_TCL_LIB_PATH" = ""
 				then as_ac_Lib=`echo "ac_cv_lib_$NAME_LIB_TCL''_Tcl_DoOneEvent" | $as_tr_sh`
-echo "$as_me:11612: checking for Tcl_DoOneEvent in -l$NAME_LIB_TCL" >&5
+echo "$as_me:11615: checking for Tcl_DoOneEvent in -l$NAME_LIB_TCL" >&5
 echo $ECHO_N "checking for Tcl_DoOneEvent in -l$NAME_LIB_TCL... $ECHO_C" >&6
 if eval "test \"\${$as_ac_Lib+set}\" = set"; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -11617,7 +11620,7 @@ else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-l$NAME_LIB_TCL  -L$PATH_LIB_TCL -l$NAME_LIB_TCL $TCL_LDFLAGS $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
-#line 11620 "configure"
+#line 11623 "configure"
 #include "confdefs.h"
 
 /* Override any gcc2 internal prototype to avoid an error.  */
@@ -11636,16 +11639,16 @@ Tcl_DoOneEvent ();
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:11639: \"$ac_link\"") >&5
+if { (eval echo "$as_me:11642: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:11642: \$? = $ac_status" >&5
+  echo "$as_me:11645: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:11645: \"$ac_try\"") >&5
+  { (eval echo "$as_me:11648: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:11648: \$? = $ac_status" >&5
+  echo "$as_me:11651: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   eval "$as_ac_Lib=yes"
 else
@@ -11656,7 +11659,7 @@ fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:11659: result: `eval echo '${'$as_ac_Lib'}'`" >&5
+echo "$as_me:11662: result: `eval echo '${'$as_ac_Lib'}'`" >&5
 echo "${ECHO_T}`eval echo '${'$as_ac_Lib'}'`" >&6
 if test `eval echo '${'$as_ac_Lib'}'` = yes; then
   TCL_LIB_OK=1
@@ -11665,7 +11668,7 @@ else
 fi
 
 				else as_ac_Lib=`echo "ac_cv_lib_$NAME_LIB_TCL''_Tcl_DoOneEvent" | $as_tr_sh`
-echo "$as_me:11668: checking for Tcl_DoOneEvent in -l$NAME_LIB_TCL" >&5
+echo "$as_me:11671: checking for Tcl_DoOneEvent in -l$NAME_LIB_TCL" >&5
 echo $ECHO_N "checking for Tcl_DoOneEvent in -l$NAME_LIB_TCL... $ECHO_C" >&6
 if eval "test \"\${$as_ac_Lib+set}\" = set"; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -11673,7 +11676,7 @@ else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-l$NAME_LIB_TCL  -L$USER_TCL_LIB_PATH -l$NAME_LIB_TCL $TCL_LDFLAGS $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
-#line 11676 "configure"
+#line 11679 "configure"
 #include "confdefs.h"
 
 /* Override any gcc2 internal prototype to avoid an error.  */
@@ -11692,16 +11695,16 @@ Tcl_DoOneEvent ();
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:11695: \"$ac_link\"") >&5
+if { (eval echo "$as_me:11698: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:11698: \$? = $ac_status" >&5
+  echo "$as_me:11701: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:11701: \"$ac_try\"") >&5
+  { (eval echo "$as_me:11704: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:11704: \$? = $ac_status" >&5
+  echo "$as_me:11707: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   eval "$as_ac_Lib=yes"
 else
@@ -11712,7 +11715,7 @@ fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:11715: result: `eval echo '${'$as_ac_Lib'}'`" >&5
+echo "$as_me:11718: result: `eval echo '${'$as_ac_Lib'}'`" >&5
 echo "${ECHO_T}`eval echo '${'$as_ac_Lib'}'`" >&6
 if test `eval echo '${'$as_ac_Lib'}'` = yes; then
   TCL_LIB_OK=1
@@ -11746,30 +11749,30 @@ done
 
   #perform tk tests if tcl test passed
   if test $TCL_LIB_OK = 0; then
-        { { echo "$as_me:11749: error: tcl library not found" >&5
+        { { echo "$as_me:11752: error: tcl library not found" >&5
 echo "$as_me: error: tcl library not found" >&2;}
    { (exit 1); exit 1; }; }
   fi
 
   # Check for tk header file
-  echo "$as_me:11755: checking for header file k.h" >&5
+  echo "$as_me:11758: checking for header file k.h" >&5
 echo $ECHO_N "checking for header file k.h... $ECHO_C" >&6
   dirs="$USER_TK_INC_PATH  /include /usr/include /usr/include/tk /usr/include/tk8.* /usr/local/include /usr/local/include/tk /usr/local/include/tk8.* /usr/X11/include/tk /usr/X11/include/tk8.* /usr/include/X11 /usr/include/X11/tk /usr/include/X11/tk8.* ../include ../../include /usr/tk /usr/local/tk /usr/local/tk/include /usr/tk/include  /usr/local/tcl /usr/tcl /usr/tcl/include /usr/local/tcl/include"
   for i in $dirs ; do
 	if test -r $i/tk.h; then
-		echo "$as_me:11760: result: found in $i " >&5
+		echo "$as_me:11763: result: found in $i " >&5
 echo "${ECHO_T}found in $i " >&6
 
 CHK_TK_INCLUDE_PATH=$i
 CHK_TK_MAJOR=8
 CHK_TK_MINOR=0
 CHK_TK_INC_NAME=tk.h
-saved_cppflags="$CPPFLAGS"
-CPPFLAGS="$CPPFLAGS $TCL_INC_PATH $X_CFLAGS"
-echo "$as_me:11769: checking if tk is version $CHK_TK_MAJOR.$CHK_TK_MINOR or later" >&5
+saved_cppflags="$CFLAGS"
+CFLAGS="$CFLAGS -I$CHK_TK_INCLUDE_PATH $X_CFLAGS"
+echo "$as_me:11772: checking if tk is version $CHK_TK_MAJOR.$CHK_TK_MINOR or later" >&5
 echo $ECHO_N "checking if tk is version $CHK_TK_MAJOR.$CHK_TK_MINOR or later... $ECHO_C" >&6
 cat > conftest.$ac_ext <<EOF
-#line 11772 "configure"
+#line 11775 "configure"
 #include "confdefs.h"
 
 #include "$CHK_TK_INCLUDE_PATH/$CHK_TK_INC_NAME"
@@ -11797,7 +11800,7 @@ rm -f conftest*
 cat > conftest.$ac_ext <<EOF
 #include "confdefs.h"
 #include <stdio.h>
-#include "$CHK_TK_INCLUDE_PATH/$CHK_TK_INC_NAME"
+#include <$CHK_TK_INC_NAME>
 int main(int argc,char **argv) {
         FILE *maj = fopen("tkmajor","w");
         FILE *min = fopen("tkminor","w");
@@ -11821,29 +11824,29 @@ fi
 TK_INC_PATH=-I$i
 TK_LIB=tk$TK_VERSION
 if test $TK_VERSION_OK = 1; then
-	echo "$as_me:11824: result: ($TK_VERSION) yes" >&5
+	echo "$as_me:11827: result: ($TK_VERSION) yes" >&5
 echo "${ECHO_T}($TK_VERSION) yes" >&6
 else
-	echo "$as_me:11827: result: ($TK_VERSION) no" >&5
+	echo "$as_me:11830: result: ($TK_VERSION) no" >&5
 echo "${ECHO_T}($TK_VERSION) no" >&6
 	if $TK_VERSION = "can't happen"; then
-		{ { echo "$as_me:11830: error: can(t happen" >&5
+		{ { echo "$as_me:11833: error: can(t happen" >&5
 echo "$as_me: error: can(t happen" >&2;}
    { (exit 1); exit 1; }; }
         else
-	   { { echo "$as_me:11834: error: you need at least version 8.0 of tk" >&5
+	   { { echo "$as_me:11837: error: you need at least version 8.0 of tk" >&5
 echo "$as_me: error: you need at least version 8.0 of tk" >&2;}
    { (exit 1); exit 1; }; }
 	fi
 fi
- CPPFLAGS=$saved_cppflags
+CFLAGS=$saved_cflags
 
 		if test $TK_VERSION_OK = 1; then
 
 CHK_TK_MAJ=$TK_MAJOR_VERSION
 CHK_TK_MIN=$TK_MINOR_VERSION
 TK_LIB_OK=0
-  echo "$as_me:11846: checking for tcl library tcl$TK_MAJOR_VERSION.$TK_MINOR_VERSION" >&5
+  echo "$as_me:11849: checking for tcl library tcl$TK_MAJOR_VERSION.$TK_MINOR_VERSION" >&5
 echo $ECHO_N "checking for tcl library tcl$TK_MAJOR_VERSION.$TK_MINOR_VERSION... $ECHO_C" >&6
 dirs="$USER_TK_LIB_PATH /lib /usr/lib /usr/lib/tk /usr/lib/tk8.* /shlib /shlib/tk /shlib/tk8.* /usr/shlib /shlib/tk /usr/shlib/tk8.* /usr/local/lib /usr/local/lib/tk /usr/local/lib/tk8.* /usr/local/shlib /usr/X11/lib/tk /usr/X11/lib/tk8.*  /usr/lib/X11 /usr/lib/X11/tk /usr/lib/X11/tk8.* ../lib ../../lib /usr/tk /usr/local/tk /usr/local/tk/lib /usr/tk/lib /usr/local/tcl /usr/tcl /usr/local/tcl/lib /usr/tcl/lib"
 libexts="so so.1.0 sl a"
@@ -11856,7 +11859,7 @@ for e in $libexts; do
 				PATH_LIB_TK=$j
 				EXT_LIB_TK=$e
 				NAME_LIB_TK=$n
-				echo "$as_me:11859: result: found $m using -L$PATH_LIB_TK -l$NAME_LIB_TK" >&5
+				echo "$as_me:11862: result: found $m using -L$PATH_LIB_TK -l$NAME_LIB_TK" >&5
 echo "${ECHO_T}found $m using -L$PATH_LIB_TK -l$NAME_LIB_TK" >&6
 				saved_cflags="$CFLAGS"
 				saved_ldflags="$LDFLAGS"
@@ -11868,7 +11871,7 @@ echo "${ECHO_T}found $m using -L$PATH_LIB_TK -l$NAME_LIB_TK" >&6
 				# Check for Tcl lib
 				if test "$USER_TK_LIB_PATH" = ""
 				then as_ac_Lib=`echo "ac_cv_lib_$NAME_LIB_TK''_Tk_BindEvent" | $as_tr_sh`
-echo "$as_me:11871: checking for Tk_BindEvent in -l$NAME_LIB_TK" >&5
+echo "$as_me:11874: checking for Tk_BindEvent in -l$NAME_LIB_TK" >&5
 echo $ECHO_N "checking for Tk_BindEvent in -l$NAME_LIB_TK... $ECHO_C" >&6
 if eval "test \"\${$as_ac_Lib+set}\" = set"; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -11876,7 +11879,7 @@ else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-l$NAME_LIB_TK  -L$PATH_LIB_TK -l$NAME_LIB_TK $TK_LDFLAGS $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
-#line 11879 "configure"
+#line 11882 "configure"
 #include "confdefs.h"
 
 /* Override any gcc2 internal prototype to avoid an error.  */
@@ -11895,16 +11898,16 @@ Tk_BindEvent ();
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:11898: \"$ac_link\"") >&5
+if { (eval echo "$as_me:11901: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:11901: \$? = $ac_status" >&5
+  echo "$as_me:11904: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:11904: \"$ac_try\"") >&5
+  { (eval echo "$as_me:11907: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:11907: \$? = $ac_status" >&5
+  echo "$as_me:11910: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   eval "$as_ac_Lib=yes"
 else
@@ -11915,7 +11918,7 @@ fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:11918: result: `eval echo '${'$as_ac_Lib'}'`" >&5
+echo "$as_me:11921: result: `eval echo '${'$as_ac_Lib'}'`" >&5
 echo "${ECHO_T}`eval echo '${'$as_ac_Lib'}'`" >&6
 if test `eval echo '${'$as_ac_Lib'}'` = yes; then
   TK_LIB_OK=1
@@ -11924,7 +11927,7 @@ else
 fi
 
 				else as_ac_Lib=`echo "ac_cv_lib_$NAME_LIB_TK''_Tk_BindEvent" | $as_tr_sh`
-echo "$as_me:11927: checking for Tk_BindEvent in -l$NAME_LIB_TK" >&5
+echo "$as_me:11930: checking for Tk_BindEvent in -l$NAME_LIB_TK" >&5
 echo $ECHO_N "checking for Tk_BindEvent in -l$NAME_LIB_TK... $ECHO_C" >&6
 if eval "test \"\${$as_ac_Lib+set}\" = set"; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -11932,7 +11935,7 @@ else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-l$NAME_LIB_TK  -L$USER_TK_LIB_PATH -l$NAME_LIB_TK $TK_LDFLAGS $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
-#line 11935 "configure"
+#line 11938 "configure"
 #include "confdefs.h"
 
 /* Override any gcc2 internal prototype to avoid an error.  */
@@ -11951,16 +11954,16 @@ Tk_BindEvent ();
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:11954: \"$ac_link\"") >&5
+if { (eval echo "$as_me:11957: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:11957: \$? = $ac_status" >&5
+  echo "$as_me:11960: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:11960: \"$ac_try\"") >&5
+  { (eval echo "$as_me:11963: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:11963: \$? = $ac_status" >&5
+  echo "$as_me:11966: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   eval "$as_ac_Lib=yes"
 else
@@ -11971,7 +11974,7 @@ fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:11974: result: `eval echo '${'$as_ac_Lib'}'`" >&5
+echo "$as_me:11977: result: `eval echo '${'$as_ac_Lib'}'`" >&5
 echo "${ECHO_T}`eval echo '${'$as_ac_Lib'}'`" >&6
 if test `eval echo '${'$as_ac_Lib'}'` = yes; then
   TK_LIB_OK=1
@@ -12004,7 +12007,7 @@ done
   done
 
   if test $TK_LIB_OK = 0; then
-        { { echo "$as_me:12007: error: tk library not found" >&5
+        { { echo "$as_me:12010: error: tk library not found" >&5
 echo "$as_me: error: tk library not found" >&2;}
    { (exit 1); exit 1; }; }
   else
@@ -12021,7 +12024,7 @@ EOF
   TKSCILIB="\$(SCIDIR)/libs/tksci.a"
   TKSCIDIR=tksci
 else
-  { { echo "$as_me:12024: error: \"TCL/TK not found. Do not use --with-tk\"" >&5
+  { { echo "$as_me:12027: error: \"TCL/TK not found. Do not use --with-tk\"" >&5
 echo "$as_me: error: \"TCL/TK not found. Do not use --with-tk\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -12144,7 +12147,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:12147: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:12150: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -12316,7 +12319,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:12319: error: ambiguous option: $1
+    { { echo "$as_me:12322: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -12335,7 +12338,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:12338: error: unrecognized option: $1
+  -*) { { echo "$as_me:12341: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -12395,7 +12398,7 @@ do
   "scripts/scilab-gtk.g" ) CONFIG_FILES="$CONFIG_FILES scripts/scilab-gtk.g" ;;
   "examples/Makefile" ) CONFIG_FILES="$CONFIG_FILES examples/Makefile" ;;
   "routines/machine.h" ) CONFIG_HEADERS="$CONFIG_HEADERS routines/machine.h" ;;
-  *) { { echo "$as_me:12398: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:12401: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -12698,7 +12701,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:12701: creating $ac_file" >&5
+    { echo "$as_me:12704: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -12716,7 +12719,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:12719: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:12722: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -12729,7 +12732,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:12732: error: cannot find input file: $f" >&5
+           { { echo "$as_me:12735: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -12789,7 +12792,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:12792: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:12795: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -12800,7 +12803,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:12803: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:12806: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -12813,7 +12816,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:12816: error: cannot find input file: $f" >&5
+           { { echo "$as_me:12819: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -12930,7 +12933,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:12933: $ac_file is unchanged" >&5
+      { echo "$as_me:12936: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
