Force the user to have libncurses

diff --git a/scilab/configure b/scilab/configure
--- a/scilab/configure
+++ b/scilab/configure
@@ -15203,9 +15203,9 @@ cat >>confdefs.h <<\_ACEOF
 _ACEOF
 
 else
- { echo "$as_me:$LINENO: WARNING: No termcap library detected" >&5
-echo "$as_me: WARNING: No termcap library detected" >&2;}
- TERMCAPLIB=
+ { { echo "$as_me:$LINENO: error: No termcap library detected. Please install ncurses dev library (or termcap library)" >&5
+echo "$as_me: error: No termcap library detected. Please install ncurses dev library (or termcap library)" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 
