Better detection of Java for the compilation

diff --git a/scilab/configure b/scilab/configure
--- a/scilab/configure
+++ b/scilab/configure
@@ -9987,8 +9987,8 @@ fi
 
 
         if test "x$JAVAC" = "x" ; then
-            { { echo "$as_me:$LINENO: error: javac not found on PATH ... did you forget --with-jdk=DIR" >&5
-echo "$as_me: error: javac not found on PATH ... did you forget --with-jdk=DIR" >&2;}
+            { { echo "$as_me:$LINENO: error: javac not found on PATH ... did you try with --with-jdk=DIR" >&5
+echo "$as_me: error: javac not found on PATH ... did you try with --with-jdk=DIR" >&2;}
    { (exit 1); exit 1; }; }
         fi
     fi
@@ -10000,14 +10000,34 @@ echo "$as_me: error: javac '$JAVAC' does not exist.
    { (exit 1); exit 1; }; }
     fi
 
-    # Check for Solaris install which uses a symlink in /usr/bin to /usr/java/bin
+    # Check for installs which uses a symlink. If it is the case, try to resolve JAVA_HOME from it
     if test -h "$JAVAC" ; then
-        BASE=`basename $JAVAC`
-        DIR=`dirname $JAVAC`
-        if test -f $DIR/../java/bin/$BASE ; then
-            JAVAC=`cd $DIR/../java/bin;pwd`/$BASE
-        fi
+
+
+		_cur="$JAVAC"
+	while ls -ld "$_cur" 2>/dev/null | grep " -> " >/dev/null; do
+		{ echo "$as_me:$LINENO: checking Symlink for $_cur" >&5
+echo $ECHO_N "checking Symlink for $_cur... $ECHO_C" >&6; }
+		_slink=`ls -ld "$_cur" | sed 's/.* -> //'`
+		case "$_slink" in
+			/*)
+				_cur="$_slink";;
+			# 'X' avoids triggering unwanted echo options.
+			*)
+				_cur=`echo "X$_cur" | sed -e 's/^X//' -e 's:[^/]*$::'`"$_slink";;
+		esac
+		{ echo "$as_me:$LINENO: result: $_cur" >&5
+echo "${ECHO_T}$_cur" >&6; }
+	done
+	SYMLINK_FOLLOWED_TO="$_cur"
+
+        TMP=`dirname $SYMLINK_FOLLOWED_TO`
+        TMP=`dirname $TMP`
+        ac_java_jvm_dir=$TMP
+		echo "Java base directory (probably) available here : $ac_java_jvm_dir"
     fi
+
+
 
     # If we were searching for javac, then set ac_java_jvm_dir
     if test "x$ac_java_jvm_dir" = "x"; then
@@ -10060,7 +10080,7 @@ echo "${ECHO_T}$ac_java_classpath" >&6; }
 echo $ECHO_N "checking to see if the java compiler works... $ECHO_C" >&6; }
 
     cat << \EOF > conftest.java
-// #line 10063 "configure"
+// #line 10083 "configure"
 
 
 public class conftest {
@@ -10110,7 +10130,7 @@ echo $ECHO_N "checking type of jvm... $ECHO_C" >&6; }
     if test "x$ac_java_jvm_name" = "x" ; then
 
     cat << \EOF > conftest.java
-// #line 10113 "configure"
+// #line 10133 "configure"
 import gnu.java.io.EncodingManager;
 
 public class conftest {
@@ -10158,7 +10178,7 @@ echo $ECHO_N "checking java API version... $ECHO_C" >&6; }
 
 
     cat << \EOF > conftest.java
-// #line 10161 "configure"
+// #line 10181 "configure"
 import java.nio.charset.Charset;
 
 public class conftest {
@@ -10185,7 +10205,7 @@ EOF
 
 
     cat << \EOF > conftest.java
-// #line 10188 "configure"
+// #line 10208 "configure"
 import java.lang.StringBuilder;
 
 public class conftest {
@@ -17568,7 +17588,7 @@ CPPFLAGS="$CPPFLAGS -I$CHK_TCL_INCLUDE_PATH"
 { echo "$as_me:$LINENO: checking if tcl is version $CHK_TCL_MAJOR.$CHK_TCL_MINOR or later" >&5
 echo $ECHO_N "checking if tcl is version $CHK_TCL_MAJOR.$CHK_TCL_MINOR or later... $ECHO_C" >&6; }
 cat > conftest.$ac_ext <<EOF
-#line 17571 "configure"
+#line 17591 "configure"
 #include "confdefs.h"
 
 #include "$CHK_TCL_INCLUDE_PATH/$CHK_TCL_INC_NAME"
@@ -17929,7 +17949,7 @@ CPPFLAGS="$CPPFLAGS $TCL_INC_PATH -I$CHK_TK_INCLUDE_PATH $X_CFLAGS"
 echo $ECHO_N "checking if tk is version $CHK_TK_MAJOR.$CHK_TK_MINOR or later... $ECHO_C" >&6; }
 
 cat > conftest.$ac_ext <<EOF
-#line 17932 "configure"
+#line 17952 "configure"
 #include "confdefs.h"
 
 #include "$CHK_TK_INCLUDE_PATH/$CHK_TK_INC_NAME"
@@ -19468,13 +19488,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:19471: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:19491: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:19474: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:19494: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:19477: output\"" >&5)
+  (eval echo "\"\$as_me:19497: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -20560,7 +20580,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 20563 "configure"' > conftest.$ac_ext
+  echo '#line 20583 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -22154,11 +22174,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:22157: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:22177: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:22161: \$? = $ac_status" >&5
+   echo "$as_me:22181: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -22476,11 +22496,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:22479: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:22499: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:22483: \$? = $ac_status" >&5
+   echo "$as_me:22503: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -22581,11 +22601,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:22584: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:22604: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:22588: \$? = $ac_status" >&5
+   echo "$as_me:22608: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22636,11 +22656,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:22639: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:22659: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:22643: \$? = $ac_status" >&5
+   echo "$as_me:22663: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -25385,7 +25405,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 25388 "configure"
+#line 25408 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -25485,7 +25505,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 25488 "configure"
+#line 25508 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -27507,11 +27527,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:27510: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:27530: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:27514: \$? = $ac_status" >&5
+   echo "$as_me:27534: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -27606,11 +27626,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:27609: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:27629: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:27613: \$? = $ac_status" >&5
+   echo "$as_me:27633: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -27658,11 +27678,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:27661: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:27681: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:27665: \$? = $ac_status" >&5
+   echo "$as_me:27685: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -29033,11 +29053,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:29036: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:29056: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:29040: \$? = $ac_status" >&5
+   echo "$as_me:29060: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -29132,11 +29152,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:29135: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:29155: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:29139: \$? = $ac_status" >&5
+   echo "$as_me:29159: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -29184,11 +29204,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:29187: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:29207: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:29191: \$? = $ac_status" >&5
+   echo "$as_me:29211: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
