gtk

diff --git a/scilab/configure b/scilab/configure
--- a/scilab/configure
+++ b/scilab/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.26 .
+# From configure.in Revision: 1.27 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52.
 #
@@ -11298,25 +11298,31 @@ for ac_dir in $ac_dummy; do
   IFS=$ac_save_IFS
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
-ac_cv_prog_GTK_CONFIG="none"
+ac_cv_prog_GTK_CONFIG="yes"
 echo "$as_me:11302: found $ac_dir/$ac_word" >&5
 break
 done
 
+  test -z "$ac_cv_prog_GTK_CONFIG" && ac_cv_prog_GTK_CONFIG="no"
 fi
 fi
 GTK_CONFIG=$ac_cv_prog_GTK_CONFIG
 if test -n "$GTK_CONFIG"; then
-  echo "$as_me:11310: result: $GTK_CONFIG" >&5
+  echo "$as_me:11311: result: $GTK_CONFIG" >&5
 echo "${ECHO_T}$GTK_CONFIG" >&6
 else
-  echo "$as_me:11313: result: no" >&5
+  echo "$as_me:11314: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
+  if test "$GTK_CONFIG" = no; then
+    { echo "$as_me:11319: WARNING: \"gtk-config not found: I will not use -with-gtk\"" >&5
+echo "$as_me: WARNING: \"gtk-config not found: I will not use -with-gtk\"" >&2;}
+    with_gtk="no"
+  fi
   # Extract the first word of "gnome-config", so it can be a program name with args.
 set dummy gnome-config; ac_word=$2
-echo "$as_me:11319: checking for $ac_word" >&5
+echo "$as_me:11325: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_GNOME_CONFIG+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -11330,57 +11336,65 @@ for ac_dir in $ac_dummy; do
   IFS=$ac_save_IFS
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
-ac_cv_prog_GNOME_CONFIG="none"
-echo "$as_me:11334: found $ac_dir/$ac_word" >&5
+ac_cv_prog_GNOME_CONFIG="yes"
+echo "$as_me:11340: found $ac_dir/$ac_word" >&5
 break
 done
 
+  test -z "$ac_cv_prog_GNOME_CONFIG" && ac_cv_prog_GNOME_CONFIG="no"
 fi
 fi
 GNOME_CONFIG=$ac_cv_prog_GNOME_CONFIG
 if test -n "$GNOME_CONFIG"; then
-  echo "$as_me:11342: result: $GNOME_CONFIG" >&5
+  echo "$as_me:11349: result: $GNOME_CONFIG" >&5
 echo "${ECHO_T}$GNOME_CONFIG" >&6
 else
-  echo "$as_me:11345: result: no" >&5
+  echo "$as_me:11352: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
-  echo "$as_me:11349: checking if gtk is version 1.2 or later" >&5
+  if test "$GNOME_CONFIG" = no; then
+    { echo "$as_me:11357: WARNING: \"gnome-config not found: I will not use -with-gtk\"" >&5
+echo "$as_me: WARNING: \"gnome-config not found: I will not use -with-gtk\"" >&2;}
+    with_gtk="no"
+  fi
+  if test "$with_gtk" = yes; then
+    echo "$as_me:11362: checking if gtk is version 1.2 or later" >&5
 echo $ECHO_N "checking if gtk is version 1.2 or later... $ECHO_C" >&6
-  GTK_VER=`$GTK_CONFIG --version`
-  case $GTK_VER in
-    0.* )
-     { { echo "$as_me:11354: error: you need at least version 1.2 of gtk" >&5
+    GTK_VER=`gtk-config --version`
+    case $GTK_VER in
+      0.* )
+        { { echo "$as_me:11367: error: you need at least version 1.2 of gtk" >&5
 echo "$as_me: error: you need at least version 1.2 of gtk" >&2;}
    { (exit 1); exit 1; }; }
-     ;;
-    1.1* )
-     { { echo "$as_me:11359: error: you need at least version 1.2 of gtk" >&5
+        ;;
+      1.1* )
+        { { echo "$as_me:11372: error: you need at least version 1.2 of gtk" >&5
 echo "$as_me: error: you need at least version 1.2 of gtk" >&2;}
    { (exit 1); exit 1; }; }
-     ;;
-    * )
-     # we have cheched above that gtk-config is in the
-     # path, then we don't want to generate a full path
-     # for gtk-config or to directly generate the
-     # result of `gtk-config --cflags`. Idem for gnome
-     echo "$as_me:11368: result: $GTK_VER" >&5
+        ;;
+      * )
+      # we have cheched above that gtk-config is in the
+      # path, then we don't want to generate a full path
+      # for gtk-config or to directly generate the
+      # result of `gtk-config --cflags`. Idem for gnome
+      echo "$as_me:11381: result: $GTK_VER" >&5
 echo "${ECHO_T}$GTK_VER" >&6
-     GTKCFLAGS='`gtk-config --cflags`'
-     GTKLIBS='`gtk-config --libs`'
-     GNOMECFLAGS='`gnome-config --cflags gnome`'
-     ;;
-  esac
-  cat >>confdefs.h <<\EOF
+      GTKCFLAGS='`gtk-config --cflags`'
+      GTKLIBS='`gtk-config --libs`'
+      GNOMECFLAGS='`gnome-config --cflags gnome`'
+      ;;
+    esac
+    cat >>confdefs.h <<\EOF
 #define WITH_GTK 1
 EOF
 
-  GUILIB='gtksci'
-  GZVT='gzvt'
-  SCILABSCRIPT=scilab-gtk.g
-  MENUSOBJS=GOBJS
-  PERIFILE=periGtk.o
+    GUILIB='gtksci'
+    GZVT='gzvt'
+    SCILABSCRIPT=scilab-gtk.g
+    MENUSOBJS=GOBJS
+    PERIFILE=periGtk.o
+  fi
 fi
 
 #################
@@ -11434,7 +11448,7 @@ saved_cflags="$CFLAGS"
 saved_ldflags="$LDFLAGS"
 saved_cppflags="$CPPFLAGS"
 
-echo "$as_me:11437: checking for main in -ldl" >&5
+echo "$as_me:11451: checking for main in -ldl" >&5
 echo $ECHO_N "checking for main in -ldl... $ECHO_C" >&6
 if test "${ac_cv_lib_dl_main+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -11442,7 +11456,7 @@ else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-ldl  $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
-#line 11445 "configure"
+#line 11459 "configure"
 #include "confdefs.h"
 
 int
@@ -11454,16 +11468,16 @@ main ();
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:11457: \"$ac_link\"") >&5
+if { (eval echo "$as_me:11471: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:11460: \$? = $ac_status" >&5
+  echo "$as_me:11474: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:11463: \"$ac_try\"") >&5
+  { (eval echo "$as_me:11477: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:11466: \$? = $ac_status" >&5
+  echo "$as_me:11480: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   ac_cv_lib_dl_main=yes
 else
@@ -11474,7 +11488,7 @@ fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:11477: result: $ac_cv_lib_dl_main" >&5
+echo "$as_me:11491: result: $ac_cv_lib_dl_main" >&5
 echo "${ECHO_T}$ac_cv_lib_dl_main" >&6
 if test $ac_cv_lib_dl_main = yes; then
   TCLTK_LIBS=" -ldl"
@@ -11496,8 +11510,9 @@ CHK_TCL_MINOR=0
 CHK_TCL_INC_NAME=tcl.h
 
 echo $ac_n "  testing version (need $CHK_TCL_MAJOR.$CHK_TCL_MINOR or later)... " $ac_c
+echo $ac_n "  testing version (need $CHK_TCL_MAJOR.$CHK_TCL_MINOR or later)... "
 cat > conftest.$ac_ext <<EOF
-#line 11500 "configure"
+#line 11515 "configure"
 #include "confdefs.h"
 
 #include "$CHK_TCL_INCLUDE_PATH/$CHK_TCL_INC_NAME"
@@ -11541,7 +11556,7 @@ if test -s conftest && (./conftest; exit) 2>/dev/null; then
   tclmajor=`cat tclmajor`
   tclminor=`cat tclminor`
   TCL_VERSION=$tclmajor.$tclminor
-  echo $ac_n "it's $TCL_VERSION :""$ac_c " 1>&6
+  echo "$TCL_VERSION :""$ac_c " 1>&6
   rm -f tclmajor tclminor
 else
   echo "$ac_t""can't happen" 1>&6
@@ -11571,7 +11586,7 @@ echo "  found $m"
 PATH_LIB_TCL=$j
 EXT_LIB_TCL=$e
 NAME_LIB_TCL=$n
-echo "  link with -l$NAME_LIB_TCL -L$PATH_LIB_TCL"
+echo "  link with  -L$PATH_LIB_TCL -l$NAME_LIB_TCL"
 
 saved_cflags="$CFLAGS"
 saved_ldflags="$LDFLAGS"
@@ -11583,7 +11598,7 @@ LDFLAGS=$LDFLAGS
 # Check for Tcl lib
 echo $ac_n "  ""$ac_c"
 if test "$USER_TCL_LIB_PATH" = ""
-then echo "$as_me:11586: checking for Tcl_DoOneEvent in -lm" >&5
+then echo "$as_me:11601: checking for Tcl_DoOneEvent in -lm" >&5
 echo $ECHO_N "checking for Tcl_DoOneEvent in -lm... $ECHO_C" >&6
 if test "${ac_cv_lib_m_Tcl_DoOneEvent+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -11591,7 +11606,7 @@ else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-lm  -l$NAME_LIB_TCL $X_LIBS $X_EXTRA_LIBS $TCLTK_LIBS $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
-#line 11594 "configure"
+#line 11609 "configure"
 #include "confdefs.h"
 
 /* Override any gcc2 internal prototype to avoid an error.  */
@@ -11610,16 +11625,16 @@ Tcl_DoOneEvent ();
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:11613: \"$ac_link\"") >&5
+if { (eval echo "$as_me:11628: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:11616: \$? = $ac_status" >&5
+  echo "$as_me:11631: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:11619: \"$ac_try\"") >&5
+  { (eval echo "$as_me:11634: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:11622: \$? = $ac_status" >&5
+  echo "$as_me:11637: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   ac_cv_lib_m_Tcl_DoOneEvent=yes
 else
@@ -11630,7 +11645,7 @@ fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:11633: result: $ac_cv_lib_m_Tcl_DoOneEvent" >&5
+echo "$as_me:11648: result: $ac_cv_lib_m_Tcl_DoOneEvent" >&5
 echo "${ECHO_T}$ac_cv_lib_m_Tcl_DoOneEvent" >&6
 if test $ac_cv_lib_m_Tcl_DoOneEvent = yes; then
   TCL_LIB_OK=1
@@ -11638,7 +11653,7 @@ else
   TCL_LIB_OK=0
 fi
 
-else echo "$as_me:11641: checking for Tcl_DoOneEvent in -lm" >&5
+else echo "$as_me:11656: checking for Tcl_DoOneEvent in -lm" >&5
 echo $ECHO_N "checking for Tcl_DoOneEvent in -lm... $ECHO_C" >&6
 if test "${ac_cv_lib_m_Tcl_DoOneEvent+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -11646,7 +11661,7 @@ else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-lm  -L$USER_TCL_LIB_PATH -l$NAME_LIB_TCL $X_LIBS $X_EXTRA_LIBS $TCLTK_LIBS $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
-#line 11649 "configure"
+#line 11664 "configure"
 #include "confdefs.h"
 
 /* Override any gcc2 internal prototype to avoid an error.  */
@@ -11665,16 +11680,16 @@ Tcl_DoOneEvent ();
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:11668: \"$ac_link\"") >&5
+if { (eval echo "$as_me:11683: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:11671: \$? = $ac_status" >&5
+  echo "$as_me:11686: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:11674: \"$ac_try\"") >&5
+  { (eval echo "$as_me:11689: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:11677: \$? = $ac_status" >&5
+  echo "$as_me:11692: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   ac_cv_lib_m_Tcl_DoOneEvent=yes
 else
@@ -11685,7 +11700,7 @@ fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:11688: result: $ac_cv_lib_m_Tcl_DoOneEvent" >&5
+echo "$as_me:11703: result: $ac_cv_lib_m_Tcl_DoOneEvent" >&5
 echo "${ECHO_T}$ac_cv_lib_m_Tcl_DoOneEvent" >&6
 if test $ac_cv_lib_m_Tcl_DoOneEvent = yes; then
   TCL_LIB_OK=1
@@ -11739,7 +11754,7 @@ saved_cppflags="$CPPFLAGS"
 CPPFLAGS="$CPPFLAGS $TCL_INC_PATH $X_CFLAGS"
 echo $ac_n "  testing version (need $CHK_TK_MAJOR.$CHK_TK_MINOR or later)... " $ac_c
 cat > conftest.$ac_ext <<EOF
-#line 11742 "configure"
+#line 11757 "configure"
 #include "confdefs.h"
 
 #include "$CHK_TK_INCLUDE_PATH/$CHK_TK_INC_NAME"
@@ -11822,7 +11837,7 @@ LDFLAGS=$LDFLAGS" $X_LDFLAGS $X_LIBS"
 # Check for Tk lib
 echo $ac_n "  ""$ac_c"
 if test "$USER_TK_LIB_PATH" = ""
-then echo "$as_me:11825: checking for Tk_BindEvent in -lm" >&5
+then echo "$as_me:11840: checking for Tk_BindEvent in -lm" >&5
 echo $ECHO_N "checking for Tk_BindEvent in -lm... $ECHO_C" >&6
 if test "${ac_cv_lib_m_Tk_BindEvent+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -11830,7 +11845,7 @@ else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-lm  -l$NAME_LIB_TK  -lX11 $X_LIBS $X_EXTRA_LIBS $TCLTK_LIBS $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
-#line 11833 "configure"
+#line 11848 "configure"
 #include "confdefs.h"
 
 /* Override any gcc2 internal prototype to avoid an error.  */
@@ -11849,16 +11864,16 @@ Tk_BindEvent ();
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:11852: \"$ac_link\"") >&5
+if { (eval echo "$as_me:11867: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:11855: \$? = $ac_status" >&5
+  echo "$as_me:11870: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:11858: \"$ac_try\"") >&5
+  { (eval echo "$as_me:11873: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:11861: \$? = $ac_status" >&5
+  echo "$as_me:11876: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   ac_cv_lib_m_Tk_BindEvent=yes
 else
@@ -11869,7 +11884,7 @@ fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:11872: result: $ac_cv_lib_m_Tk_BindEvent" >&5
+echo "$as_me:11887: result: $ac_cv_lib_m_Tk_BindEvent" >&5
 echo "${ECHO_T}$ac_cv_lib_m_Tk_BindEvent" >&6
 if test $ac_cv_lib_m_Tk_BindEvent = yes; then
   TK_LIB_OK=1
@@ -11877,7 +11892,7 @@ else
   TK_LIB_OK=0
 fi
 
-else echo "$as_me:11880: checking for Tk_BindEvent in -lm" >&5
+else echo "$as_me:11895: checking for Tk_BindEvent in -lm" >&5
 echo $ECHO_N "checking for Tk_BindEvent in -lm... $ECHO_C" >&6
 if test "${ac_cv_lib_m_Tk_BindEvent+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -11885,7 +11900,7 @@ else
   ac_check_lib_save_LIBS=$LIBS
 LIBS="-lm  -L$USER_TK_LIB_PATH -l$NAME_LIB_TK  -lX11 $X_LIBS $X_EXTRA_LIBS $TCLTK_LIBS $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
-#line 11888 "configure"
+#line 11903 "configure"
 #include "confdefs.h"
 
 /* Override any gcc2 internal prototype to avoid an error.  */
@@ -11904,16 +11919,16 @@ Tk_BindEvent ();
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:11907: \"$ac_link\"") >&5
+if { (eval echo "$as_me:11922: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:11910: \$? = $ac_status" >&5
+  echo "$as_me:11925: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:11913: \"$ac_try\"") >&5
+  { (eval echo "$as_me:11928: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:11916: \$? = $ac_status" >&5
+  echo "$as_me:11931: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   ac_cv_lib_m_Tk_BindEvent=yes
 else
@@ -11924,7 +11939,7 @@ fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:11927: result: $ac_cv_lib_m_Tk_BindEvent" >&5
+echo "$as_me:11942: result: $ac_cv_lib_m_Tk_BindEvent" >&5
 echo "${ECHO_T}$ac_cv_lib_m_Tk_BindEvent" >&6
 if test $ac_cv_lib_m_Tk_BindEvent = yes; then
   TK_LIB_OK=1
@@ -11971,7 +11986,7 @@ EOF
   TKSCILIB="\$(SCIDIR)/libs/tksci.a"
   TKSCIDIR=tksci
 else
-  { { echo "$as_me:11974: error: \"TCL/TK not found. Do not use --with-tk\"" >&5
+  { { echo "$as_me:11989: error: \"TCL/TK not found. Do not use --with-tk\"" >&5
 echo "$as_me: error: \"TCL/TK not found. Do not use --with-tk\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -12094,7 +12109,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:12097: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:12112: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -12266,7 +12281,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:12269: error: ambiguous option: $1
+    { { echo "$as_me:12284: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -12285,7 +12300,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:12288: error: unrecognized option: $1
+  -*) { { echo "$as_me:12303: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -12345,7 +12360,7 @@ do
   "scripts/scilab-gtk.g" ) CONFIG_FILES="$CONFIG_FILES scripts/scilab-gtk.g" ;;
   "examples/Makefile" ) CONFIG_FILES="$CONFIG_FILES examples/Makefile" ;;
   "routines/machine.h" ) CONFIG_HEADERS="$CONFIG_HEADERS routines/machine.h" ;;
-  *) { { echo "$as_me:12348: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:12363: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -12648,7 +12663,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:12651: creating $ac_file" >&5
+    { echo "$as_me:12666: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -12666,7 +12681,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:12669: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:12684: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -12679,7 +12694,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:12682: error: cannot find input file: $f" >&5
+           { { echo "$as_me:12697: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -12739,7 +12754,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:12742: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:12757: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -12750,7 +12765,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:12753: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:12768: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -12763,7 +12778,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:12766: error: cannot find input file: $f" >&5
+           { { echo "$as_me:12781: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -12880,7 +12895,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:12883: $ac_file is unchanged" >&5
+      { echo "$as_me:12898: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
