A test for the Makefile.am added (NEED_JAVA) since we need it for the documentation & the GUI

diff --git a/scilab/configure b/scilab/configure
--- a/scilab/configure
+++ b/scilab/configure
@@ -906,6 +906,8 @@ SWIG_RUNTIME_LIBS_DIR
 SWIG_JAVA
 PYTHON
 GIWS_BIN
+NEED_JAVA_TRUE
+NEED_JAVA_FALSE
 GUI_TRUE
 GUI_FALSE
 JAVASCI_TRUE
@@ -1677,6 +1679,7 @@ Optional Packages:
                           Set the path to the MATIO headers
   --with-matio-library=DIR
                           Set the path to the MATIO libraries
+  --with-docbook=DIR      Set the path to the docbook package
   --with-install-help-xml make install will install XML files
   --with-gnu-ld           assume the C compiler uses GNU ld [default=no]
   --with-pic              try to use only PIC/non-PIC objects [default=use
@@ -9643,7 +9646,7 @@ fi
 ## test for JAVA compiler
 ###########################
 
-if test "$with_javasci" != no -o "$with_gui" != no; then
+if test "$with_javasci" != no -o "$with_gui" != no -o "$enable_build_help" != no; then
    # See if --with-jdk command line argument is given
      # Try to detect the installed JVM, this could be controlled
 	 # by the above --with options
@@ -9867,7 +9870,7 @@ echo "${ECHO_T}$ac_java_classpath" >&6; }
 echo $ECHO_N "checking to see if the java compiler works... $ECHO_C" >&6; }
 
     cat << \EOF > conftest.java
-// #line 9870 "configure"
+// #line 9873 "configure"
 
 
 public class conftest {
@@ -9917,7 +9920,7 @@ echo $ECHO_N "checking type of jvm... $ECHO_C" >&6; }
     if test "x$ac_java_jvm_name" = "x" ; then
 
     cat << \EOF > conftest.java
-// #line 9920 "configure"
+// #line 9923 "configure"
 import gnu.java.io.EncodingManager;
 
 public class conftest {
@@ -9965,7 +9968,7 @@ echo $ECHO_N "checking java API version... $ECHO_C" >&6; }
 
 
     cat << \EOF > conftest.java
-// #line 9968 "configure"
+// #line 9971 "configure"
 import java.nio.charset.Charset;
 
 public class conftest {
@@ -9992,7 +9995,7 @@ EOF
 
 
     cat << \EOF > conftest.java
-// #line 9995 "configure"
+// #line 9998 "configure"
 import java.lang.StringBuilder;
 
 public class conftest {
@@ -11247,7 +11250,7 @@ echo $ECHO_N "checking flexdock... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11250 "configure"
+// #line 11253 "configure"
 import org.flexdock.docking.DockingManager;
 
 public class conftest {
@@ -11315,7 +11318,7 @@ echo $ECHO_N "checking jogl... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11318 "configure"
+// #line 11321 "configure"
 import javax.media.opengl.glu.GLUnurbs;
 
 public class conftest {
@@ -11383,7 +11386,7 @@ echo $ECHO_N "checking jhall... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11386 "configure"
+// #line 11389 "configure"
 import javax.help.JHelp;
 
 public class conftest {
@@ -11451,7 +11454,7 @@ echo $ECHO_N "checking gluegen-rt... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11454 "configure"
+// #line 11457 "configure"
 import com.sun.gluegen.runtime.CPU;
 
 public class conftest {
@@ -11519,7 +11522,7 @@ echo $ECHO_N "checking jrosetta-API... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11522 "configure"
+// #line 11525 "configure"
 import com.artenum.rosetta.interfaces.core.ConsoleConfiguration;
 
 public class conftest {
@@ -11587,7 +11590,7 @@ echo $ECHO_N "checking jrosetta-engine... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11590 "configure"
+// #line 11593 "configure"
 import com.artenum.rosetta.core.action.AbstractConsoleAction;
 
 public class conftest {
@@ -11655,7 +11658,7 @@ echo $ECHO_N "checking commons-logging... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 11658 "configure"
+// #line 11661 "configure"
 import org.apache.commons.logging.LogFactory;
 
 public class conftest {
@@ -11932,6 +11935,14 @@ chmod +x $GIWS_BIN
 
 
 	fi
+
+	 if test "$with_javasci" != no -o "$with_gui" != no -o "$enable_build_help" != no; then
+  NEED_JAVA_TRUE=
+  NEED_JAVA_FALSE='#'
+else
+  NEED_JAVA_TRUE='#'
+  NEED_JAVA_FALSE=
+fi
 
 fi
 
@@ -23240,7 +23251,7 @@ CPPFLAGS="$CPPFLAGS -I$CHK_TCL_INCLUDE_PATH"
 { echo "$as_me:$LINENO: checking if tcl is version $CHK_TCL_MAJOR.$CHK_TCL_MINOR or later" >&5
 echo $ECHO_N "checking if tcl is version $CHK_TCL_MAJOR.$CHK_TCL_MINOR or later... $ECHO_C" >&6; }
 cat > conftest.$ac_ext <<EOF
-#line 23243 "configure"
+#line 23254 "configure"
 #include "confdefs.h"
 
 #include "$CHK_TCL_INCLUDE_PATH/$CHK_TCL_INC_NAME"
@@ -23624,7 +23635,7 @@ CPPFLAGS="$CPPFLAGS $TCL_INC_PATH -I$CHK_TK_INCLUDE_PATH $X_CFLAGS"
 echo $ECHO_N "checking if tk is version $CHK_TK_MAJOR.$CHK_TK_MINOR or later... $ECHO_C" >&6; }
 
 cat > conftest.$ac_ext <<EOF
-#line 23627 "configure"
+#line 23638 "configure"
 #include "confdefs.h"
 
 #include "$CHK_TK_INCLUDE_PATH/$CHK_TK_INC_NAME"
@@ -24624,9 +24635,9 @@ DOCBOOK_ROOT=
 
 # Check whether --with-docbook was given.
 if test "${with_docbook+set}" = set; then
-  withval=$with_docbook; with_umfpack_library=$withval
+  withval=$with_docbook; with_docbook=$withval
 else
-  with_umfpack_library='yes'
+  with_docbook='yes'
 
 fi
 
@@ -24656,7 +24667,7 @@ echo $ECHO_N "checking batik... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 24659 "configure"
+// #line 24670 "configure"
 import org.apache.batik.parser.Parser;
 
 public class conftest {
@@ -24724,7 +24735,7 @@ echo $ECHO_N "checking saxon... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 24727 "configure"
+// #line 24738 "configure"
 import com.icl.saxon.Loader;
 
 public class conftest {
@@ -24792,7 +24803,7 @@ echo $ECHO_N "checking fop... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 24795 "configure"
+// #line 24806 "configure"
 import org.apache.fop.pdf.PDFInfo;
 
 public class conftest {
@@ -24860,7 +24871,7 @@ echo $ECHO_N "checking jeuclid-core... $ECHO_C" >&6; }
           export ac_java_classpath="$jar_resolved:$ac_java_classpath"
 
     cat << \EOF > conftest.java
-// #line 24863 "configure"
+// #line 24874 "configure"
 import net.sourceforge.jeuclid.MathBase;
 
 public class conftest {
@@ -25498,7 +25509,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 25501 "configure"' > conftest.$ac_ext
+  echo '#line 25512 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -27368,11 +27379,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:27371: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:27382: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:27375: \$? = $ac_status" >&5
+   echo "$as_me:27386: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -27658,11 +27669,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:27661: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:27672: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:27665: \$? = $ac_status" >&5
+   echo "$as_me:27676: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -27762,11 +27773,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:27765: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:27776: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:27769: \$? = $ac_status" >&5
+   echo "$as_me:27780: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -30211,7 +30222,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 30214 "configure"
+#line 30225 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -30311,7 +30322,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 30314 "configure"
+#line 30325 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -32732,11 +32743,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:32735: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:32746: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:32739: \$? = $ac_status" >&5
+   echo "$as_me:32750: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -32836,11 +32847,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:32839: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:32850: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:32843: \$? = $ac_status" >&5
+   echo "$as_me:32854: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -34434,11 +34445,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:34437: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:34448: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:34441: \$? = $ac_status" >&5
+   echo "$as_me:34452: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -34538,11 +34549,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:34541: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:34552: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:34545: \$? = $ac_status" >&5
+   echo "$as_me:34556: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -36762,11 +36773,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:36765: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:36776: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:36769: \$? = $ac_status" >&5
+   echo "$as_me:36780: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -37052,11 +37063,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:37055: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:37066: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:37059: \$? = $ac_status" >&5
+   echo "$as_me:37070: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -37156,11 +37167,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:37159: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:37170: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:37163: \$? = $ac_status" >&5
+   echo "$as_me:37174: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -40296,6 +40307,13 @@ echo "$as_me: error: conditional \"IS_64_BITS_CPU\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${NEED_JAVA_TRUE}" && test -z "${NEED_JAVA_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"NEED_JAVA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"NEED_JAVA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${GUI_TRUE}" && test -z "${GUI_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"GUI\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -41205,6 +41223,8 @@ SWIG_RUNTIME_LIBS_DIR!$SWIG_RUNTIME_LIBS_DIR$ac_delim
 SWIG_JAVA!$SWIG_JAVA$ac_delim
 PYTHON!$PYTHON$ac_delim
 GIWS_BIN!$GIWS_BIN$ac_delim
+NEED_JAVA_TRUE!$NEED_JAVA_TRUE$ac_delim
+NEED_JAVA_FALSE!$NEED_JAVA_FALSE$ac_delim
 GUI_TRUE!$GUI_TRUE$ac_delim
 GUI_FALSE!$GUI_FALSE$ac_delim
 JAVASCI_TRUE!$JAVASCI_TRUE$ac_delim
@@ -41260,8 +41280,6 @@ UMFPACK_ENABLE!$UMFPACK_ENABLE$ac_delim
 UMFPACK_TRUE!$UMFPACK_TRUE$ac_delim
 UMFPACK_FALSE!$UMFPACK_FALSE$ac_delim
 PCRE_CONFIG!$PCRE_CONFIG$ac_delim
-PCRE_CFLAGS!$PCRE_CFLAGS$ac_delim
-PCRE_LIBS!$PCRE_LIBS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -41303,6 +41321,8 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+PCRE_CFLAGS!$PCRE_CFLAGS$ac_delim
+PCRE_LIBS!$PCRE_LIBS$ac_delim
 PCRE_VERSION!$PCRE_VERSION$ac_delim
 XMKMF!$XMKMF$ac_delim
 X_CFLAGS!$X_CFLAGS$ac_delim
@@ -41341,7 +41361,7 @@ ENABLE_STATIC_FALSE!$ENABLE_STATIC_FALSE$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 36; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 38; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
