* --without-java has been splited into two directives : * --without-gui * --without-javasci If the two commands are used together, Java won't be checked * better management of without-gui/javasci

diff --git a/scilab/configure b/scilab/configure
--- a/scilab/configure
+++ b/scilab/configure
@@ -882,8 +882,10 @@ ANT
 JAVA_JNI_INCLUDE
 JAVA_JNI_LIBS
 JAVA_HOME
-WITH_JAVA_TRUE
-WITH_JAVA_FALSE
+GUI_TRUE
+GUI_FALSE
+JAVASCI_TRUE
+JAVASCI_FALSE
 GREP
 EGREP
 LIBOBJS
@@ -1566,7 +1568,8 @@ Optional Packages:
   --with-intelcompilers   use Intel C (icc) and Fortran (ifort) proprietary compilers (GNU/Linux only)
   --with-local-xaw        use Xaw3d widgets given with Scilab
   --without-tk            do not compile with TCL/TK
-  --without-java          do not compile java modules
+  --without-javasci       do not compile the Java/Scilab module
+  --without-gui           do not compile the Graphical User Interface (GUI). Intended for embedded/clustering/grid Scilab
   --with-x                use the X Window System
   --with-jdk=DIR          use JDK from DIR
   --with-ant=DIR          use ant from DIR
@@ -4273,9 +4276,16 @@ fi
 
 
 
-# Check whether --with-java was given.
-if test "${with_java+set}" = set; then
-  withval=$with_java;
+# Check whether --with-javasci was given.
+if test "${with_javasci+set}" = set; then
+  withval=$with_javasci;
+fi
+
+
+
+# Check whether --with-gui was given.
+if test "${with_gui+set}" = set; then
+  withval=$with_gui;
 fi
 
 
@@ -9896,7 +9906,7 @@ fi
 ## test for JAVA compiler
 ###########################
 
-if test "$with_java" != no; then
+if test "$with_javasci" == yes -o "$with_gui" == yes; then
    # See if --with-jdk command line argument is given
      # Try to detect the installed JVM, this could be controlled
 	 # by the above --with options
@@ -10080,7 +10090,7 @@ echo "${ECHO_T}$ac_java_classpath" >&6; }
 echo $ECHO_N "checking to see if the java compiler works... $ECHO_C" >&6; }
 
     cat << \EOF > conftest.java
-// #line 10083 "configure"
+// #line 10093 "configure"
 
 
 public class conftest {
@@ -10130,7 +10140,7 @@ echo $ECHO_N "checking type of jvm... $ECHO_C" >&6; }
     if test "x$ac_java_jvm_name" = "x" ; then
 
     cat << \EOF > conftest.java
-// #line 10133 "configure"
+// #line 10143 "configure"
 import gnu.java.io.EncodingManager;
 
 public class conftest {
@@ -10178,7 +10188,7 @@ echo $ECHO_N "checking java API version... $ECHO_C" >&6; }
 
 
     cat << \EOF > conftest.java
-// #line 10181 "configure"
+// #line 10191 "configure"
 import java.nio.charset.Charset;
 
 public class conftest {
@@ -10205,7 +10215,7 @@ EOF
 
 
     cat << \EOF > conftest.java
-// #line 10208 "configure"
+// #line 10218 "configure"
 import java.lang.StringBuilder;
 
 public class conftest {
@@ -11377,7 +11387,7 @@ echo "$as_me: error: Cannot find ant" >&2;}
 
 
 cat >>confdefs.h <<\_ACEOF
-#define WITH_JAVA
+#define WITH_GUI
 _ACEOF
 
 	else
@@ -11392,12 +11402,20 @@ echo "$as_me: WARNING: We do not support $ac_java_jvm_name yet" >&2;}
 
 
 fi
- if test "$with_java" != no; then
-  WITH_JAVA_TRUE=
-  WITH_JAVA_FALSE='#'
+ if test "$with_gui" == yes; then
+  GUI_TRUE=
+  GUI_FALSE='#'
 else
-  WITH_JAVA_TRUE='#'
-  WITH_JAVA_FALSE=
+  GUI_TRUE='#'
+  GUI_FALSE=
+fi
+
+ if test "$with_javasci" == yes; then
+  JAVASCI_TRUE=
+  JAVASCI_FALSE='#'
+else
+  JAVASCI_TRUE='#'
+  JAVASCI_FALSE=
 fi
 
 
@@ -17588,7 +17606,7 @@ CPPFLAGS="$CPPFLAGS -I$CHK_TCL_INCLUDE_PATH"
 { echo "$as_me:$LINENO: checking if tcl is version $CHK_TCL_MAJOR.$CHK_TCL_MINOR or later" >&5
 echo $ECHO_N "checking if tcl is version $CHK_TCL_MAJOR.$CHK_TCL_MINOR or later... $ECHO_C" >&6; }
 cat > conftest.$ac_ext <<EOF
-#line 17591 "configure"
+#line 17609 "configure"
 #include "confdefs.h"
 
 #include "$CHK_TCL_INCLUDE_PATH/$CHK_TCL_INC_NAME"
@@ -17949,7 +17967,7 @@ CPPFLAGS="$CPPFLAGS $TCL_INC_PATH -I$CHK_TK_INCLUDE_PATH $X_CFLAGS"
 echo $ECHO_N "checking if tk is version $CHK_TK_MAJOR.$CHK_TK_MINOR or later... $ECHO_C" >&6; }
 
 cat > conftest.$ac_ext <<EOF
-#line 17952 "configure"
+#line 17970 "configure"
 #include "confdefs.h"
 
 #include "$CHK_TK_INCLUDE_PATH/$CHK_TK_INC_NAME"
@@ -19488,13 +19506,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:19491: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:19509: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:19494: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:19512: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:19497: output\"" >&5)
+  (eval echo "\"\$as_me:19515: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -20580,7 +20598,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 20583 "configure"' > conftest.$ac_ext
+  echo '#line 20601 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -22174,11 +22192,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:22177: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:22195: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:22181: \$? = $ac_status" >&5
+   echo "$as_me:22199: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -22496,11 +22514,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:22499: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:22517: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:22503: \$? = $ac_status" >&5
+   echo "$as_me:22521: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -22601,11 +22619,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:22604: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:22622: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:22608: \$? = $ac_status" >&5
+   echo "$as_me:22626: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -22656,11 +22674,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:22659: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:22677: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:22663: \$? = $ac_status" >&5
+   echo "$as_me:22681: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -25405,7 +25423,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 25408 "configure"
+#line 25426 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -25505,7 +25523,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 25508 "configure"
+#line 25526 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -27527,11 +27545,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:27530: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:27548: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:27534: \$? = $ac_status" >&5
+   echo "$as_me:27552: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -27626,11 +27644,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:27629: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:27647: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:27633: \$? = $ac_status" >&5
+   echo "$as_me:27651: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -27678,11 +27696,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:27681: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:27699: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:27685: \$? = $ac_status" >&5
+   echo "$as_me:27703: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -29053,11 +29071,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:29056: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:29074: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:29060: \$? = $ac_status" >&5
+   echo "$as_me:29078: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -29152,11 +29170,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:29155: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:29173: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:29159: \$? = $ac_status" >&5
+   echo "$as_me:29177: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -29204,11 +29222,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:29207: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:29225: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:29211: \$? = $ac_status" >&5
+   echo "$as_me:29229: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -31436,12 +31454,20 @@ _ACEOF
 
 ## Faudriat mettre -I/home/sylvestre/dev/scilab5/libs/MALLOC/includes/ juste dans les modules ou c'est necessaire
 
-ac_config_files="$ac_config_files libs/lapack/Makefile libs/blas/Makefile libs/MALLOC/Makefile libs/dynamiclibrary/Makefile libs/hashtable/Makefile libs/f2c/Makefile libs/libst/Makefile modules/helptools/Makefile modules/data_structures/Makefile modules/differential_equations/Makefile modules/optimization/Makefile modules/elementaries_functions/Makefile modules/special_functions/Makefile modules/io/Makefile modules/shell/Makefile modules/jvm/Makefile modules/sound/Makefile modules/statistics/Makefile modules/mexlib/Makefile modules/sparse/Makefile modules/linear_algebra/Makefile modules/polynomials/Makefile modules/symbolic/Makefile modules/signal_processing/Makefile modules/arnoldi/Makefile modules/interpolation/Makefile modules/intersci/Makefile modules/localization/Makefile modules/metanet/Makefile modules/cacsd/Makefile modules/boolean/Makefile modules/integer/Makefile modules/double/Makefile modules/fileio/Makefile modules/string/Makefile modules/string_V2/Makefile modules/time/Makefile modules/graphics/Makefile modules/gui/Makefile modules/pvm/Makefile modules/randlib/Makefile modules/tclsci/Makefile modules/wintools/Makefile modules/core/Makefile modules/fftw/Makefile modules/scicos/Makefile modules/scicos/src/ocaml/Makefile modules/functions/Makefile modules/incremental_link/Makefile modules/others/Makefile modules/overloading/Makefile modules/javasci/Makefile modules/maple2scilab/Makefile modules/m2sci/Makefile modules/compatibility_functions/Makefile modules/texmacs/Makefile modules/scipad/Makefile modules/scilab2fortran/Makefile modules/development_tools/Makefile modules/Makefile libs/Makefile Makefile modules/helptools/macros/xmlfiletohtml.sci"
+ac_config_files="$ac_config_files libs/lapack/Makefile libs/blas/Makefile libs/MALLOC/Makefile libs/dynamiclibrary/Makefile libs/hashtable/Makefile libs/f2c/Makefile libs/libst/Makefile modules/helptools/Makefile modules/data_structures/Makefile modules/differential_equations/Makefile modules/optimization/Makefile modules/elementaries_functions/Makefile modules/special_functions/Makefile modules/io/Makefile modules/shell/Makefile modules/jvm/Makefile modules/sound/Makefile modules/statistics/Makefile modules/mexlib/Makefile modules/sparse/Makefile modules/linear_algebra/Makefile modules/polynomials/Makefile modules/symbolic/Makefile modules/signal_processing/Makefile modules/arnoldi/Makefile modules/interpolation/Makefile modules/intersci/Makefile modules/localization/Makefile modules/metanet/Makefile modules/cacsd/Makefile modules/boolean/Makefile modules/integer/Makefile modules/double/Makefile modules/fileio/Makefile modules/string/Makefile modules/string_V2/Makefile modules/time/Makefile modules/graphics/Makefile modules/gui/Makefile modules/pvm/Makefile modules/randlib/Makefile modules/tclsci/Makefile modules/wintools/Makefile modules/core/Makefile modules/fftw/Makefile modules/scicos/Makefile modules/scicos/src/ocaml/Makefile modules/functions/Makefile modules/incremental_link/Makefile modules/others/Makefile modules/overloading/Makefile modules/javasci/Makefile modules/maple2scilab/Makefile modules/m2sci/Makefile modules/compatibility_functions/Makefile modules/texmacs/Makefile modules/scipad/Makefile modules/scilab2fortran/Makefile modules/development_tools/Makefile modules/Makefile libs/Makefile tools/Makefile tools/lib/Makefile tools/name/Makefile Makefile modules/helptools/macros/xmlfiletohtml.sci"
 #MAN_FR MAN_ENG
 #modules/mpi/Makefile
 #for top_builddir in . .. ../.. $ac_auxdir $ac_auxdir/..; do
 #  test -f $top_builddir/configure && break
 #done
+
+#tools/gengatsce/Makefile
+#tools/gensosce/Makefile
+#tools/forwin/Makefile
+#tools/gensomex/Makefile
+#tools/printer/Makefile
+#tools/tomake/Makefile
+
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -31588,10 +31614,17 @@ echo "$as_me: error: conditional \"IS_MIPS_SGI_IRIX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${WITH_JAVA_TRUE}" && test -z "${WITH_JAVA_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"WITH_JAVA\" was never defined.
+if test -z "${GUI_TRUE}" && test -z "${GUI_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"GUI\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"WITH_JAVA\" was never defined.
+echo "$as_me: error: conditional \"GUI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${JAVASCI_TRUE}" && test -z "${JAVASCI_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"JAVASCI\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"JAVASCI\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -32612,6 +32645,9 @@ do
     "modules/development_tools/Makefile") CONFIG_FILES="$CONFIG_FILES modules/development_tools/Makefile" ;;
     "modules/Makefile") CONFIG_FILES="$CONFIG_FILES modules/Makefile" ;;
     "libs/Makefile") CONFIG_FILES="$CONFIG_FILES libs/Makefile" ;;
+    "tools/Makefile") CONFIG_FILES="$CONFIG_FILES tools/Makefile" ;;
+    "tools/lib/Makefile") CONFIG_FILES="$CONFIG_FILES tools/lib/Makefile" ;;
+    "tools/name/Makefile") CONFIG_FILES="$CONFIG_FILES tools/name/Makefile" ;;
     "Makefile") CONFIG_FILES="$CONFIG_FILES Makefile" ;;
     "modules/helptools/macros/xmlfiletohtml.sci") CONFIG_FILES="$CONFIG_FILES modules/helptools/macros/xmlfiletohtml.sci" ;;
 
@@ -32835,8 +32871,10 @@ ANT!$ANT$ac_delim
 JAVA_JNI_INCLUDE!$JAVA_JNI_INCLUDE$ac_delim
 JAVA_JNI_LIBS!$JAVA_JNI_LIBS$ac_delim
 JAVA_HOME!$JAVA_HOME$ac_delim
-WITH_JAVA_TRUE!$WITH_JAVA_TRUE$ac_delim
-WITH_JAVA_FALSE!$WITH_JAVA_FALSE$ac_delim
+GUI_TRUE!$GUI_TRUE$ac_delim
+GUI_FALSE!$GUI_FALSE$ac_delim
+JAVASCI_TRUE!$JAVASCI_TRUE$ac_delim
+JAVASCI_FALSE!$JAVASCI_FALSE$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
@@ -32897,7 +32935,7 @@ tcldir!$tcldir$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 81; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 83; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
